name: shrapnel_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  esp_softap_provisioning:
    git:
      url: https://github.com/ShrapnelDSP/esp_softap_provisioning.git
      ref: shrapnel
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
