name: shrapnel
description: Digital guitar effects

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  esp_softap_provisioning:
    git:
      url: https://github.com/ShrapnelDSP/esp_softap_provisioning.git
      ref: shrapnel
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  logging: ^1.0.2
  pausable_timer: ^3.1.0+3
  provider: ^6.0.0
  remove_from_coverage: ^2.0.0
  rxdart: ^0.27.3
  state_notifier: ^1.0.0
  uuid: ^3.0.6
  vector_math: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
