name: shrapnel
description: Digital guitar effects

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  json_annotation: ^4.4.0
  logging: ^1.0.2
  provider: ^6.0.0
  remove_from_coverage: ^2.0.0
  rxdart: ^0.27.3
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
