name: shrapnel
description: Digital guitar effects

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  async: ^2.11.0
  esp_softap_provisioning:
    git:
      url: https://github.com/ShrapnelDSP/esp_softap_provisioning.git
      ref: shrapnel
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.2.0
  google_fonts: ^6.1.0
  logging: ^1.0.2
  mockito: ^5.4.4
  path: ^1.8.3
  pausable_timer: ^3.1.0+3
  protobuf: ^3.1.0
  remove_from_coverage: ^2.0.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  vector_math: ^2.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  flutter_libserialport: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  integration_test:
    sdk: flutter
  libserialport: ^0.3.0+1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
