name: shrapnel_test_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.2.6

dependencies:
  esp_softap_provisioning:
    git:
      url: https://github.com/ShrapnelDSP/esp_softap_provisioning.git
      ref: shrapnel
  libserialport: ^0.3.0
  logging: ^1.2.0
  path: ^1.8.0
  shrapnel_common:
    path: ../shrapnel_common

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
