[package]
name = "shrapnel_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7.1"

[dev-dependencies]
mockall = "0.12.1"
