ShrapnelDSP: effects/abstract_dsp/include/abstract_dsp.h File Reference
abstract_dsp.h File Reference
Abstraction layer for DSP functionality.
Typedefs
typedef struct dspal_delayline * dspal_delayline_t
Enumerations
enum dspal_err_t { DSPAL_OK , DSPAL_FAIL }
Functions
dspal_err_t dspal_biquad_design_lowpass (float *coeffs, float f, float q_factor)
void dspal_multiply (const float *in1, const float *in2, float *out, size_t buf_size)
dspal_delayline_t dspal_delayline_create (size_t max_samples)
void dspal_delayline_destroy (dspal_delayline_t delayline)
void dspal_delayline_set_delay (dspal_delayline_t delayline, float delay)
void dspal_delayline_push_sample (dspal_delayline_t delayline, float sample)
float dspal_delayline_pop_sample (dspal_delayline_t delayline)
Detailed Description
Abstraction layer for DSP functionality.
This enables the use of use of platform native, and potentially optimised DSP functions in effects in a generic way.
Definition in file abstract_dsp.h.
Typedef Documentation
dspal_delayline_t
typedef struct dspal_delayline* dspal_delayline_t
Definition at line 31 of file abstract_dsp.h.
Enumeration Type Documentation
dspal_err_t
enum dspal_err_t
Enumerator
DSPAL_OK
DSPAL_FAIL
Definition at line 33 of file abstract_dsp.h.
             {
    DSPAL_OK,
    DSPAL_FAIL,
} dspal_err_t;
Function Documentation
dspal_biquad_design_lowpass()
dspal_err_t dspal_biquad_design_lowpass (float * coeffs, float f, float q_factor)
Definition at line 28 of file abstract_dsp_juce.cpp.
{
    // TODO check if the frequency is scaled correctly
    auto juce_coeffs = juce::dsp::IIR::Coefficients<float>::makeLowPass(1, f, q_factor);
    auto raw_coeffs = juce_coeffs->getRawCoefficients();
    assert(2 == juce_coeffs->getFilterOrder());
    // These coefficients are expected to be normalised
    assert(5 == juce_coeffs->coefficients.size());
    memcpy(coeffs, raw_coeffs, 5*sizeof(float));
    return DSPAL_OK;
}
References DSPAL_FAIL, and DSPAL_OK.
Referenced by gate_set_sample_rate().
dspal_delayline_create()
dspal_delayline_t dspal_delayline_create (size_t max_samples)
Definition at line 28 of file delayline_c.cpp.
{
    dspal_delayline_t delayline = new dspal_delayline;
    delayline->delayline.reset(new shrapnel::dsp::DelayLine(max_samples));
    return delayline;
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::prepare().
dspal_delayline_destroy()
void dspal_delayline_destroy (dspal_delayline_t delayline)
Definition at line 37 of file delayline_c.cpp.
{
    delete delayline;
}
Referenced by shrapnel::effect::Chorus::reset().
dspal_delayline_pop_sample()
float dspal_delayline_pop_sample (dspal_delayline_t delayline)
Definition at line 52 of file delayline_c.cpp.
{
    return delayline->delayline->pop_sample();
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().
dspal_delayline_push_sample()
void dspal_delayline_push_sample (dspal_delayline_t delayline, float sample)
Definition at line 47 of file delayline_c.cpp.
{
    delayline->delayline->push_sample(sample);
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().
dspal_delayline_set_delay()
void dspal_delayline_set_delay (dspal_delayline_t delayline, float delay)
Definition at line 42 of file delayline_c.cpp.
{
    delayline->delayline->set_delay(delay);
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().
dspal_multiply()
void dspal_multiply (const float * in1, const float * in2, float * out, size_t buf_size)
Definition at line 44 of file abstract_dsp_juce.cpp.
{
    for(size_t i = 0; i < buf_size; i++)
    {
        out[i] = in1[i] * in2[i];
    }
}
Referenced by gate_process().