ShrapnelDSP: firmware/components/audio_events/include/audio_events.h File Reference
audio_events.h File Reference
Enumerations
enum audio_event_t { AUDIO_EVENT_OUTPUT_CLIPPED = (1 << 0) }
Functions
esp_err_t audio_event_init (void)
void audio_event_send_callback (const char *message, int fd)
Called when an event is triggered.
Variables
EventGroupHandle_t g_audio_event_group
Enumeration Type Documentation
audio_event_t
enum audio_event_t
Enumerator
AUDIO_EVENT_OUTPUT_CLIPPED
Definition at line 30 of file audio_events.h.
{
    AUDIO_EVENT_OUTPUT_CLIPPED = (1 << 0),
} audio_event_t;
Function Documentation
audio_event_init()
esp_err_t audio_event_init (void)
Definition at line 66 of file audio_events.c.
{
    g_audio_event_group = xEventGroupCreate();
    if(g_audio_event_group == NULL)
    {
        ESP_LOGE(TAG, "Failed to create event group");
        return ESP_FAIL;
    }
    if(pdPASS != xTaskCreate(audio_event_task, "audio event", 2000, NULL, 4, NULL))
    {
        ESP_LOGE(TAG, "Failed to create task");
        return ESP_FAIL;
    }
    return ESP_OK;
}
References audio_event_task(), and g_audio_event_group.
Referenced by shrapnel::app_main().
audio_event_send_callback()
void audio_event_send_callback (const char * message, int fd)
Called when an event is triggered.
Parameters
message JSON representation of the audio event
fd The socket file descriptor for the client initiating this event
fd is used to prevent a client from receiving a message that was triggered by it. The implementation of this callback must ensure that the message is transmitted only to clients where their descriptor is different from fd.
Definition at line 480 of file main.cpp.
{
    shrapnel::audio_event_message_t event_message = {
        .message = {0},
        .fd = fd,
    };
    snprintf(event_message.message, sizeof(event_message.message), "%s", message);
    ESP_LOGD(TAG, "%s %s", __FUNCTION__, event_message.message);
    ESP_LOGD(TAG, "%s %s", __FUNCTION__, pcTaskGetTaskName(NULL));
    if(errQUEUE_FULL ==
            xQueueSendToBack(shrapnel::out_queue,
                             &event_message,
                             100 / portTICK_PERIOD_MS))
    {
        ESP_LOGE(TAG, "Failed to send message to websocket");
        return;
    }
    if(!xSemaphoreTake(shrapnel::work_semaphore, 1000 / portTICK_PERIOD_MS))
    {
        ESP_LOGE(TAG, "work semaphore timed out");
        return;
    }
    esp_err_t rc = httpd_queue_work(
            shrapnel::_server,
            shrapnel::websocket_send,
            shrapnel::_server);
    if(ESP_OK != rc)
    {
        ESP_LOGE(TAG, "failed to queue work for server");
        xQueueReset(shrapnel::out_queue);
    }
}
References shrapnel::_server, shrapnel::audio_event_message_t::message, shrapnel::out_queue, shrapnel::websocket_send(), and shrapnel::work_semaphore.
Referenced by audio_event_task(), and shrapnel::EventSend::send().
Variable Documentation
g_audio_event_group
EventGroupHandle_t g_audio_event_group extern
Definition at line 27 of file audio_events.c.
Referenced by audio_event_init(), audio_event_task(), and process_samples().