ShrapnelDSP: shrapnel::wifi_provisioning::WiFiProvisioning Class Reference
shrapnel::wifi_provisioning::WiFiProvisioning Class Reference final
#include <wifi_provisioning.h>
Public Member Functions
WiFiProvisioning (void)
void wait_for_provisioning (void)
~WiFiProvisioning ()
Static Public Member Functions
static bool is_provisioned (void)
static void start (void)
Detailed Description
Definition at line 41 of file wifi_provisioning.h.
Constructor & Destructor Documentation
WiFiProvisioning()
shrapnel::wifi_provisioning::WiFiProvisioning::WiFiProvisioning (void) inline
Definition at line 162 of file wifi_provisioning.h.
                       : queue()
{
    // XXX: Make sure to deregister the handlers in the destructor
    ESP_ERROR_CHECK(esp_event_handler_register(
                WIFI_PROV_EVENT,
                ESP_EVENT_ANY_ID,
                provisioning_event_handler,
                &queue));
    ESP_ERROR_CHECK(esp_event_handler_register(
                WIFI_EVENT,
                ESP_EVENT_ANY_ID,
                wifi_event_handler,
                nullptr));
    ESP_ERROR_CHECK(esp_event_handler_register(
                IP_EVENT,
                IP_EVENT_STA_GOT_IP,
                wifi_event_handler,
                nullptr));
    wifi_prov_mgr_config_t config = {
        .scheme = wifi_prov_scheme_softap,
    };
    ESP_ERROR_CHECK(wifi_prov_mgr_init(config));
}
~WiFiProvisioning()
shrapnel::wifi_provisioning::WiFiProvisioning::~WiFiProvisioning () inline
Definition at line 242 of file wifi_provisioning.h.
                    {
    ESP_ERROR_CHECK(esp_event_handler_unregister(
                WIFI_PROV_EVENT,
                ESP_EVENT_ANY_ID,
                provisioning_event_handler));
    ESP_ERROR_CHECK(esp_event_handler_unregister(
                WIFI_EVENT,
                ESP_EVENT_ANY_ID,
                wifi_event_handler));
    ESP_ERROR_CHECK(esp_event_handler_unregister(
                IP_EVENT,
                IP_EVENT_STA_GOT_IP,
                wifi_event_handler));
    wifi_prov_mgr_deinit();
}
Member Function Documentation
is_provisioned()
static bool shrapnel::wifi_provisioning::WiFiProvisioning::is_provisioned (void) inline static
Definition at line 188 of file wifi_provisioning.h.
{
    bool provisioned = false;
    ESP_ERROR_CHECK(wifi_prov_mgr_is_provisioned(&provisioned));
    return provisioned;
}
start()
static void shrapnel::wifi_provisioning::WiFiProvisioning::start (void) inline static
Definition at line 195 of file wifi_provisioning.h.
{
    ESP_LOGI(TAG, "Starting provisioning");
    char service_name[16];
    get_device_service_name(service_name, sizeof(service_name));
    wifi_prov_security_t security = WIFI_PROV_SECURITY_1;
    constexpr std::string_view proof_of_possession{"abcd1234"};
    wifi_prov_security1_params_t params{
        .data{reinterpret_cast<const uint8_t *>(proof_of_possession.data())},
        .len{proof_of_possession.size()},
    };
    const char *service_key = NULL;
    ESP_ERROR_CHECK(wifi_prov_mgr_start_provisioning(security, &params, service_name, service_key));
}
Referenced by wait_for_provisioning().
wait_for_provisioning()
void shrapnel::wifi_provisioning::WiFiProvisioning::wait_for_provisioning (void) inline
Definition at line 213 of file wifi_provisioning.h.
{
    start();
    while(1)
    {
        Event event;
        int rc = queue.receive(&event, portMAX_DELAY);
        assert(rc == true);
        if(event.type == EVENT_PROVISIONING_SUCCESSFUL)
        {
            break;
        }
        else if(event.type == EVENT_PROVISIONING_FAILED)
        {
            wifi_prov_mgr_stop_provisioning();
            wifi_prov_mgr_wait();
            start();
        }
        else
        {
            ESP_LOGE(TAG, "unhandled event %d", event.type);
        }
    }
    ESP_LOGI(TAG, "Provisioning finished");
}
References shrapnel::Queue< T, MAX_SIZE >::receive(), and start().
The documentation for this class was generated from the following file:
firmware/components/wifi/include/wifi_provisioning.h