ShrapnelDSP: shrapnel::presets::PresetsManager Class Reference
shrapnel::presets::PresetsManager Class Reference
#include <presets_manager.h>
Public Member Functions
int create (const PresetData &preset, id_t &id_out)
std::optional< PresetData > read (id_t id)
int update (id_t id, const PresetData &preset)
int remove (id_t id)
void for_each (etl::delegate< void(id_t, const PresetData &)> callback)
Detailed Description
Definition at line 28 of file presets_manager.h.
Member Function Documentation
create()
int shrapnel::presets::PresetsManager::create (const PresetData & preset, id_t & id_out)
Definition at line 26 of file preset_manager.cpp.
{
    std::array<uint8_t, 100> buffer;
    auto data = std::span<uint8_t, std::dynamic_extent>(buffer);
    int rc = serialise_preset(preset, data);
    if(rc != 0)
    {
        return -1;
    }
    rc = storage->create(data, id_out);
    if(rc != 0)
    {
        return -1;
    }
    return 0;
}
References shrapnel::presets::serialise_preset().
for_each()
void shrapnel::presets::PresetsManager::for_each (etl::delegate< void(id_t, const PresetData &)> callback)
Definition at line 97 of file preset_manager.cpp.
{
    for(const auto &entry : *storage)
    {
        auto id = key_to_id(entry.key);
        auto preset = read(id);
        if(!preset.has_value())
        {
            ESP_LOGE(TAG, "Failed to read preset at key %s", entry.key);
            continue;
        }
        callback(id, *preset);
    }
}
References read().
read()
std::optional< PresetData > shrapnel::presets::PresetsManager::read (id_t id)
Definition at line 46 of file preset_manager.cpp.
{
    std::array<uint8_t, 100> buffer;
    auto data = std::span<uint8_t, std::dynamic_extent>(buffer);
    int rc = storage->load(id, data);
    if(rc != 0)
    {
        return std::nullopt;
    }
    PresetData preset;
    rc = deserialise_preset(data, preset);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return preset;
}
References shrapnel::presets::deserialise_preset().
Referenced by for_each().
remove()
int shrapnel::presets::PresetsManager::remove (id_t id)
Definition at line 86 of file preset_manager.cpp.
{
    int rc = storage->remove(id);
    if(rc != 0)
    {
        return -1;
    }
    return 0;
}
update()
int shrapnel::presets::PresetsManager::update (id_t id, const PresetData & preset)
Definition at line 66 of file preset_manager.cpp.
{
    std::array<uint8_t, 100> buffer;
    auto data = std::span<uint8_t, std::dynamic_extent>(buffer);
    int rc = serialise_preset(preset, data);
    if(rc != 0)
    {
        return -1;
    }
    rc = storage->save(id, data);
    if(rc != 0)
    {
        return -1;
    }
    return 0;
}
References shrapnel::presets::serialise_preset().
The documentation for this class was generated from the following files:
firmware/components/presets/include/presets_manager.h
firmware/components/presets/src/preset_manager.cpp