ShrapnelDSP: shrapnel::dsp::IirFilter Class Reference
shrapnel::dsp::IirFilter Class Reference final
#include <iir_concrete.h>
Public Member Functions
IirFilter (void)
void process (const float *in, float *out, size_t buf_size) override
void reset (void) override
void set_coefficients (std::array< float, 6 > new_coefficients) override
void set_coefficients (std::array< float, 8 > new_coefficients) override
void set_coefficients (std::array< float, 10 > new_coefficients) override
IirFilter (void)
void process (const float *in, float *out, size_t buf_size) override
void reset (void) override
void set_coefficients (std::array< float, 6 > new_coefficients) override
void set_coefficients (std::array< float, 8 > new_coefficients) override
void set_coefficients (std::array< float, 10 > new_coefficients) override
Public Member Functions inherited from shrapnel::dsp::IirFilterBase
virtual void process (const float *in, float *out, std::size_t buf_size)=0
virtual void reset (void)=0
virtual void set_coefficients (std::array< float, 6 > new_coefficients)=0
virtual void set_coefficients (std::array< float, 8 > new_coefficients)=0
virtual void set_coefficients (std::array< float, 10 > new_coefficients)=0
Detailed Description
Definition at line 31 of file iir_concrete.h.
Constructor & Destructor Documentation
IirFilter() [1/2]
shrapnel::dsp::IirFilter::IirFilter (void) inline
Definition at line 33 of file iir_concrete.h.
                    : order(2)
    {
        coefficients.fill(0);
        reset();
    }
References reset().
IirFilter() [2/2]
shrapnel::dsp::IirFilter::IirFilter (void) inline
Definition at line 32 of file iir_concrete.h.
    {
        filter.reset();
    }
Member Function Documentation
process() [1/2]
void shrapnel::dsp::IirFilter::process (const float * in, float * out, size_t buf_size) inline override
Definition at line 39 of file iir_concrete.h.
    {
        if(order == 2)
        {
            dsps_biquad_f32_ae32(in, out, buf_size, coefficients.data(), delay.data());
        }
        else
        {
            iir_process(in, out, buf_size, coefficients.data(), delay.data(), order * 2 + 2);
        }
    }
References iir_process().
Referenced by gate_analyse(), ContourFilter::process(), shrapnel::effect::valvestate::FMVFilter::process(), shrapnel::effect::valvestate::GainControl::process(), shrapnel::effect::valvestate::InputFilter::process(), and shrapnel::effect::Wah::process().
process() [2/2]
void shrapnel::dsp::IirFilter::process (const float * in, float * out, size_t buf_size) inline override
Definition at line 37 of file iir_concrete.h.
    {
        if(in == out)
        {
            auto block = juce::dsp::AudioBlock<float>(&out, 1, 0, buf_size);
            auto context = juce::dsp::ProcessContextReplacing<float> (block);
            filter.process(context);
        }
        else
        {
            auto in_block = juce::dsp::AudioBlock<const float>(&in, 1, 0, buf_size);
            auto out_block = juce::dsp::AudioBlock<float>(&out, 1, 0, buf_size);
            auto context = juce::dsp::ProcessContextNonReplacing<float> (in_block, out_block);
            filter.process(context);
        }
    }
reset() [1/2]
void shrapnel::dsp::IirFilter::reset (void) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 51 of file iir_concrete.h.
    {
        delay.fill(0);
    }
Referenced by IirFilter(), ContourFilter::prepare(), shrapnel::effect::valvestate::FMVFilter::prepare(), shrapnel::effect::valvestate::GainControl::prepare(), shrapnel::effect::valvestate::InputFilter::prepare(), shrapnel::effect::valvestate::FMVFilter::reset(), shrapnel::effect::valvestate::InputFilter::reset(), ContourFilter::reset(), and shrapnel::effect::valvestate::GainControl::reset().
reset() [2/2]
void shrapnel::dsp::IirFilter::reset (void) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 54 of file iir_concrete.h.
    {
        filter.reset();
    }
set_coefficients() [1/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 10 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 82 of file iir_concrete.h.
    {
        order = 4;
        coefficients = new_coefficients;
    }
set_coefficients() [2/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 10 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 71 of file iir_concrete.h.
    {
        filter.coefficients =
            new juce::dsp::IIR::Coefficients<float>(new_coefficients);
    }
set_coefficients() [3/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 6 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 56 of file iir_concrete.h.
    {
        order = 2;
        size_t out_index = 0;
        for(int i = 0; i < 6; i++)
        {
            if(i == 3)
            {
                continue;
            }
            coefficients[out_index] = new_coefficients[i] / new_coefficients[3];
            out_index++;
        }
    }
Referenced by gate_set_sample_rate(), shrapnel::effect::valvestate::InputFilter::prepare(), shrapnel::effect::Wah::process(), ContourFilter::set_parameter(), shrapnel::effect::valvestate::GainControl::set_parameters(), shrapnel::effect::valvestate::FMVFilter::set_parameters(), and shrapnel::effect::Wah::set_sample_rate().
set_coefficients() [4/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 6 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 59 of file iir_concrete.h.
    {
        filter.coefficients =
            new juce::dsp::IIR::Coefficients<float>(new_coefficients);
    }
set_coefficients() [5/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 8 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 73 of file iir_concrete.h.
    {
        order = 3;
        for(int i = 0; i < new_coefficients.size(); i++)
        {
            coefficients[i] = new_coefficients[i];
        }
    }
set_coefficients() [6/6]
void shrapnel::dsp::IirFilter::set_coefficients (std::array< float, 8 > new_coefficients) inline override virtual
Implements shrapnel::dsp::IirFilterBase.
Definition at line 65 of file iir_concrete.h.
    {
        filter.coefficients =
            new juce::dsp::IIR::Coefficients<float>(new_coefficients);
    }
The documentation for this class was generated from the following files:
effects/abstract_dsp/esp32/include/iir_concrete.h
effects/abstract_dsp/juce/include/iir_concrete.h