ShrapnelDSP: shrapnel::MainThread< MAX_PARAMETERS, QUEUE_LEN > Class Template Reference
shrapnel::MainThread< MAX_PARAMETERS, QUEUE_LEN > Class Template Reference
#include <main_thread.h>
Public Member Functions
MainThread (SendMessageCallback a_send_message, Queue< AppMessage, QUEUE_LEN > &a_in_queue, midi::MidiUartBase *a_midi_uart, std::shared_ptr< AudioParameters > a_audio_params, persistence::Storage &a_persistence)
void loop ()
Detailed Description
template<std::size_t MAX_PARAMETERS, std::size_t QUEUE_LEN>
class shrapnel::MainThread< MAX_PARAMETERS, QUEUE_LEN >
Definition at line 219 of file main_thread.h.
Constructor & Destructor Documentation
MainThread()
template<std::size_t MAX_PARAMETERS, std::size_t QUEUE_LEN> shrapnel::MainThread< MAX_PARAMETERS, QUEUE_LEN >::MainThread (SendMessageCallback a_send_message, Queue< AppMessage, QUEUE_LEN > & a_in_queue, midi::MidiUartBase * a_midi_uart, std::shared_ptr< AudioParameters > a_audio_params, persistence::Storage & a_persistence) inline
Definition at line 222 of file main_thread.h.
        : send_message{a_send_message},
          in_queue{a_in_queue},
          parameter_observer{a_persistence},
          clipping_throttle_timer{
              "clipping throttle", pdMS_TO_TICKS(1000), false},
          midi_message_notify_timer{
              "midi notify",
              pdMS_TO_TICKS(100),
              true,
              os::Timer::Callback::
                  create<MainThread, &MainThread::clear_midi_notify_waiting>(
                      *this)},
          midi_uart{a_midi_uart},
          last_midi_message{},
          last_notified_midi_message{},
          midi_decoder{std::make_unique<midi::Decoder>(
              midi::Decoder::Callback::create<MainThread,
                                              &MainThread::on_midi_message>(
                  *this))},
          midi_mutex{},
          audio_params{a_audio_params},
          cmd_handling{
              std::make_unique<parameters::CommandHandling<AudioParameters>>(
                  a_audio_params,
                  parameters::CommandHandling<AudioParameters>::
                      SendMessageCallback::create<
                          MainThread,
                          &MainThread::cmd_handling_send_message>(*this))}
    {
        auto create_and_load_parameter = [&](const parameters::id_t &name,
                                             float minimum,
                                             float maximum,
                                             float default_value)
        {
            std::optional<float> loaded_value;
            etl::string<128> json_string{};
            int rc = a_persistence.load(name.data(), json_string);
            if(rc != 0)
            {
                ESP_LOGW(TAG, "Parameter %s failed to load", name.data());
                goto out;
            }
            {
                rapidjson::Document document;
                document.Parse(json_string.data());
                if(!document.HasParseError())
                {
                    loaded_value = midi::from_json<float>(document);
                }
                else
                {
                    ESP_LOGE(TAG,
                             "document failed to parse '%s'",
                             json_string.data());
                }
            }
        out:
            auto range = maximum - minimum;
            rc = a_audio_params->create_and_add_parameter(
                name,
                minimum,
                maximum,
                loaded_value.has_value() ? *loaded_value * range + minimum
                                         : default_value);
            if(rc != 0)
            {
                ESP_LOGE(TAG, "Failed to create parameter %s", name.c_str());
            }
        };
        // XXX: These are duplicated in the JUCE plugin, be sure to update both at
        // the same time
        create_and_load_parameter("ampGain", 0, 1, 0.5);
        create_and_load_parameter("ampChannel", 0, 1, 0);
        create_and_load_parameter("bass", 0, 1, 0.5);
        create_and_load_parameter("middle", 0, 1, 0.5);
        create_and_load_parameter("treble", 0, 1, 0.5);
        //contour gets unstable when set to 0
        create_and_load_parameter("contour", 0.01, 1, 0.5);
        create_and_load_parameter("volume", -30, 0, -15);
        create_and_load_parameter("noiseGateThreshold", -80, 0, -60);
        create_and_load_parameter("noiseGateHysteresis", 0, 5, 0);
        create_and_load_parameter("noiseGateAttack", 1, 50, 10);
        create_and_load_parameter("noiseGateHold", 1, 250, 50);
        create_and_load_parameter("noiseGateRelease", 1, 250, 50);
        create_and_load_parameter("noiseGateBypass", 0, 1, 0);
        create_and_load_parameter("chorusRate", 0.1, 4, 0.95);
        create_and_load_parameter("chorusDepth", 0, 1, 0.3);
        create_and_load_parameter("chorusMix", 0, 1, 0.8);
        create_and_load_parameter("chorusBypass", 0, 1, 1);
        create_and_load_parameter("wahPosition", 0, 1, 0.5);
        create_and_load_parameter("wahVocal", 0, 1, 0);
        create_and_load_parameter("wahBypass", 0, 1, 1);
        a_audio_params->add_observer(parameter_observer);
        auto parameter_notifier = std::make_shared<ParameterUpdateNotifier>(
            a_audio_params, a_send_message);
        [&]
        {
            /* TODO How to reduce the memory usage?
           * - We could store each entry in the table at a different key
           * - Use the streaming API so that the entire message does not have to
           *   be parsed at once?
           * - Replace etl::map with more efficient implementation
           */
            etl::string<1500> mapping_json;
            a_persistence.load("midi_mappings", mapping_json);
            ESP_LOGI(TAG, "saved mappings: %s", mapping_json.c_str());
            rapidjson::Document document;
            document.Parse(mapping_json.c_str());
            auto saved_mappings = midi::from_json<
                etl::map<midi::Mapping::id_t, midi::Mapping, 10>>(document);
            using MidiMappingType =
                midi::MappingManager<ParameterUpdateNotifier, 10, 1>;
            midi_mapping_manager =
                saved_mappings.has_value()
                    ? std::make_unique<MidiMappingType>(parameter_notifier,
                                                        *saved_mappings)
                    : std::make_unique<MidiMappingType>(parameter_notifier);
        }();
        mapping_observer = std::make_unique<MidiMappingObserver<
            midi::MappingManager<ParameterUpdateNotifier, 10, 1>>>(
            a_persistence, *midi_mapping_manager);
        midi_mapping_manager->add_observer(*mapping_observer);
        BaseType_t rc = midi_message_notify_timer.start(portMAX_DELAY);
        if(rc != pdPASS)
        {
            ESP_LOGE(TAG, "Failed to start midi message timer");
        }
        events::input_clipped.test_and_set();
        events::output_clipped.test_and_set();
    }
References shrapnel::midi::from_json(), shrapnel::events::input_clipped, shrapnel::persistence::Storage::load(), shrapnel::events::output_clipped, and shrapnel::os::Timer::start().
Member Function Documentation
loop()
template<std::size_t MAX_PARAMETERS, std::size_t QUEUE_LEN> void shrapnel::MainThread< MAX_PARAMETERS, QUEUE_LEN >::loop () inline
Definition at line 373 of file main_thread.h.
    {
        {
            auto byte = midi_uart->get_byte(0);
            while(byte.has_value())
            {
                ESP_LOGI(TAG, "midi got byte 0x%02x", *byte);
                midi_decoder->decode(*byte);
                byte = midi_uart->get_byte(0);
            }
        }
        if(AppMessage message; in_queue.receive(&message, 0))
        {
            auto fd = message.second;
            std::visit([this, fd](const auto &m) { handle_message(m, fd); },
                       message.first);
        }
        if(!clipping_throttle_timer.is_active())
        {
            if(!events::input_clipped.test_and_set())
            {
                ESP_LOGI(TAG, "input was clipped");
                send_message({events::InputClipped{}, std::nullopt});
                BaseType_t rc =
                    clipping_throttle_timer.start(pdMS_TO_TICKS(10));
                if(rc != pdPASS)
                {
                    ESP_LOGE(TAG, "Failed to start clipping throttle timer");
                }
            }
            if(!events::output_clipped.test_and_set())
            {
                ESP_LOGI(TAG, "output was clipped");
                send_message({events::OutputClipped{}, std::nullopt});
                BaseType_t rc =
                    clipping_throttle_timer.start(pdMS_TO_TICKS(10));
                if(rc != pdPASS)
                {
                    ESP_LOGE(TAG, "Failed to start clipping throttle timer");
                }
            }
        }
        parameter_observer.loop();
        if(!is_midi_notify_waiting.test_and_set() &&
           last_midi_message.has_value() &&
           last_notified_midi_message != *last_midi_message)
        {
            last_notified_midi_message = *last_midi_message;
            send_message(
                {midi::MessageReceived{*last_midi_message}, std::nullopt});
        }
    }
References shrapnel::midi::MidiUartBase::get_byte(), shrapnel::events::input_clipped, shrapnel::os::Timer::is_active(), shrapnel::events::output_clipped, shrapnel::Queue< T, MAX_SIZE >::receive(), and shrapnel::os::Timer::start().
The documentation for this class was generated from the following file:
firmware/main/include/main_thread.h