ShrapnelDSP: shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS > Class Template Reference
shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS > Class Template Reference final
#include <midi_mapping.h>
Public Types
using MapType = etl::map< Mapping::id_t, Mapping, MAX_MAPPINGS >
Public Member Functions
MappingManager (std::shared_ptr< AudioParametersT > a_parameters, std::unique_ptr< persistence::Crud< std::span< uint8_t > > > a_storage)
const etl::imap< Mapping::id_t, Mapping > * get () const
int create (const Mapping &mapping, Mapping::id_t &id_out) override
int read (Mapping::id_t id, Mapping &mapping) override
int update (Mapping::id_t id, const Mapping &mapping) override
int destroy (Mapping::id_t id) override
void for_each (etl::delegate< void(uint32_t, const Mapping &)> callback) override
void process_message (Message message) const
React to a MIDI message by updating an audio parameter if there is a mapping registered.
Public Member Functions inherited from shrapnel::persistence::Crud< Mapping >
virtual ~Crud ()=default
virtual int create (const Mapping &data, uint32_t &id_out)=0
virtual int read (uint32_t id, Mapping &data_out)=0
virtual int update (uint32_t id, const Mapping &data)=0
virtual int destroy (uint32_t id)=0
virtual void for_each (etl::delegate< void(uint32_t, const Mapping &)> callback)=0
Detailed Description
template<typename AudioParametersT, std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS>
class shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >
Definition at line 62 of file midi_mapping.h.
Member Typedef Documentation
MapType
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> using shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::MapType = etl::map<Mapping::id_t, Mapping, MAX_MAPPINGS>
Definition at line 67 of file midi_mapping.h.
Constructor & Destructor Documentation
MappingManager()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::MappingManager (std::shared_ptr< AudioParametersT > a_parameters, std::unique_ptr< persistence::Crud< std::span< uint8_t > > > a_storage) inline
Definition at line 69 of file midi_mapping.h.
        : parameters{a_parameters},
          storage{std::move(a_storage)}
    {
        for_each(
            [this](uint32_t id, const shrapnel::midi::Mapping &mapping) {
                mappings.insert({id, mapping});
            });
    }
References shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::for_each().
Member Function Documentation
create()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> int shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::create (const Mapping & mapping, Mapping::id_t & id_out) inline override
Returns
non-zero on failure
Definition at line 87 of file midi_mapping.h.
    {
        if(mappings.full())
        {
            ESP_LOGE(TAG, "Failed to create new midi mapping, map is full");
            return -1;
        }
        std::array<uint8_t, 256> memory{};
        std::span<uint8_t> buffer{memory};
        auto encoded = api::to_bytes(mapping, buffer);
        if(!encoded.has_value())
        {
            return -1;
        }
        int rc = storage->create(*encoded, id_out);
        if(rc != 0)
        {
            return -1;
        }
        mappings.insert({id_out, mapping});
        this->notify_observers(id_out);
        return 0;
    }
References shrapnel::api::to_bytes().
destroy()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> int shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::destroy (Mapping::id_t id) inline override virtual
Implements shrapnel::persistence::Crud< Mapping >.
Definition at line 169 of file midi_mapping.h.
    {
        int rc = storage->destroy(id);
        if(rc != 0)
        {
            return -1;
        }
        mappings.erase(id);
        this->notify_observers(id);
        return 0;
    }
for_each()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> void shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::for_each (etl::delegate< void(uint32_t, const Mapping &)> callback) inline override
Definition at line 183 of file midi_mapping.h.
    {
        storage->for_each(
            [&callback](uint32_t id, const std::span<uint8_t> &buffer)
            {
                auto decoded = api::from_bytes<Mapping>(buffer);
                if(!decoded.has_value())
                {
                    return;
                }
                callback(id, *decoded);
            });
    }
Referenced by shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::MappingManager().
get()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> const etl::imap< Mapping::id_t, Mapping > * shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::get (void) const inline
Definition at line 81 of file midi_mapping.h.
    {
        return &mappings;
    }
process_message()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> void shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::process_message (Message message) const inline
React to a MIDI message by updating an audio parameter if there is a mapping registered.
Definition at line 201 of file midi_mapping.h.
    {
        auto cc_params = get_if<Message::ControlChange>(&message.parameters);
        if(!cc_params)
            return;
        for(const auto &[_, mapping] : mappings)
        {
            if(mapping.midi_channel != message.channel)
            {
                continue;
            }
            if(mapping.cc_number != cc_params->control)
            {
                continue;
            }
            switch(mapping.mode)
            {
            case Mapping::Mode::PARAMETER:
                parameters->update(mapping.parameter_name,
                                   cc_params->value / float(CC_VALUE_MAX));
                break;
            case Mapping::Mode::TOGGLE:
                if(cc_params->value == 0)
                {
                    continue;
                }
                auto old_value = parameters->get(mapping.parameter_name);
                parameters->update(mapping.parameter_name,
                                   old_value < 0.5f ? 1.f : 0.f);
                break;
            }
        }
    };
References shrapnel::midi::CC_VALUE_MAX, shrapnel::midi::Message::channel, shrapnel::midi::Mapping::PARAMETER, shrapnel::midi::Message::parameters, and shrapnel::midi::Mapping::TOGGLE.
read()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> int shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::read (Mapping::id_t id, Mapping & mapping) inline override
Definition at line 116 of file midi_mapping.h.
    {
        std::array<uint8_t, 256> memory{};
        std::span<uint8_t> buffer{memory};
        int rc = storage->read(id, buffer);
        if(rc != 0)
        {
            return -1;
        }
        auto decoded = api::from_bytes<Mapping>(buffer);
        if(!decoded.has_value())
        {
            return -1;
        }
        mappings.insert({id, *decoded});
        mapping = *decoded;
        this->notify_observers(id);
        return 0;
    }
update()
template<typename AudioParametersT , std::size_t MAX_MAPPINGS, std::size_t MAX_OBSERVERS> int shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::update (Mapping::id_t id, const Mapping & mapping) inline override
Returns
non-zero on failure
Definition at line 140 of file midi_mapping.h.
    {
        if(!mappings.contains(id))
        {
            ESP_LOGE(TAG, "Does not contain key %" PRIu32, id);
            return -1;
        }
        std::array<uint8_t, 256> memory{};
        std::span<uint8_t> buffer{memory};
        auto encoded = api::to_bytes(mapping, buffer);
        if(!encoded.has_value())
        {
            return -1;
        }
        int rc = storage->update(id, *encoded);
        if(rc != 0)
        {
            return -1;
        }
        mappings.erase(id);
        mappings.insert({id, mapping});
        this->notify_observers(id);
        return 0;
    }
References shrapnel::api::to_bytes().
The documentation for this class was generated from the following file:
firmware/components/midi_mapping/include/midi_mapping.h