ShrapnelDSP: shrapnel::ParameterObserver< MAX_PARAMETERS > Class Template Reference
shrapnel::ParameterObserver< MAX_PARAMETERS > Class Template Reference final
Public Member Functions
ParameterObserver (persistence::Storage &persistence)
void timer_callback ()
void notification (std::pair< const parameters::id_t &, float > parameter) override
void persist_parameters ()
Data Fields
std::atomic_flag is_save_throttled
Detailed Description
template<std::size_t MAX_PARAMETERS>
class shrapnel::ParameterObserver< MAX_PARAMETERS >
Definition at line 136 of file main.cpp.
Constructor & Destructor Documentation
ParameterObserver()
template<std::size_t MAX_PARAMETERS> shrapnel::ParameterObserver< MAX_PARAMETERS >::ParameterObserver (persistence::Storage & persistence) inline explicit
Definition at line 138 of file main.cpp.
        : persistence{persistence},
          timer{"param save throttle",
                pdMS_TO_TICKS(10'000),
                false,
                etl::delegate<void(void)>::create<
                    ParameterObserver<MAX_PARAMETERS>,
                    &ParameterObserver<MAX_PARAMETERS>::timer_callback>(*this)}
    {
    }
Member Function Documentation
notification()
template<std::size_t MAX_PARAMETERS> void shrapnel::ParameterObserver< MAX_PARAMETERS >::notification (std::pair< const parameters::id_t &, float > parameter) inline override
Definition at line 155 of file main.cpp.
    {
        auto &[id, value] = parameter;
        ESP_LOGI(
            TAG, "notified about parameter change %s %f", id.data(), value);
        if (!updated_parameters.available())
        {
            ESP_LOGE(TAG, "no space available");
            return;
        }
        updated_parameters[id] = value;
        if(!timer.is_active())
        {
            timer.start(pdMS_TO_TICKS(5));
        }
    }
References shrapnel::os::Timer::is_active(), shrapnel::os::Timer::start(), and shrapnel::parameters::TAG.
persist_parameters()
template<std::size_t MAX_PARAMETERS> void shrapnel::ParameterObserver< MAX_PARAMETERS >::persist_parameters () inline
Definition at line 174 of file main.cpp.
    {
        for(const auto &param : updated_parameters)
        {
            rapidjson::Document document;
            auto parameter_data = midi::to_json(document, param.second);
            document.Swap(parameter_data);
            rapidjson::StringBuffer buffer;
            rapidjson::Writer writer{buffer};
            document.Accept(writer);
            persistence.save(param.first.data(), buffer.GetString());
        }
        updated_parameters.clear();
    }
References shrapnel::persistence::Storage::save(), and shrapnel::midi::to_json().
timer_callback()
template<std::size_t MAX_PARAMETERS> void shrapnel::ParameterObserver< MAX_PARAMETERS >::timer_callback () inline
Definition at line 149 of file main.cpp.
    {
        is_save_throttled.clear();
        is_save_throttled.notify_all();
    }
References shrapnel::ParameterObserver< MAX_PARAMETERS >::is_save_throttled.
Field Documentation
is_save_throttled
template<std::size_t MAX_PARAMETERS> std::atomic_flag shrapnel::ParameterObserver< MAX_PARAMETERS >::is_save_throttled
Definition at line 193 of file main.cpp.
Referenced by shrapnel::ParameterObserver< MAX_PARAMETERS >::timer_callback().
The documentation for this class was generated from the following file:
firmware/main/main.cpp