ShrapnelDSP: shrapnel::os::Timer Class Reference
shrapnel::os::Timer Class Reference final
#include <timer.h>
Public Member Functions
Timer (const char *pcTimerName, TickType_t xTimerPeriod, const UBaseType_t uxAutoReload, etl::delegate< void(void)> callback)
~Timer ()
Timer (const Timer &)=delete
Timer & operator= (const Timer &)=delete
BaseType_t is_active () const
BaseType_t start (TickType_t xBlockTime)
BaseType_t stop (TickType_t xBlockTime)
BaseType_t change_period (TickType_t xNewPeriod, TickType_t xBlockTime)
BaseType_t reset (TickType_t xBlockTime)
BaseType_t start_from_isr (BaseType_t &pxHigherPriorityTaskWoken)
BaseType_t stop_from_isr (BaseType_t &pxHigherPriorityTaskWoken)
BaseType_t change_period_from_isr (TickType_t xNewPeriod, BaseType_t &pxHigherPriorityTaskWoken)
BaseType_t reset_from_isr (BaseType_t &pxHigherPriorityTaskWoken)
void set_reload_mode (UBaseType_t uxAutoReload)
const char * get_name () const
TickType_t get_period () const
TickType_t get_expiry_time () const
BaseType_t get_reload_mode () const
Friends
void shrapnel::os::timer_callback (TimerHandle_t)
Detailed Description
Definition at line 30 of file timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
shrapnel::os::Timer::Timer (const char * pcTimerName, TickType_t xTimerPeriod, const UBaseType_t uxAutoReload, etl::delegate< void(void)> callback)
Definition at line 32 of file timer.cpp.
    : callback{callback}
{
    timer = xTimerCreate(
        pcTimerName, xTimerPeriod, uxAutoReload, this, timer_callback);
}
References shrapnel::os::timer_callback().
~Timer()
shrapnel::os::Timer::~Timer ()
Definition at line 42 of file timer.cpp.
{
    auto rc = xTimerDelete(timer, portMAX_DELAY);
    assert(rc == pdPASS);
}
Timer() [2/2]
shrapnel::os::Timer::Timer (const Timer &) delete
Member Function Documentation
change_period()
BaseType_t shrapnel::os::Timer::change_period (TickType_t xNewPeriod, TickType_t xBlockTime)
Definition at line 60 of file timer.cpp.
{
    return xTimerChangePeriod(timer, xNewPeriod, xBlockTime);
}
change_period_from_isr()
BaseType_t shrapnel::os::Timer::change_period_from_isr (TickType_t xNewPeriod, BaseType_t & pxHigherPriorityTaskWoken)
Definition at line 80 of file timer.cpp.
{
    return xTimerChangePeriodFromISR(
        timer, xNewPeriod, &pxHigherPriorityTaskWoken);
}
get_expiry_time()
TickType_t shrapnel::os::Timer::get_expiry_time () const
Definition at line 101 of file timer.cpp.
{ return xTimerGetExpiryTime(timer); }
get_name()
const char * shrapnel::os::Timer::get_name () const
Definition at line 97 of file timer.cpp.
{ return pcTimerGetName(timer); }
get_period()
TickType_t shrapnel::os::Timer::get_period () const
Definition at line 99 of file timer.cpp.
{ return xTimerGetPeriod(timer); }
get_reload_mode()
BaseType_t shrapnel::os::Timer::get_reload_mode () const
Definition at line 103 of file timer.cpp.
{
    return static_cast<BaseType_t>(uxTimerGetReloadMode(timer));
}
is_active()
BaseType_t shrapnel::os::Timer::is_active () const
Definition at line 48 of file timer.cpp.
{ return xTimerIsTimerActive(timer); }
Referenced by shrapnel::ParameterObserver< MAX_PARAMETERS >::notification().
operator=()
Timer & shrapnel::os::Timer::operator= (const Timer &) delete
reset()
BaseType_t shrapnel::os::Timer::reset (TickType_t xBlockTime)
Definition at line 65 of file timer.cpp.
{
    return xTimerReset(timer, xBlockTime);
}
reset_from_isr()
BaseType_t shrapnel::os::Timer::reset_from_isr (BaseType_t & pxHigherPriorityTaskWoken)
Definition at line 87 of file timer.cpp.
{
    return xTimerResetFromISR(timer, &pxHigherPriorityTaskWoken);
}
set_reload_mode()
void shrapnel::os::Timer::set_reload_mode (UBaseType_t uxAutoReload)
Definition at line 92 of file timer.cpp.
{
    vTimerSetReloadMode(timer, uxAutoReload);
}
start()
BaseType_t shrapnel::os::Timer::start (TickType_t xBlockTime)
Definition at line 50 of file timer.cpp.
{
    return xTimerStart(timer, xBlockTime);
}
Referenced by shrapnel::app_main(), and shrapnel::ParameterObserver< MAX_PARAMETERS >::notification().
start_from_isr()
BaseType_t shrapnel::os::Timer::start_from_isr (BaseType_t & pxHigherPriorityTaskWoken)
Definition at line 70 of file timer.cpp.
{
    return xTimerStartFromISR(timer, &pxHigherPriorityTaskWoken);
}
stop()
BaseType_t shrapnel::os::Timer::stop (TickType_t xBlockTime)
Definition at line 55 of file timer.cpp.
{
    return xTimerStart(timer, xBlockTime);
}
stop_from_isr()
BaseType_t shrapnel::os::Timer::stop_from_isr (BaseType_t & pxHigherPriorityTaskWoken)
Definition at line 75 of file timer.cpp.
{
    return xTimerStopFromISR(timer, &pxHigherPriorityTaskWoken);
}
Friends And Related Function Documentation
shrapnel::os::timer_callback
void shrapnel::os::timer_callback (TimerHandle_t) friend
The documentation for this class was generated from the following files:
firmware/components/timer/include/timer.h
firmware/components/timer/src/timer.cpp