ShrapnelDSP: shrapnel::AudioProcessor Class Reference
shrapnel::AudioProcessor Class Reference
#include <audio_processor.h>
Public Member Functions
AudioProcessor (AudioProcessorParameters a_parameters)
void prepare (float sample_rate, size_t buffer_size)
void process (std::span< float, 512 > samples)
void reset ()
Detailed Description
Definition at line 73 of file audio_processor.h.
Constructor & Destructor Documentation
AudioProcessor()
shrapnel::AudioProcessor::AudioProcessor (AudioProcessorParameters a_parameters) explicit
Definition at line 35 of file audio_processor.cpp.
    : parameters{a_parameters},
      speaker{{std::make_unique<shrapnel::dsp::FastConvolution<1024, 512>>(fir_coeff)}}
{
    esp_err_t rc = gate_init();
    assert(rc == ESP_OK);
    ESP_LOGI(TAG, "Initialised FIR filter with length %zd", fir_coeff.size());
}
References fir_coeff.
Member Function Documentation
prepare()
void shrapnel::AudioProcessor::prepare (float sample_rate, size_t buffer_size)
Definition at line 45 of file audio_processor.cpp.
{
    gate_set_sample_rate(sample_rate);
    gate_set_buffer_size(buffer_size);
    chorus.prepare(sample_rate, buffer_size);
    wah.prepare(sample_rate, buffer_size);
    valvestate.prepare(sample_rate, buffer_size);
}
References buffer_size, gate_set_buffer_size(), gate_set_sample_rate(), and sample_rate.
process()
void shrapnel::AudioProcessor::process (std::span< float, 512 > samples)
Definition at line 55 of file audio_processor.cpp.
{
    gate_set_threshold(*parameters.gate.threshold, *parameters.gate.hysteresis);
    gate_set_attack(*parameters.gate.attack);
    gate_set_hold(*parameters.gate.hold);
    gate_set_release(*parameters.gate.release);
    profiling_mark_stage(0);
    gate_analyse(fbuf.data(), fbuf.size());
    profiling_mark_stage(1);
    valvestate.set_gain(*parameters.amplifier.gain,
                        *parameters.amplifier.channel);
    valvestate.set_fmv(*parameters.amplifier.bass,
                       *parameters.amplifier.middle,
                       *parameters.amplifier.treble);
    valvestate.set_contour(*parameters.amplifier.contour);
    valvestate.set_volume(decibel_to_ratio(*parameters.amplifier.volume));
    profiling_mark_stage(2);
    valvestate.process(fbuf);
    profiling_mark_stage(3);
    if(*parameters.gate.bypass < 0.5f)
    {
        gate_process(fbuf.data(), fbuf.size());
    }
    profiling_mark_stage(4);
    /* speaker IR */
    speaker.process(fbuf);
    profiling_mark_stage(17);
    chorus.set_modulation_rate_hz(*parameters.chorus.rate);
    chorus.set_modulation_depth(*parameters.chorus.depth);
    chorus.set_modulation_mix(*parameters.chorus.mix);
    profiling_mark_stage(18);
    if(*parameters.chorus.bypass < 0.5f)
    {
        chorus.process(fbuf);
    }
    profiling_mark_stage(19);
    wah.set_expression_position(*parameters.wah.position);
    wah.set_vocal(*parameters.wah.vocal);
    if(*parameters.wah.bypass < 0.5f)
    {
        wah.process(fbuf);
    }
}
References gate_analyse(), gate_process(), gate_set_attack(), gate_set_hold(), gate_set_release(), gate_set_threshold(), and profiling_mark_stage().
reset()
void shrapnel::AudioProcessor::reset ()
Definition at line 109 of file audio_processor.cpp.
{
    valvestate.reset();
    chorus.reset();
    wah.reset();
    speaker.reset();
}
The documentation for this class was generated from the following files:
firmware/components/audio/include/audio_processor.h
firmware/components/audio/src/audio_processor.cpp