ShrapnelDSP: shrapnel::effect::Chorus Class Reference
shrapnel::effect::Chorus Class Reference
#include <chorus.h>
Public Member Functions
Chorus ()
void set_modulation_rate_hz (float rate)
Set the rate of modulation.
void set_modulation_depth (float depth)
Set the depth of modulation.
void set_sample_rate (float rate)
void set_modulation_mix (float depth)
Set the mix ratio of modulation.
void process (float *samples, std::size_t sample_count)
Detailed Description
Definition at line 28 of file chorus.h.
Constructor & Destructor Documentation
Chorus()
shrapnel::effect::Chorus::Chorus ()
Definition at line 45 of file chorus.cpp.
               {
}
Member Function Documentation
process()
void shrapnel::effect::Chorus::process (float * samples, std::size_t sample_count)
Definition at line 63 of file chorus.cpp.
{
    for(std::size_t i = 0; i < sample_count; i++)
    {
        float lfo = 0.5f * triangle(phase);
        phase += modulation_rate / sample_rate * 2 * (float)M_PI;
        if(phase > 2 * (float)M_PI)
        {
            phase -= 2 * (float)M_PI;
        }
#if 1
        float delay = MAX_DELAY_MS / 1000 * sample_rate *
                (0.5f + (modulation_depth * lfo));
        dspal_delayline_set_delay(delayline, delay);
        dspal_delayline_push_sample(delayline, samples[i]);
        samples[i] = samples[i] +
            (modulation_mix * dspal_delayline_pop_sample(delayline));
#else
        samples[i] = lfo;
#endif
    }
}
References dspal_delayline_pop_sample(), dspal_delayline_push_sample(), and dspal_delayline_set_delay().
set_modulation_depth()
void shrapnel::effect::Chorus::set_modulation_depth (float depth)
Set the depth of modulation.
This parameter is normalised to the range [0, 1].
Definition at line 53 of file chorus.cpp.
{
    modulation_depth = depth;
}
set_modulation_mix()
void shrapnel::effect::Chorus::set_modulation_mix (float depth)
Set the mix ratio of modulation.
This parameter is normalised to the range [0, 1].
Definition at line 58 of file chorus.cpp.
{
    modulation_mix = mix;
}
set_modulation_rate_hz()
void shrapnel::effect::Chorus::set_modulation_rate_hz (float rate)
Set the rate of modulation.
This parameter is in units of Hz.
Definition at line 48 of file chorus.cpp.
{
    modulation_rate = rate;
}
set_sample_rate()
void shrapnel::effect::Chorus::set_sample_rate (float rate)
Definition at line 91 of file chorus.cpp.
{
    if(nullptr != delayline)
    {
        dspal_delayline_destroy(delayline);
        delayline = nullptr;
    }
    delayline = dspal_delayline_create(rate * MAX_DELAY_MS / 1000);
    sample_rate = rate;
}
References dspal_delayline_create(), and dspal_delayline_destroy().
The documentation for this class was generated from the following files:
effects/chorus/include/chorus.h
effects/chorus/src/chorus.cpp