ShrapnelDSP: shrapnel::effect::Wah Class Reference
shrapnel::effect::Wah Class Reference
#include <wah.h>
Public Member Functions
void set_expression_position (float position)
Set the expression pedal position.
void set_vocal (float vocal)
Set the vocal mod magnitude.
void prepare (float sample_rate, size_t)
void reset ()
void process (std::span< float > samples)
Detailed Description
Definition at line 28 of file wah.h.
Member Function Documentation
prepare()
void shrapnel::effect::Wah::prepare (float sample_rate, size_t)
Definition at line 36 of file wah.cpp.
{
    float p = 0.9;
    std::array<float, 6> coefficients{1 - p, 0, 0, 1, -p, 0};
    position_filter.set_coefficients(coefficients );
    vocal_filter.set_coefficients(coefficients );
    sample_rate = rate;
}
References shrapnel::dsp::IirFilter::set_coefficients().
process()
void shrapnel::effect::Wah::process (std::span< float > samples)
Definition at line 44 of file wah.cpp.
{
    float wah;
    position_filter.process(&position_parameter, &wah, 1);
    float vocal;
    vocal_filter.process(&vocal_parameter, &vocal, 1);
    constexpr auto base_gain = 14.f * std::pow(10.f, -1.f / 20.f);
    constexpr auto gain_factor_wah = -1.2f;
    constexpr auto gain_factor_vocal = -1.f;
    constexpr auto vocal_range = 2.f;
    auto gain =
        base_gain * expf(gain_factor_wah * wah + gain_factor_vocal * vocal);
    auto resonance_frequency_hz = 450.f * powf(2, 2.3f * wah);
    auto quality = powf(2, 2 * (1 - wah) + 1 - vocal_range * vocal);
    float coefficients[5];
    // XXX: Slight inefficiency here. This function converts from denormalised
    // to normalised, then set_coefficients does the same again
    dsps_biquad_gen_bpf0db_f32(
        coefficients, resonance_frequency_hz / sample_rate, quality);
    wah_filter.set_coefficients(
        std::array<float, 6>{
            coefficients[0] * gain,
            coefficients[1] * gain,
            coefficients[2] * gain,
            1,
            coefficients[3],
            coefficients[4]});
    wah_filter.process(samples.data(), samples.data(), samples.size());
}
References shrapnel::dsp::IirFilter::process(), and shrapnel::dsp::IirFilter::set_coefficients().
reset()
void shrapnel::effect::Wah::reset (void)
Definition at line 81 of file wah.cpp.
                {
    wah_filter.reset();
    position_filter.reset();
    vocal_filter.reset();
}
References shrapnel::dsp::IirFilter::reset().
set_expression_position()
void shrapnel::effect::Wah::set_expression_position (float position)
Set the expression pedal position.
This parameter is normalised to the range [0, 1]. 1 corresponds to the pedal being fully depressed.
Definition at line 29 of file wah.cpp.
{
    position_parameter = position;
}
set_vocal()
void shrapnel::effect::Wah::set_vocal (float vocal)
Set the vocal mod magnitude.
This parameter is normalised to the range [0, 1]. Larger values increase the resonance filter bandwidth.
Definition at line 34 of file wah.cpp.
{ vocal_parameter = vocal; }
The documentation for this class was generated from the following files:
effects/wah/include/wah.h
effects/wah/wah.cpp