ShrapnelDSP: shrapnel::effect::valvestate::Valvestate Class Reference
shrapnel::effect::valvestate::Valvestate Class Reference
#include <valvestate.h>
Public Member Functions
Valvestate ()
void set_gain (float gain, float channel)
void set_fmv (float bass, float middle, float treble)
void set_contour (float contour)
void set_volume (float volume)
void process (float *buffer, std::size_t buffer_size)
void prepare (float samplerate)
void reset (void)
Detailed Description
Definition at line 34 of file valvestate.h.
Constructor & Destructor Documentation
Valvestate()
shrapnel::effect::valvestate::Valvestate::Valvestate ()
Definition at line 27 of file valvestate.cpp.
: volume(0) {}
Member Function Documentation
prepare()
void shrapnel::effect::valvestate::Valvestate::prepare (float samplerate)
Definition at line 63 of file valvestate.cpp.
{
    input.prepare(samplerate);
    gaincontrol.prepare(samplerate);
    fmv.prepare(samplerate);
    contour.prepare(samplerate);
}
References ContourFilter::prepare(), shrapnel::effect::valvestate::FMVFilter::prepare(), shrapnel::effect::valvestate::GainControl::prepare(), and shrapnel::effect::valvestate::InputFilter::prepare().
process()
void shrapnel::effect::valvestate::Valvestate::process (float * buffer, std::size_t buffer_size)
Definition at line 49 of file valvestate.cpp.
{
    input.process(buffer, buffer_size);
    gaincontrol.process(buffer, buffer_size);
    clipping.process(buffer, buffer_size);
    fmv.process(buffer, buffer_size);
    contour.process(buffer, buffer_size);
    for(std::size_t i = 0; i < buffer_size; i++)
    {
        buffer[i] *= volume;
    }
}
References buffer_size, shrapnel::effect::valvestate::Clipping::process(), ContourFilter::process(), shrapnel::effect::valvestate::FMVFilter::process(), shrapnel::effect::valvestate::GainControl::process(), and shrapnel::effect::valvestate::InputFilter::process().
reset()
void shrapnel::effect::valvestate::Valvestate::reset (void)
Definition at line 71 of file valvestate.cpp.
{
    input.reset();
    gaincontrol.reset();
    fmv.reset();
    contour.reset();
}
References shrapnel::effect::valvestate::FMVFilter::reset(), shrapnel::effect::valvestate::InputFilter::reset(), ContourFilter::reset(), and shrapnel::effect::valvestate::GainControl::reset().
set_contour()
void shrapnel::effect::valvestate::Valvestate::set_contour (float contour)
Definition at line 39 of file valvestate.cpp.
{
    contour.set_parameter(a_contour);
}
References ContourFilter::set_parameter().
set_fmv()
void shrapnel::effect::valvestate::Valvestate::set_fmv (float bass, float middle, float treble)
Definition at line 34 of file valvestate.cpp.
{
    fmv.set_parameters(bass, middle, treble);
}
References shrapnel::effect::valvestate::FMVFilter::set_parameters().
set_gain()
void shrapnel::effect::valvestate::Valvestate::set_gain (float gain, float channel)
Definition at line 29 of file valvestate.cpp.
{
    gaincontrol.set_parameters(gain, channel);
}
References shrapnel::effect::valvestate::GainControl::set_parameters().
set_volume()
void shrapnel::effect::valvestate::Valvestate::set_volume (float volume)
Definition at line 44 of file valvestate.cpp.
{
    volume = a_volume;
}
The documentation for this class was generated from the following files:
effects/valvestate/include/valvestate.h
effects/valvestate/src/valvestate.cpp