ShrapnelDSP: shrapnel::dsp::FastConvolution< N, K > Class Template Reference
shrapnel::dsp::FastConvolution< N, K > Class Template Reference final
#include <fast_convolution.h>
Public Member Functions
FastConvolution (const std::array< float, K > &a)
void process (const std::array< float, N > &b, std::array< float, N > &out)
Process samples.
Static Public Member Functions
static void complex_multiply (const std::array< std::complex< float >, N > &a, const std::array< std::complex< float >, N > &b, std::array< std::complex< float >, N > &out)
Detailed Description
template<std::size_t N, std::size_t K>
class shrapnel::dsp::FastConvolution< N, K >
Definition at line 35 of file fast_convolution.h.
Constructor & Destructor Documentation
FastConvolution()
template<std::size_t N, std::size_t K> shrapnel::dsp::FastConvolution< N, K >::FastConvolution (const std::array< float, K > & a) inline
Definition at line 37 of file fast_convolution.h.
    {
        ESP_ERROR_CHECK(dsps_fft4r_init_fc32(NULL, CONFIG_DSP_MAX_FFT_SIZE));
        // transform a
        std::array<float, N> a_copy{};
        std::copy(a.cbegin(), a.cend(), a_copy.begin());
        a_complex = real_to_complex(a_copy);
        ESP_ERROR_CHECK(dsps_fft4r_fc32(reinterpret_cast<float *>(a_complex.data()), N));
        dsps_bit_rev4r_fc32(reinterpret_cast<float *>(a_complex.data()), N);
    }
Member Function Documentation
complex_multiply()
template<std::size_t N, std::size_t K> static void shrapnel::dsp::FastConvolution< N, K >::complex_multiply (const std::array< std::complex< float >, N > & a, const std::array< std::complex< float >, N > & b, std::array< std::complex< float >, N > & out) inline static
Definition at line 120 of file fast_convolution.h.
    {
        // We want to compute (r_a + im_a j) * (r_b + im_b j)
        // This can be rewritten as follows:
        //
        // ra rb + ra im_b j + im_a r_b j + im_a im_b j j
        //
        // j j  is -1 so:
        //
        // (ra rb + ra im_b j) +    // part 1
        // (- im_a im_b + im_a r_b j)   // part 2
        // TODO we multiply then add here, could we use the MADD.S instruction
        // to speed it up?
        auto a_ptr = reinterpret_cast<const float*>(a.data());
        auto b_ptr = reinterpret_cast<const float*>(b.data());
        auto out_ptr = reinterpret_cast<float*>(out.data());
        // part 1
        dsps_mul_f32(a_ptr, b_ptr, out_ptr, N, 2, 2, 2);
        dsps_mul_f32(a_ptr, b_ptr + 1, out_ptr + 1, N, 2, 2, 2);
        // part 2
        std::array<std::complex<float>, N> out2;
        auto out2_ptr = reinterpret_cast<float*>(out2.data());
        dsps_mul_f32(a_ptr + 1, b_ptr + 1, out2_ptr, N, 2, 2, 2);
        dsps_mul_f32(a_ptr + 1, b_ptr, out2_ptr + 1, N, 2, 2, 2);
        dsps_mulc_f32(out2_ptr, out2_ptr, N, -1, 2, 2);
        dsps_add_f32(out_ptr, out2_ptr, out_ptr, 2*out.size(), 1, 1, 1);
    }
Referenced by shrapnel::dsp::FastConvolution< N, K >::process().
process()
template<std::size_t N, std::size_t K> void shrapnel::dsp::FastConvolution< N, K >::process (const std::array< float, N > & b, std::array< float, N > & out) inline
Process samples.
\(out = a \circledast b \)
Definition at line 54 of file fast_convolution.h.
    {
        // transform b
        auto b_complex = real_to_complex(b);
        profiling_mark_stage(7);
        ESP_ERROR_CHECK(dsps_fft4r_fc32(reinterpret_cast<float *>(b_complex.data()), N));
        profiling_mark_stage(8);
        dsps_bit_rev4r_fc32(reinterpret_cast<float *>(b_complex.data()), N);
        profiling_mark_stage(9);
        // multiply A * B
        std::array<std::complex<float>, N> multiplied;
        complex_multiply(a_complex, b_complex, multiplied);
        profiling_mark_stage(10);
        // transform result
        // Inverse transform achieved by complex conjugating the input and
        // output of the forward transform. The imaginary part of the output is
        // not used, so we don't actually calculate the complex conjugate on
        // it.
        //
        // There is no inverse transform provided by esp-dsp.
        auto multiplied_ptr = reinterpret_cast<float *>(multiplied.data());
        dsps_mulc_f32(multiplied_ptr + 1, multiplied_ptr + 1, N, -1, 2, 2);
        profiling_mark_stage(11);
        ESP_ERROR_CHECK(dsps_fft4r_fc32(multiplied_ptr, N));
        profiling_mark_stage(12);
        dsps_bit_rev4r_fc32(multiplied_ptr, N);
        profiling_mark_stage(13);
        complex_to_real(multiplied, out);
        profiling_mark_stage(14);
        dsps_mulc_f32(out.data(), out.data(), N, scale_factor, 1, 1);
        profiling_mark_stage(15);
    }
References shrapnel::dsp::FastConvolution< N, K >::complex_multiply(), and profiling_mark_stage().
The documentation for this class was generated from the following file:
effects/abstract_dsp/include/fast_convolution.h