ShrapnelDSP: shrapnel::effect::valvestate::GainControl Class Reference
shrapnel::effect::valvestate::GainControl Class Reference
#include <gain_control.h>
Public Member Functions
void set_parameters (float g, float channel)
void prepare (float samplerate, size_t)
void process (std::span< float > buffer)
void reset ()
Detailed Description
Definition at line 28 of file gain_control.h.
Member Function Documentation
prepare()
void shrapnel::effect::valvestate::GainControl::prepare (float samplerate, size_t)
Definition at line 61 of file gain_control.cpp.
{
    filter.reset();
    samplerate = a_samplerate;
}
References shrapnel::dsp::IirFilter::reset().
Referenced by shrapnel::effect::valvestate::Valvestate::prepare().
process()
void shrapnel::effect::valvestate::GainControl::process (std::span< float > buffer)
Definition at line 67 of file gain_control.cpp.
{
    filter.process(buffer.data(), buffer.data(), buffer.size());
}
References shrapnel::dsp::IirFilter::process().
Referenced by shrapnel::effect::valvestate::Valvestate::process().
reset()
void shrapnel::effect::valvestate::GainControl::reset (void)
Definition at line 72 of file gain_control.cpp.
{ filter.reset(); }
References shrapnel::dsp::IirFilter::reset().
Referenced by shrapnel::effect::valvestate::Valvestate::reset().
set_parameters()
void shrapnel::effect::valvestate::GainControl::set_parameters (float g, float channel)
Parameters
g The value of gain from 0 to 1.
channel 0 for OD1, 1 for OD2
Definition at line 26 of file gain_control.cpp.
{
    float B0, B1, B2, A0, A1, A2;
    float K = 2 * samplerate;
    if(channel < 0.5f)
    {
        //OD1
        B0 = 0.00916582638188652f * K * g;
        B1 = 0;
        B2 = -0.00916582638188652f * K * g;
        A0 = 4.30793839948666e-8f * std::pow(K, 2.f) * g + 2.35e-5f * K * g +
             0.000916582638188652f * K + 0.5f;
        A1 = -8.61587679897332e-8f * std::pow(K, 2.f) * g + 1.0f;
        A2 = 4.30793839948666e-8f * std::pow(K, 2.f) * g - 2.35e-5f * K * g -
             0.000916582638188652f * K + 0.5f;
    }
    else
    {
        //OD2
        B0 = 0.11f * K * g;
        B1 = 0;
        B2 = -0.11f * K * g;
        A0 = 4.69953e-8f * std::pow(K, 2.f) * g + 2.35e-5f * K * g +
             0.0009999f * K + 0.5f;
        A1 = -9.39906e-8f * std::pow(K, 2.f) * g + 1.0f;
        A2 = 4.69953e-8f * std::pow(K, 2.f) * g - 2.35e-5f * K * g -
             0.0009999f * K + 0.5f;
    }
    filter.set_coefficients(std::array<float, 6>({B0, B1, B2, A0, A1, A2}));
}
References shrapnel::dsp::IirFilter::set_coefficients().
Referenced by shrapnel::effect::valvestate::Valvestate::set_gain().
The documentation for this class was generated from the following files:
effects/valvestate/include/gain_control.h
effects/valvestate/src/gain_control.cpp