ShrapnelDSP: shrapnel::effect::valvestate::InputFilter Class Reference
shrapnel::effect::valvestate::InputFilter Class Reference
#include <input_filter.h>
Public Member Functions
void prepare (float samplerate, size_t)
void process (std::span< float > buffer)
void reset ()
Detailed Description
Definition at line 28 of file input_filter.h.
Member Function Documentation
prepare()
void shrapnel::effect::valvestate::InputFilter::prepare (float samplerate, size_t)
Definition at line 28 of file input_filter.cpp.
{
    float K = 2 * samplerate;
    float B0 = 1.10449884469421e-9f * std::pow(K, 2.f) +
               0.00246545127613797f * K + 0.5f;
    float B1 = 1.0f - 2.20899768938842e-9f * std::pow(K, 2.f);
    float B2 = 1.10449884469421e-9f * std::pow(K, 2.f) -
               0.00246545127613797f * K + 0.5f;
    float A0 = 1.10449884469421e-9f * std::pow(K, 2.f) +
               0.000115449950739352f * K + 0.5f;
    float A1 = 1.0f - 2.20899768938842e-9f * std::pow(K, 2.f);
    float A2 = 1.10449884469421e-9f * std::pow(K, 2.f) -
               0.000115449950739352f * K + 0.5f;
    filter.set_coefficients(std::array<float, 6>({B0, B1, B2, A0, A1, A2}));
    filter.reset();
}
References shrapnel::dsp::IirFilter::reset(), and shrapnel::dsp::IirFilter::set_coefficients().
Referenced by shrapnel::effect::valvestate::Valvestate::prepare().
process()
void shrapnel::effect::valvestate::InputFilter::process (std::span< float > buffer)
Definition at line 48 of file input_filter.cpp.
{
    filter.process(buffer.data(), buffer.data(), buffer.size());
}
References shrapnel::dsp::IirFilter::process().
Referenced by shrapnel::effect::valvestate::Valvestate::process().
reset()
void shrapnel::effect::valvestate::InputFilter::reset (void)
Definition at line 53 of file input_filter.cpp.
{ filter.reset(); }
References shrapnel::dsp::IirFilter::reset().
Referenced by shrapnel::effect::valvestate::Valvestate::reset().
The documentation for this class was generated from the following files:
effects/valvestate/include/input_filter.h
effects/valvestate/src/input_filter.cpp