ShrapnelDSP: effects/abstract_dsp/universal/delayline_c.cpp File Reference
delayline_c.cpp File Reference
Data Structures
struct dspal_delayline
Functions
dspal_delayline_t dspal_delayline_create (size_t max_samples)
void dspal_delayline_destroy (dspal_delayline_t delayline)
void dspal_delayline_set_delay (dspal_delayline_t delayline, float delay)
void dspal_delayline_push_sample (dspal_delayline_t delayline, float sample)
float dspal_delayline_pop_sample (dspal_delayline_t delayline)
Function Documentation
dspal_delayline_create()
dspal_delayline_t dspal_delayline_create (size_t max_samples)
Definition at line 28 of file delayline_c.cpp.
{
    dspal_delayline_t delayline = new dspal_delayline;
    delayline->delayline.reset(new shrapnel::dsp::DelayLine(max_samples));
    return delayline;
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::prepare().
dspal_delayline_destroy()
void dspal_delayline_destroy (dspal_delayline_t delayline)
Definition at line 37 of file delayline_c.cpp.
{
    delete delayline;
}
Referenced by shrapnel::effect::Chorus::reset().
dspal_delayline_pop_sample()
float dspal_delayline_pop_sample (dspal_delayline_t delayline)
Definition at line 52 of file delayline_c.cpp.
{
    return delayline->delayline->pop_sample();
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().
dspal_delayline_push_sample()
void dspal_delayline_push_sample (dspal_delayline_t delayline, float sample)
Definition at line 47 of file delayline_c.cpp.
{
    delayline->delayline->push_sample(sample);
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().
dspal_delayline_set_delay()
void dspal_delayline_set_delay (dspal_delayline_t delayline, float delay)
Definition at line 42 of file delayline_c.cpp.
{
    delayline->delayline->set_delay(delay);
}
References dspal_delayline::delayline.
Referenced by shrapnel::effect::Chorus::process().