ShrapnelDSP: firmware/components/i2s/include/i2s.h File Reference
i2s.h File Reference
Functions
esp_err_t i2s_setup (gpio_num_t profiling_gpio, shrapnel::parameters::AudioParametersBase *audio_params)
void log_i2s_event (const i2s_event_t &event)
Variables
QueueHandle_t i2s_queue
Function Documentation
i2s_setup()
esp_err_t i2s_setup (gpio_num_t profiling_gpio, shrapnel::parameters::AudioParametersBase * audio_params)
Parameters
profiling_gpio This pin will go high when samples are being processed and return to low once the processing is finished.
Definition at line 200 of file i2s.cpp.
{
    esp_err_t err;
    g_profiling_gpio = profiling_gpio;
    gpio_config_t io_conf = {
        .pin_bit_mask = 1ULL << profiling_gpio,
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE,
    };
    err = gpio_config(&io_conf);
    if(err != ESP_OK)
    {
        ESP_LOGE(TAG, "gpio_config failed %d, %s", err, esp_err_to_name(err));
        return err;
    }
    err = gpio_set_level(profiling_gpio, 0);
    if(err != ESP_OK)
    {
        ESP_LOGE(TAG, "gpio_set_level failed %d, %s", err, esp_err_to_name(err));
        return err;
    }
    // This task must be pinned as CPU cycle count is used for profiling
    int ret = xTaskCreatePinnedToCore(i2s_processing_task, "i2s proc", TASK_STACK, audio_param, TASK_PRIO, NULL, 1);
    if(ret != pdPASS)
    {
        ESP_LOGE(TAG, "Processing task create failed %d", ret);
    }
    return ESP_OK;
}
References g_profiling_gpio, i2s_processing_task(), and shrapnel::parameters::TAG.
Referenced by shrapnel::app_main().
log_i2s_event()
void log_i2s_event (const i2s_event_t & event)
Definition at line 53 of file i2s.cpp.
{
    switch(e.type)
    {
    case I2S_EVENT_DMA_ERROR:
        ESP_LOGE(TAG, "Something went wrong with DMA");
        break;
    case I2S_EVENT_TX_DONE:
    case I2S_EVENT_RX_DONE:
        //do nothing
        break;
    case I2S_EVENT_TX_Q_OVF:
        ESP_LOGE(TAG, "TX queue overflowed");
        break;
    case I2S_EVENT_RX_Q_OVF:
        ESP_LOGE(TAG, "RX queue overflowed");
        break;
    default:
        ESP_LOGE(TAG, "Unhandled type: %d", e.type);
        break;
    }
}
References shrapnel::parameters::TAG.
Referenced by shrapnel::app_main().
Variable Documentation
i2s_queue
QueueHandle_t i2s_queue extern
Definition at line 45 of file i2s.cpp.
Referenced by shrapnel::app_main(), and i2s_processing_task().