ShrapnelDSP: firmware/main/main.cpp File Reference
main.cpp File Reference
Data Structures
class shrapnel::ParameterUpdateNotifier
class shrapnel::EventSend
class shrapnel::ParameterObserver< MAX_PARAMETERS >
class shrapnel::MidiMappingObserver< MappingManagerT >
Namespaces
namespace shrapnel
namespace shrapnel::midi
Typedefs
using ApiMessage = std::variant< shrapnel::parameters::ApiMessage, shrapnel::midi::MappingApiMessage, shrapnel::events::ApiMessage >
using FileDescriptor = std::optional< int >
using AppMessage = std::pair< ApiMessage, FileDescriptor >
using shrapnel::AudioParameters = parameters::AudioParameters< MAX_PARAMETERS, 1 >
Functions
void audio_event_send_callback (const AppMessage &message)
template<>
std::optional< float > shrapnel::midi::from_json (const rapidjson::Value &value)
Convert the message into a object representing it.
template<>
rapidjson::Value shrapnel::midi::to_json (rapidjson::Document &document, const float &object)
static void shrapnel::websocket_send (void *arg)
static esp_err_t shrapnel::websocket_get_handler (httpd_req_t *req)
static esp_err_t shrapnel::ui_get_handler (httpd_req_t *req)
static httpd_handle_t shrapnel::start_webserver (void)
static void shrapnel::stop_webserver (httpd_handle_t server)
static void shrapnel::disconnect_handler (void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
static void shrapnel::connect_handler (void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
static void shrapnel::start_mdns (void)
static void shrapnel::i2c_setup (void)
static void shrapnel::do_nothing (TimerHandle_t)
static void shrapnel::wifi_start_handler (void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
static void shrapnel::failed_alloc_callback (size_t size, uint32_t caps, const char *function_name)
void shrapnel::nvs_debug_print ()
void shrapnel::app_main (void)
Variables
constexpr const size_t shrapnel::MAX_PARAMETERS = 17
static Queue< AppMessage, QUEUE_LEN > * shrapnel::in_queue
static std::shared_ptr< AudioParameters > shrapnel::audio_params
static parameters::CommandHandling< AudioParameters, EventSend > * shrapnel::cmd_handling
static midi::MappingManager< ParameterUpdateNotifier, 10, 1 > * shrapnel::midi_mapping_manager
static EventSend shrapnel::event_send {}
static Queue< AppMessage, QUEUE_LEN > * shrapnel::out_queue
static SemaphoreHandle_t shrapnel::work_semaphore
static std::mutex shrapnel::midi_mutex
static httpd_handle_t shrapnel::_server = nullptr
static const httpd_uri_t shrapnel::websocket
static const httpd_uri_t shrapnel::ui
Typedef Documentation
ApiMessage
using ApiMessage = std::variant<shrapnel::parameters::ApiMessage, shrapnel::midi::MappingApiMessage, shrapnel::events::ApiMessage>
Definition at line 75 of file main.cpp.
AppMessage
using AppMessage = std::pair<ApiMessage, FileDescriptor>
Definition at line 77 of file main.cpp.
FileDescriptor
using FileDescriptor = std::optional<int>
Definition at line 76 of file main.cpp.
Function Documentation
audio_event_send_callback()
void audio_event_send_callback (const AppMessage & message)
Definition at line 960 of file main.cpp.
{
    ESP_LOGD(TAG, "%s %s", __FUNCTION__, pcTaskGetName(NULL));
    if(errQUEUE_FULL ==
            shrapnel::out_queue->send(&message, pdMS_TO_TICKS(100)))
    {
        ESP_LOGE(TAG, "Failed to send message to websocket");
        return;
    }
    if(!xSemaphoreTake(shrapnel::work_semaphore, 1000 / portTICK_PERIOD_MS))
    {
        ESP_LOGE(TAG, "work semaphore timed out");
        return;
    }
    esp_err_t rc = httpd_queue_work(
            shrapnel::_server,
            shrapnel::websocket_send,
            shrapnel::_server);
    if(ESP_OK != rc)
    {
        ESP_LOGE(TAG, "failed to queue work for server");
    }
}
References shrapnel::_server, shrapnel::out_queue, shrapnel::parameters::TAG, shrapnel::websocket_send(), and shrapnel::work_semaphore.
Referenced by shrapnel::app_main(), shrapnel::EventSend::send(), and shrapnel::ParameterUpdateNotifier::update().