ShrapnelDSP: shrapnel::uuid Namespace Reference
shrapnel::uuid Namespace Reference
Typedefs
using uuid_t = std::array< uint8_t, 16 >
Functions
template<typename T >
std::optional< T > from_json (const rapidjson::Value &json)
template<>
std::optional< uuid_t > from_json (const rapidjson::Value &json)
template<typename T >
rapidjson::Value to_json (rapidjson::Document &document, const T &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const uuid_t &object)
static int parse_uuid (uuid_t &uuid, const char *string)
template<>
std::optional< uuid_t > from_json (const rapidjson::Value &json)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const uuid_t &object)
Typedef Documentation
uuid_t
using shrapnel::uuid::uuid_t = typedef std::array<uint8_t, 16>
Definition at line 37 of file uuid.h.
Function Documentation
from_json() [1/3]
template<typename T > std::optional< T > shrapnel::uuid::from_json (const rapidjson::Value & json)
from_json() [2/3]
template<> std::optional< uuid_t > shrapnel::uuid::from_json (const rapidjson::Value & json)
Definition at line 31 of file uuid_json.cpp.
{
    constexpr const char *TAG = "Mapping::id_t from_json";
    if(!json.IsString())
    {
        ESP_LOGE(TAG, "id is not string");
        return std::nullopt;
    }
    uuid_t out;
    int rc = parse_uuid(out, json.GetString());
    if(rc != 0)
    {
        ESP_LOGE(TAG, "failed to get uuid");
        return std::nullopt;
    }
    return out;
}
References parse_uuid().
from_json() [3/3]
template<> std::optional< uuid_t > shrapnel::uuid::from_json (const rapidjson::Value & json)
Definition at line 31 of file uuid_json.cpp.
{
    constexpr const char *TAG = "Mapping::id_t from_json";
    if(!json.IsString())
    {
        ESP_LOGE(TAG, "id is not string");
        return std::nullopt;
    }
    uuid_t out;
    int rc = parse_uuid(out, json.GetString());
    if(rc != 0)
    {
        ESP_LOGE(TAG, "failed to get uuid");
        return std::nullopt;
    }
    return out;
}
References parse_uuid().
parse_uuid()
static int shrapnel::uuid::parse_uuid (uuid_t & uuid, const char * string) static
Definition at line 52 of file uuid_json.cpp.
{
    constexpr std::size_t UUID_LENGTH = 36;
    constexpr char TAG[] = "parse_uuid";
    if(UUID_LENGTH != std::strlen(string))
    {
        ESP_LOGE(TAG, "Incorrect UUID string length");
        return -1;
    }
    size_t i = 0;
    size_t j = 0;
    ESP_LOGD(TAG, "i = %zu, j = %zu", i, j);
    while(i < UUID_LENGTH)
    {
        char digit[2];
        std::memcpy(digit, &string[i], 2);
        ESP_LOGD(TAG, "digit = %c%c", digit[0], digit[1]);
        // TODO error on invalid characters: z, symbols etc
        //      The only valid characters are 0 to 9 and a to f.
        //
        //      Handle uppercase as well. It is required when a string UUID
        //      is an input as per RFC 4122 Section 3
        //      https://tools.ietf.org/html/rfc4122#section-3
        auto get_value = [&](char hex) -> uint8_t
        {
            if(hex >= 'a')
            {
                return hex - 'a' + 10;
            }
            else
            {
                return hex - '0';
            }
        };
        uuid[j] = get_value(digit[0]) << 4 | get_value(digit[1]);
        j++;
        i += 2;
        bool is_separator = (i == 8) || (i == 13) || (i == 18) || (i == 23);
        if(is_separator)
            i++;
        ESP_LOGD(TAG, "i = %zu, j = %zu", i, j);
    }
    return 0;
}
Referenced by from_json().
to_json() [1/3]
template<typename T > rapidjson::Value shrapnel::uuid::to_json (rapidjson::Document & document, const T & object)
Referenced by shrapnel::midi::to_json().
to_json() [2/3]
template<> rapidjson::Value shrapnel::uuid::to_json (rapidjson::Document & document, const uuid_t & object)
Definition at line 106 of file uuid_json.cpp.
{
    char uuid[37];
    sprintf(uuid,
            "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-"
            "%02x%02x%02x%02x%02x%02x",
            object[0],
            object[1],
            object[2],
            object[3],
            object[4],
            object[5],
            object[6],
            object[7],
            object[8],
            object[9],
            object[10],
            object[11],
            object[12],
            object[13],
            object[14],
            object[15]);
    rapidjson::Value out;
    out.SetString(uuid, 36, document.GetAllocator());
    return out;
}
to_json() [3/3]
template<> rapidjson::Value shrapnel::uuid::to_json (rapidjson::Document & document, const uuid_t & object)
Definition at line 106 of file uuid_json.cpp.
{
    char uuid[37];
    sprintf(uuid,
            "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-"
            "%02x%02x%02x%02x%02x%02x",
            object[0],
            object[1],
            object[2],
            object[3],
            object[4],
            object[5],
            object[6],
            object[7],
            object[8],
            object[9],
            object[10],
            object[11],
            object[12],
            object[13],
            object[14],
            object[15]);
    rapidjson::Value out;
    out.SetString(uuid, 36, document.GetAllocator());
    return out;
}