ShrapnelDSP: shrapnel::api Namespace Reference
shrapnel::api Namespace Reference
Functions
template<typename T >
std::optional< std::span< uint8_t > > to_bytes (const T &message, std::span< uint8_t > buffer)
Convert a message to bytes to be sent over the network to the frontend.
template<typename T >
std::optional< T > from_bytes (std::span< const uint8_t > buffer)
Parse a message from bytes received from the frontend.
template<typename ProtoT , typename T >
int to_proto (const T &message, ProtoT &out)
Convert a message to proto struct.
template<typename T , typename ProtoT >
int from_proto (const ProtoT &message, T &out)
Convert a message from proto struct.
template<>
int to_proto (const events::ApiMessage &message, shrapnel_audio_events_Message &out)
template<>
int from_proto (const shrapnel_audio_events_Message &message, events::ApiMessage &out)
template<>
int to_proto (const events::InputClipped &, shrapnel_audio_events_InputClipped &)
template<>
int from_proto (const shrapnel_audio_events_InputClipped &, events::InputClipped &)
template<>
int to_proto (const events::OutputClipped &, shrapnel_audio_events_OutputClipped &)
template<>
int from_proto (const shrapnel_audio_events_OutputClipped &, events::OutputClipped &)
template<>
int to_proto (const events::ApiMessage &message, shrapnel_audio_events_Message &out)
template<>
int from_proto (const shrapnel_audio_events_Message &message, events::ApiMessage &out)
template<>
int to_proto (const parameters::ApiMessage &message, shrapnel_cmd_handling_Message &out)
template<>
int from_proto (const shrapnel_cmd_handling_Message &message, parameters::ApiMessage &out)
template<>
int to_proto (const parameters::Update &message, shrapnel_cmd_handling_Update &out)
template<>
int to_proto (const parameters::Initialise &, shrapnel_cmd_handling_Initialise &)
template<>
int to_proto (const parameters::ApiMessage &message, shrapnel_cmd_handling_Message &out)
template<>
int from_proto (const shrapnel_cmd_handling_Update &message, parameters::Update &out)
template<>
int from_proto (const shrapnel_cmd_handling_Initialise &, parameters::Initialise &)
template<>
int from_proto (const shrapnel_cmd_handling_Message &message, parameters::ApiMessage &out)
template<>
std::optional< std::span< uint8_t > > to_bytes (const ApiMessage &message, std::span< uint8_t > buffer)
template<>
std::optional< ApiMessage > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< std::span< uint8_t > > to_bytes (const shrapnel_messages_Message &message, std::span< uint8_t > buffer)
template<>
std::optional< shrapnel_messages_Message > from_bytes (std::span< const uint8_t > buffer)
template<>
int to_proto (const ApiMessage &message, shrapnel_messages_Message &out)
template<>
int from_proto (const shrapnel_messages_Message &message, ApiMessage &out)
template<>
std::optional< std::span< uint8_t > > to_bytes (const ApiMessage &message, std::span< uint8_t > buffer)
template<>
std::optional< ApiMessage > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< std::span< uint8_t > > to_bytes (const midi::Mapping &message, std::span< uint8_t > buffer)
template<>
std::optional< midi::Mapping > from_bytes (std::span< const uint8_t > buffer)
template<>
int to_proto (const midi::MappingApiMessage &message, shrapnel_midi_mapping_Message &out)
template<>
int from_proto (const shrapnel_midi_mapping_Message &message, midi::MappingApiMessage &out)
template<>
std::optional< midi::Message > from_bytes (std::span< const uint8_t > buffer)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage &message, midi::Message &out)
template<>
std::optional< std::span< uint8_t > > to_bytes (const shrapnel_midi_mapping_Mapping &message, std::span< uint8_t > buffer)
template<>
std::optional< shrapnel_midi_mapping_Mapping > from_bytes (std::span< const uint8_t > buffer)
template<>
int to_proto (const midi::Mapping &message, shrapnel_midi_mapping_Mapping &out)
template<>
int from_proto (const shrapnel_midi_mapping_Mapping &message, midi::Mapping &out)
template<>
int to_proto (const std::pair< midi::Mapping::id_t, midi::Mapping > &message, shrapnel_midi_mapping_MappingRecord &out)
template<>
int from_proto (const shrapnel_midi_mapping_MappingRecord &message, std::pair< midi::Mapping::id_t, midi::Mapping > &out)
template<>
int to_proto (const midi::GetRequest &, shrapnel_midi_mapping_GetRequest &)
template<>
int from_proto (const shrapnel_midi_mapping_GetRequest &, midi::GetRequest &)
template<>
int to_proto (const midi::CreateRequest &message, shrapnel_midi_mapping_CreateRequest &out)
template<>
int from_proto (const shrapnel_midi_mapping_CreateRequest &message, midi::CreateRequest &out)
template<>
int to_proto (const midi::CreateResponse &message, shrapnel_midi_mapping_CreateResponse &out)
template<>
int from_proto (const shrapnel_midi_mapping_CreateResponse &message, midi::CreateResponse &out)
template<>
int to_proto (const midi::Update &message, shrapnel_midi_mapping_Update &out)
template<>
int from_proto (const shrapnel_midi_mapping_Update &message, midi::Update &out)
template<>
int to_proto (const midi::Remove &message, shrapnel_midi_mapping_Remove &out)
template<>
int from_proto (const shrapnel_midi_mapping_Remove &message, midi::Remove &out)
template<>
int to_proto (const midi::Message::NoteOn &message, shrapnel_midi_mapping_MidiMessage_NoteOn &out)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage_NoteOn &message, midi::Message::NoteOn &out)
template<>
int to_proto (const midi::Message::NoteOff &message, shrapnel_midi_mapping_MidiMessage_NoteOff &out)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage_NoteOff &message, midi::Message::NoteOff &out)
template<>
int to_proto (const midi::Message::ControlChange &message, shrapnel_midi_mapping_MidiMessage_ControlChange &out)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage_ControlChange &message, midi::Message::ControlChange &out)
template<>
int to_proto (const midi::Message::ProgramChange &message, shrapnel_midi_mapping_MidiMessage_ProgramChange &out)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage_ProgramChange &message, midi::Message::ProgramChange &out)
template<>
int to_proto (const midi::Message &message, shrapnel_midi_mapping_MidiMessage &out)
template<>
int from_proto (const shrapnel_midi_mapping_MidiMessage &message, midi::Message &out)
template<>
int to_proto (const midi::MessageReceived &message, shrapnel_midi_mapping_MessageReceived &out)
template<>
int from_proto (const shrapnel_midi_mapping_MessageReceived &message, midi::MessageReceived &out)
template<>
int to_proto (const midi::MappingApiMessage &message, shrapnel_midi_mapping_Message &out)
template<>
int from_proto (const shrapnel_midi_mapping_Message &message, midi::MappingApiMessage &out)
template<>
std::optional< std::span< uint8_t > > to_bytes (const midi::Mapping &message, std::span< uint8_t > buffer)
template<>
std::optional< midi::Mapping > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< shrapnel_midi_mapping_MidiMessage > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< midi::Message > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< std::span< uint8_t > > to_bytes (const presets::PresetData &message, std::span< uint8_t > buffer)
template<>
std::optional< presets::PresetData > from_bytes (std::span< const uint8_t > buffer)
template<>
int to_proto (const presets::PresetsApiMessage &message, shrapnel_presets_Message &out)
template<>
int from_proto (const shrapnel_presets_Message &message, presets::PresetsApiMessage &out)
template<>
int to_proto (const selected_preset::SelectedPresetApiMessage &message, shrapnel_selected_preset_Message &out)
template<>
int from_proto (const shrapnel_selected_preset_Message &message, selected_preset::SelectedPresetApiMessage &out)
template<>
int to_proto (const presets::ParametersData &message, shrapnel_presets_PresetParameters &out)
template<>
int from_proto (const shrapnel_presets_PresetParameters &message, presets::ParametersData &out)
template<>
int to_proto (const presets::PresetData &preset, shrapnel_presets_Preset &out)
template<>
int from_proto (const shrapnel_presets_Preset &unpacked, presets::PresetData &out)
template<>
int to_proto (const presets::Initialise &, shrapnel_presets_Initialise &)
template<>
int from_proto (const shrapnel_presets_Initialise &, presets::Initialise &)
template<>
int to_proto (const presets::Notify &message, shrapnel_presets_Notify &out)
template<>
int from_proto (const shrapnel_presets_Notify &message, presets::Notify &out)
template<>
int to_proto (const presets::Create &message, shrapnel_presets_Create &out)
template<>
int from_proto (const shrapnel_presets_Create &message, presets::Create &out)
template<>
int to_proto (const presets::Update &message, shrapnel_presets_Update &out)
template<>
int from_proto (const shrapnel_presets_Update &message, presets::Update &out)
template<>
int to_proto (const presets::Delete &message, shrapnel_presets_Remove &out)
template<>
int from_proto (const shrapnel_presets_Remove &message, presets::Delete &out)
template<>
int to_proto (const presets::PresetsApiMessage &message, shrapnel_presets_Message &out)
template<>
int from_proto (const shrapnel_presets_Message &message, presets::PresetsApiMessage &out)
template<>
std::optional< std::span< uint8_t > > to_bytes (const shrapnel_presets_Preset &proto, std::span< uint8_t > buffer)
template<>
std::optional< shrapnel_presets_Preset > from_bytes (std::span< const uint8_t > buffer)
template<>
std::optional< std::span< uint8_t > > to_bytes (const presets::PresetData &message, std::span< uint8_t > buffer)
template<>
std::optional< presets::PresetData > from_bytes (std::span< const uint8_t > buffer)
template<>
int to_proto (const selected_preset::Read &, shrapnel_selected_preset_Read &)
template<>
int to_proto (const selected_preset::Notify &message, shrapnel_selected_preset_Notify &out)
template<>
int to_proto (const selected_preset ::Write &message, shrapnel_selected_preset_Write &out)
template<>
int to_proto (const selected_preset::SelectedPresetApiMessage &message, shrapnel_selected_preset_Message &out)
template<>
int from_proto (const shrapnel_selected_preset_Read &, selected_preset::Read &)
template<>
int from_proto (const shrapnel_selected_preset_Notify &message, selected_preset::Notify &out)
template<>
int from_proto (const shrapnel_selected_preset_Write &message, selected_preset::Write &out)
template<>
int from_proto (const shrapnel_selected_preset_Message &message, selected_preset::SelectedPresetApiMessage &out)
Function Documentation
from_bytes() [1/13]
template<typename T > std::optional< T > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Parse a message from bytes received from the frontend.
from_bytes() [2/13]
template<> std::optional< ApiMessage > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 47 of file messages.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_messages_Message unpacked = shrapnel_messages_Message_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_messages_Message_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
from_bytes() [3/13]
template<> std::optional< shrapnel_messages_Message > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 47 of file messages.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_messages_Message unpacked = shrapnel_messages_Message_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_messages_Message_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
from_bytes() [4/13]
template<> std::optional< ApiMessage > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 171 of file messages.cpp.
{
    auto proto_message = from_bytes<shrapnel_messages_Message>(buffer);
    ApiMessage out{};
    int rc = from_proto<ApiMessage>(*proto_message, out);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return out;
}
from_bytes() [5/13]
template<> std::optional< midi::Mapping > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 47 of file messages.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_messages_Message unpacked = shrapnel_messages_Message_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_messages_Message_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
from_bytes() [6/13]
template<> std::optional< midi::Message > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 47 of file messages.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_messages_Message unpacked = shrapnel_messages_Message_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_messages_Message_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
from_bytes() [7/13]
template<> std::optional< shrapnel_midi_mapping_Mapping > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 135 of file midi_mapping_api.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_midi_mapping_Mapping message =
        shrapnel_midi_mapping_Mapping_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_midi_mapping_Mapping_msg, &message);
    if(!success)
    {
        return std::nullopt;
    }
    return message;
}
from_bytes() [8/13]
template<> std::optional< midi::Mapping > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 643 of file midi_mapping_api.cpp.
{
    auto proto = from_bytes<shrapnel_midi_mapping_Mapping>(buffer);
    if(!proto.has_value())
    {
        return std::nullopt;
    }
    midi::Mapping out{};
    int rc = from_proto(*proto, out);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return out;
}
References from_proto().
from_bytes() [9/13]
template<> std::optional< shrapnel_midi_mapping_MidiMessage > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 662 of file midi_mapping_api.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_midi_mapping_MidiMessage message =
        shrapnel_midi_mapping_MidiMessage_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_midi_mapping_MidiMessage_msg, &message);
    if(!success)
    {
        return std::nullopt;
    }
    return message;
}
from_bytes() [10/13]
template<> std::optional< midi::Message > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 678 of file midi_mapping_api.cpp.
{
    auto proto = from_bytes<shrapnel_midi_mapping_MidiMessage>(buffer);
    if(!proto.has_value())
    {
        return std::nullopt;
    }
    midi::Message out{};
    int rc = from_proto(*proto, out);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return out;
}
References from_proto().
from_bytes() [11/13]
template<> std::optional< presets::PresetData > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 47 of file messages.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_messages_Message unpacked = shrapnel_messages_Message_init_zero;
    bool success =
        pb_decode(&stream, &shrapnel_messages_Message_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
References from_proto().
from_bytes() [12/13]
template<> std::optional< shrapnel_presets_Preset > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 308 of file presets_api.cpp.
{
    auto stream = pb_istream_from_buffer(buffer.data(), buffer.size());
    shrapnel_presets_Preset unpacked = shrapnel_presets_Preset_init_zero;
    bool success = pb_decode(&stream, &shrapnel_presets_Preset_msg, &unpacked);
    if(!success)
    {
        return std::nullopt;
    }
    return unpacked;
}
from_bytes() [13/13]
template<> std::optional< presets::PresetData > shrapnel::api::from_bytes (std::span< const uint8_t > buffer)
Definition at line 336 of file presets_api.cpp.
{
    auto proto = from_bytes<shrapnel_presets_Preset>(buffer);
    if(!proto.has_value())
    {
        return std::nullopt;
    }
    presets::PresetData out{};
    int rc = from_proto<presets::PresetData>(*proto, out);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return out;
}
from_proto() [1/40]
template<typename T , typename ProtoT > int shrapnel::api::from_proto (const ProtoT & message, T & out)
Convert a message from proto struct.
Referenced by from_bytes().
from_proto() [2/40]
template<> int shrapnel::api::from_proto (const shrapnel_audio_events_InputClipped & , events::InputClipped &)
Definition at line 79 of file audio_events.cpp.
{
    return 0;
}
from_proto() [3/40]
template<> int shrapnel::api::from_proto (const shrapnel_audio_events_Message & message, events::ApiMessage & out)
Definition at line 140 of file audio_events.cpp.
{
    switch(message.which_event)
    {
    case shrapnel_audio_events_Message_input_clipped_tag:
    {
        events::InputClipped tmp{};
        int rc =
            from_proto<events::InputClipped>(message.event.input_clipped, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_audio_events_Message_output_clipped_tag:
    {
        events::OutputClipped tmp{};
        int rc = from_proto<events::OutputClipped>(message.event.output_clipped,
                                                   tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [4/40]
template<> int shrapnel::api::from_proto (const shrapnel_audio_events_Message & message, events::ApiMessage & out)
Definition at line 140 of file audio_events.cpp.
{
    switch(message.which_event)
    {
    case shrapnel_audio_events_Message_input_clipped_tag:
    {
        events::InputClipped tmp{};
        int rc =
            from_proto<events::InputClipped>(message.event.input_clipped, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_audio_events_Message_output_clipped_tag:
    {
        events::OutputClipped tmp{};
        int rc = from_proto<events::OutputClipped>(message.event.output_clipped,
                                                   tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [5/40]
template<> int shrapnel::api::from_proto (const shrapnel_audio_events_OutputClipped & , events::OutputClipped &)
Definition at line 93 of file audio_events.cpp.
{
    return 0;
}
from_proto() [6/40]
template<> int shrapnel::api::from_proto (const shrapnel_cmd_handling_Initialise & , parameters::Initialise &)
Definition at line 116 of file cmd_handling_api.cpp.
{
    return 0;
}
from_proto() [7/40]
template<> int shrapnel::api::from_proto (const shrapnel_cmd_handling_Message & message, parameters::ApiMessage & out)
Definition at line 123 of file cmd_handling_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_cmd_handling_Message_update_tag:
    {
        parameters::Update tmp{};
        int rc = from_proto<parameters::Update>(message.message.update, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_cmd_handling_Message_initialise_tag:
    {
        parameters::Initialise tmp{};
        int rc =
            from_proto<parameters::Initialise>(message.message.initialise, tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [8/40]
template<> int shrapnel::api::from_proto (const shrapnel_cmd_handling_Message & message, parameters::ApiMessage & out)
Definition at line 123 of file cmd_handling_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_cmd_handling_Message_update_tag:
    {
        parameters::Update tmp{};
        int rc = from_proto<parameters::Update>(message.message.update, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_cmd_handling_Message_initialise_tag:
    {
        parameters::Initialise tmp{};
        int rc =
            from_proto<parameters::Initialise>(message.message.initialise, tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [9/40]
template<> int shrapnel::api::from_proto (const shrapnel_cmd_handling_Update & message, parameters::Update & out)
Definition at line 107 of file cmd_handling_api.cpp.
{
    out.id = message.id;
    out.value = message.value;
    return 0;
}
References shrapnel::parameters::Update::id, and shrapnel::parameters::Update::value.
from_proto() [10/40]
template<> int shrapnel::api::from_proto (const shrapnel_messages_Message & message, ApiMessage & out)
Definition at line 110 of file messages.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_messages_Message_audio_event_tag:
    {
        events::ApiMessage tmp{};
        from_proto<events::ApiMessage>(message.message.audio_event, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_messages_Message_command_tag:
    {
        parameters::ApiMessage tmp{};
        from_proto<parameters::ApiMessage>(message.message.command, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_messages_Message_midi_mapping_tag:
    {
        midi::MappingApiMessage tmp{};
        from_proto<midi::MappingApiMessage>(message.message.midi_mapping, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_messages_Message_preset_tag:
    {
        presets::PresetsApiMessage tmp{};
        from_proto<presets::PresetsApiMessage>(message.message.preset, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_messages_Message_selected_preset_tag:
    {
        selected_preset::SelectedPresetApiMessage tmp{};
        from_proto<selected_preset::SelectedPresetApiMessage>(
            message.message.selected_preset, tmp);
        out = tmp;
        return 0;
    }
    }
    return -1;
}
from_proto() [11/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_CreateRequest & message, midi::CreateRequest & out)
Definition at line 245 of file midi_mapping_api.cpp.
{
    return from_proto<midi::Mapping>(message.mapping, out.mapping);
}
References shrapnel::midi::CreateRequest::mapping.
from_proto() [12/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_CreateResponse & message, midi::CreateResponse & out)
Definition at line 261 of file midi_mapping_api.cpp.
{
    return from_proto<std::pair<midi::Mapping::id_t, midi::Mapping>>(
        message.mapping, out.mapping);
}
References shrapnel::midi::CreateResponse::mapping.
from_proto() [13/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_GetRequest & , midi::GetRequest &)
Definition at line 230 of file midi_mapping_api.cpp.
{
    return 0;
}
from_proto() [14/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_Mapping & message, midi::Mapping & out)
Definition at line 177 of file midi_mapping_api.cpp.
{
    out.midi_channel = static_cast<uint8_t>(message.midi_channel);
    out.cc_number = static_cast<uint8_t>(message.cc_number);
    out.parameter_name = message.parameter_name;
    out.preset_id = message.preset_id;
    switch(message.mode)
    {
    case shrapnel_midi_mapping_Mapping_Mode_parameter:
        out.mode = midi::Mapping::Mode::PARAMETER;
        break;
    case shrapnel_midi_mapping_Mapping_Mode_toggle:
        out.mode = midi::Mapping::Mode::TOGGLE;
        break;
    case shrapnel_midi_mapping_Mapping_Mode_button:
        out.mode = midi::Mapping::Mode::BUTTON;
        break;
    default:
        return -1;
    }
    return 0;
}
References shrapnel::midi::Mapping::BUTTON, shrapnel::midi::Mapping::cc_number, shrapnel::midi::Mapping::midi_channel, shrapnel::midi::Mapping::mode, shrapnel::midi::Mapping::PARAMETER, shrapnel::midi::Mapping::parameter_name, shrapnel::midi::Mapping::preset_id, and shrapnel::midi::Mapping::TOGGLE.
from_proto() [15/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MappingRecord & message, std::pair< midi::Mapping::id_t, midi::Mapping > & out)
Definition at line 216 of file midi_mapping_api.cpp.
{
    out.first = message.id;
    return from_proto<midi::Mapping>(message.mapping, out.second);
}
from_proto() [16/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_Message & message, midi::MappingApiMessage & out)
Definition at line 573 of file midi_mapping_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_midi_mapping_Message_get_request_tag:
    {
        midi::GetRequest tmp{};
        int rc = from_proto<midi::GetRequest>(message.message.get_request, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_create_request_tag:
    {
        midi::CreateRequest tmp{};
        int rc = from_proto<midi::CreateRequest>(message.message.create_request,
                                                 tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_create_response_tag:
    {
        midi::CreateResponse tmp{};
        int rc = from_proto<midi::CreateResponse>(
            message.message.create_response, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_update_tag:
    {
        midi::Update tmp{};
        int rc = from_proto<midi::Update>(message.message.update, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_remove_tag:
    {
        midi::Remove tmp{};
        int rc = from_proto<midi::Remove>(message.message.remove, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_message_received_tag:
    {
        midi::MessageReceived tmp{};
        int rc = from_proto<midi::MessageReceived>(
            message.message.message_received, tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [17/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_Message & message, midi::MappingApiMessage & out)
Definition at line 573 of file midi_mapping_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_midi_mapping_Message_get_request_tag:
    {
        midi::GetRequest tmp{};
        int rc = from_proto<midi::GetRequest>(message.message.get_request, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_create_request_tag:
    {
        midi::CreateRequest tmp{};
        int rc = from_proto<midi::CreateRequest>(message.message.create_request,
                                                 tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_create_response_tag:
    {
        midi::CreateResponse tmp{};
        int rc = from_proto<midi::CreateResponse>(
            message.message.create_response, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_update_tag:
    {
        midi::Update tmp{};
        int rc = from_proto<midi::Update>(message.message.update, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_remove_tag:
    {
        midi::Remove tmp{};
        int rc = from_proto<midi::Remove>(message.message.remove, tmp);
        out = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_Message_message_received_tag:
    {
        midi::MessageReceived tmp{};
        int rc = from_proto<midi::MessageReceived>(
            message.message.message_received, tmp);
        out = tmp;
        return rc;
    }
    }
    return -1;
}
from_proto() [18/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MessageReceived & message, midi::MessageReceived & out)
Definition at line 484 of file midi_mapping_api.cpp.
{
    return from_proto<midi::Message>(message.received_message, out.message);
}
References shrapnel::midi::MessageReceived::message.
from_proto() [19/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage & message, midi::Message & out)
Definition at line 422 of file midi_mapping_api.cpp.
{
    out.channel = message.channel;
    std::optional<decltype(out.parameters)> parameters;
    switch(message.which_parameters)
    {
    case shrapnel_midi_mapping_MidiMessage_note_on_tag:
    {
        midi::Message::NoteOn tmp{};
        int rc =
            from_proto<midi::Message::NoteOn>(message.parameters.note_on, tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_note_off_tag:
    {
        midi::Message::NoteOff tmp{};
        int rc = from_proto<midi::Message::NoteOff>(message.parameters.note_off,
                                                    tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_control_change_tag:
    {
        midi::Message::ControlChange tmp{};
        int rc = from_proto<midi::Message::ControlChange>(
            message.parameters.control_change, tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_program_change_tag:
    {
        midi::Message::ProgramChange tmp{};
        int rc = from_proto<midi::Message::ProgramChange>(
            message.parameters.program_change, tmp);
        out.parameters = tmp;
        return rc;
    }
    default:
        return -1;
    }
}
References shrapnel::midi::Message::channel, and shrapnel::midi::Message::parameters.
from_proto() [20/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage & message, midi::Message & out)
Definition at line 422 of file midi_mapping_api.cpp.
{
    out.channel = message.channel;
    std::optional<decltype(out.parameters)> parameters;
    switch(message.which_parameters)
    {
    case shrapnel_midi_mapping_MidiMessage_note_on_tag:
    {
        midi::Message::NoteOn tmp{};
        int rc =
            from_proto<midi::Message::NoteOn>(message.parameters.note_on, tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_note_off_tag:
    {
        midi::Message::NoteOff tmp{};
        int rc = from_proto<midi::Message::NoteOff>(message.parameters.note_off,
                                                    tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_control_change_tag:
    {
        midi::Message::ControlChange tmp{};
        int rc = from_proto<midi::Message::ControlChange>(
            message.parameters.control_change, tmp);
        out.parameters = tmp;
        return rc;
    }
    case shrapnel_midi_mapping_MidiMessage_program_change_tag:
    {
        midi::Message::ProgramChange tmp{};
        int rc = from_proto<midi::Message::ProgramChange>(
            message.parameters.program_change, tmp);
        out.parameters = tmp;
        return rc;
    }
    default:
        return -1;
    }
}
References shrapnel::midi::Message::channel, and shrapnel::midi::Message::parameters.
from_proto() [21/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage_ControlChange & message, midi::Message::ControlChange & out)
Definition at line 348 of file midi_mapping_api.cpp.
{
    out.control = message.control;
    out.value = message.value;
    return 0;
}
References shrapnel::midi::Message::ControlChange::control, and shrapnel::midi::Message::ControlChange::value.
from_proto() [22/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage_NoteOff & message, midi::Message::NoteOff & out)
Definition at line 330 of file midi_mapping_api.cpp.
{
    out.note = message.note;
    out.velocity = message.velocity;
    return 0;
}
References shrapnel::midi::Message::NoteOff::note, and shrapnel::midi::Message::NoteOff::velocity.
from_proto() [23/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage_NoteOn & message, midi::Message::NoteOn & out)
Definition at line 312 of file midi_mapping_api.cpp.
{
    out.note = message.note;
    out.velocity = message.velocity;
    return 0;
}
References shrapnel::midi::Message::NoteOn::note, and shrapnel::midi::Message::NoteOn::velocity.
from_proto() [24/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_MidiMessage_ProgramChange & message, midi::Message::ProgramChange & out)
Definition at line 365 of file midi_mapping_api.cpp.
{
    out.number = message.number;
    return 0;
}
References shrapnel::midi::Message::ProgramChange::number.
from_proto() [25/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_Remove & message, midi::Remove & out)
Definition at line 296 of file midi_mapping_api.cpp.
{
    out.id = message.id;
    return 0;
}
References shrapnel::midi::Remove::id.
from_proto() [26/40]
template<> int shrapnel::api::from_proto (const shrapnel_midi_mapping_Update & message, midi::Update & out)
Definition at line 282 of file midi_mapping_api.cpp.
{
    return from_proto<std::pair<midi::Mapping::id_t, midi::Mapping>>(
        message.mapping, out.mapping);
}
References shrapnel::midi::Update::mapping.
from_proto() [27/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Create & message, presets::Create & out)
Definition at line 142 of file presets_api.cpp.
{
    return from_proto<presets::PresetData>(message.preset, out.preset);
}
References shrapnel::presets::Create::preset.
from_proto() [28/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Initialise & , presets::Initialise &)
Definition at line 113 of file presets_api.cpp.
{
    return 0;
}
from_proto() [29/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Message & message, presets::PresetsApiMessage & out)
Definition at line 246 of file presets_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_presets_Message_initialise_tag:
    {
        presets::Initialise tmp{};
        from_proto<presets::Initialise>(message.message.initialise, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_notify_tag:
    {
        presets::Notify tmp{};
        from_proto<presets::Notify>(message.message.notify, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_create_tag:
    {
        presets::Create tmp{};
        from_proto<presets::Create>(message.message.create, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_update_tag:
    {
        presets::Update tmp{};
        from_proto<presets::Update>(message.message.update, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_remove_tag:
    {
        presets::Delete tmp{};
        from_proto<presets::Delete>(message.message.remove, tmp);
        out = tmp;
        return 0;
    }
    }
    return -1;
}
from_proto() [30/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Message & message, presets::PresetsApiMessage & out)
Definition at line 246 of file presets_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_presets_Message_initialise_tag:
    {
        presets::Initialise tmp{};
        from_proto<presets::Initialise>(message.message.initialise, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_notify_tag:
    {
        presets::Notify tmp{};
        from_proto<presets::Notify>(message.message.notify, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_create_tag:
    {
        presets::Create tmp{};
        from_proto<presets::Create>(message.message.create, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_update_tag:
    {
        presets::Update tmp{};
        from_proto<presets::Update>(message.message.update, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_presets_Message_remove_tag:
    {
        presets::Delete tmp{};
        from_proto<presets::Delete>(message.message.remove, tmp);
        out = tmp;
        return 0;
    }
    }
    return -1;
}
from_proto() [31/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Notify & message, presets::Notify & out)
Definition at line 128 of file presets_api.cpp.
{
    out.id = message.preset.id;
    return from_proto<presets::PresetData>(message.preset.preset, out.preset);
}
References shrapnel::presets::Notify::id, and shrapnel::presets::Notify::preset.
from_proto() [32/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Preset & unpacked, presets::PresetData & out)
Definition at line 98 of file presets_api.cpp.
{
    out.name = unpacked.name;
    return from_proto<presets::ParametersData>(unpacked.parameters,
                                               out.parameters);
}
References shrapnel::presets::PresetData::name, and shrapnel::presets::PresetData::parameters.
from_proto() [33/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_PresetParameters & message, presets::ParametersData & out)
Definition at line 55 of file presets_api.cpp.
{
    out.amp_gain = message.amp_gain / 1000.f;
    out.amp_channel = message.amp_channel / 1000.f;
    out.bass = message.bass / 1000.f;
    out.middle = message.middle / 1000.f;
    out.treble = message.treble / 1000.f;
    out.contour = message.contour / 1000.f;
    out.volume = message.volume / 1000.f;
    out.noise_gate_threshold = message.noise_gate_threshold / 1000.f;
    out.noise_gate_hysteresis = message.noise_gate_hysteresis / 1000.f;
    out.noise_gate_attack = message.noise_gate_attack / 1000.f;
    out.noise_gate_hold = message.noise_gate_hold / 1000.f;
    out.noise_gate_release = message.noise_gate_release / 1000.f;
    out.noise_gate_bypass = message.noise_gate_bypass / 1000.f;
    out.chorus_rate = message.chorus_rate / 1000.f;
    out.chorus_depth = message.chorus_depth / 1000.f;
    out.chorus_mix = message.chorus_mix / 1000.f;
    out.chorus_bypass = message.chorus_bypass / 1000.f;
    out.wah_position = message.wah_position / 1000.f;
    out.wah_vocal = message.wah_vocal / 1000.f;
    out.wah_bypass = message.wah_bypass / 1000.f;
    return 0;
}
References shrapnel::presets::ParametersData::amp_channel, shrapnel::presets::ParametersData::amp_gain, shrapnel::presets::ParametersData::bass, shrapnel::presets::ParametersData::chorus_bypass, shrapnel::presets::ParametersData::chorus_depth, shrapnel::presets::ParametersData::chorus_mix, shrapnel::presets::ParametersData::chorus_rate, shrapnel::presets::ParametersData::contour, shrapnel::presets::ParametersData::middle, shrapnel::presets::ParametersData::noise_gate_attack, shrapnel::presets::ParametersData::noise_gate_bypass, shrapnel::presets::ParametersData::noise_gate_hold, shrapnel::presets::ParametersData::noise_gate_hysteresis, shrapnel::presets::ParametersData::noise_gate_release, shrapnel::presets::ParametersData::noise_gate_threshold, shrapnel::presets::ParametersData::treble, shrapnel::presets::ParametersData::volume, shrapnel::presets::ParametersData::wah_bypass, shrapnel::presets::ParametersData::wah_position, and shrapnel::presets::ParametersData::wah_vocal.
from_proto() [34/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Remove & message, presets::Delete & out)
Definition at line 171 of file presets_api.cpp.
{
    out.id = message.id;
    return 0;
}
References shrapnel::presets::Delete::id.
from_proto() [35/40]
template<> int shrapnel::api::from_proto (const shrapnel_presets_Update & message, presets::Update & out)
Definition at line 157 of file presets_api.cpp.
{
    out.id = message.preset.id;
    return from_proto<presets::PresetData>(message.preset.preset, out.preset);
}
References shrapnel::presets::Update::id, and shrapnel::presets::Update::preset.
from_proto() [36/40]
template<> int shrapnel::api::from_proto (const shrapnel_selected_preset_Message & message, selected_preset::SelectedPresetApiMessage & out)
Definition at line 118 of file selected_preset_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_selected_preset_Message_read_tag:
    {
        selected_preset::Read tmp{};
        from_proto<selected_preset::Read>(message.message.read, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_selected_preset_Message_notify_tag:
    {
        selected_preset::Notify tmp{};
        from_proto<selected_preset::Notify>(message.message.notify, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_selected_preset_Message_write_tag:
    {
        selected_preset::Write tmp{};
        from_proto<selected_preset::Write>(message.message.write, tmp);
        out = tmp;
        return 0;
    }
    }
    return -1;
}
from_proto() [37/40]
template<> int shrapnel::api::from_proto (const shrapnel_selected_preset_Message & message, selected_preset::SelectedPresetApiMessage & out)
Definition at line 118 of file selected_preset_api.cpp.
{
    switch(message.which_message)
    {
    case shrapnel_selected_preset_Message_read_tag:
    {
        selected_preset::Read tmp{};
        from_proto<selected_preset::Read>(message.message.read, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_selected_preset_Message_notify_tag:
    {
        selected_preset::Notify tmp{};
        from_proto<selected_preset::Notify>(message.message.notify, tmp);
        out = tmp;
        return 0;
    }
    case shrapnel_selected_preset_Message_write_tag:
    {
        selected_preset::Write tmp{};
        from_proto<selected_preset::Write>(message.message.write, tmp);
        out = tmp;
        return 0;
    }
    }
    return -1;
}
from_proto() [38/40]
template<> int shrapnel::api::from_proto (const shrapnel_selected_preset_Notify & message, selected_preset::Notify & out)
Definition at line 102 of file selected_preset_api.cpp.
{
    out.selectedPresetId = message.id;
    return 0;
}
References shrapnel::selected_preset::Notify::selectedPresetId.
from_proto() [39/40]
template<> int shrapnel::api::from_proto (const shrapnel_selected_preset_Read & , selected_preset::Read &)
Definition at line 96 of file selected_preset_api.cpp.
{
    return 0;
}
from_proto() [40/40]
template<> int shrapnel::api::from_proto (const shrapnel_selected_preset_Write & message, selected_preset::Write & out)
Definition at line 110 of file selected_preset_api.cpp.
{
    out.selectedPresetId = message.id;
    return 0;
}
References shrapnel::selected_preset::Write::selectedPresetId.
to_bytes() [1/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const ApiMessage & message, std::span< uint8_t > buffer)
Definition at line 156 of file messages.cpp.
{
    shrapnel_messages_Message proto_message =
        shrapnel_messages_Message_init_zero;
    int rc = to_proto<shrapnel_messages_Message>(message, proto_message);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto_message, buffer);
}
References to_bytes().
to_bytes() [2/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const ApiMessage & message, std::span< uint8_t > buffer)
Definition at line 156 of file messages.cpp.
{
    shrapnel_messages_Message proto_message =
        shrapnel_messages_Message_init_zero;
    int rc = to_proto<shrapnel_messages_Message>(message, proto_message);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto_message, buffer);
}
References to_bytes().
to_bytes() [3/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const midi::Mapping & message, std::span< uint8_t > buffer)
Definition at line 629 of file midi_mapping_api.cpp.
{
    shrapnel_midi_mapping_Mapping proto;
    int rc = to_proto(message, proto);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto, buffer);
}
References to_bytes(), and to_proto().
to_bytes() [4/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const midi::Mapping & message, std::span< uint8_t > buffer)
Definition at line 629 of file midi_mapping_api.cpp.
{
    shrapnel_midi_mapping_Mapping proto;
    int rc = to_proto(message, proto);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto, buffer);
}
References to_bytes(), and to_proto().
to_bytes() [5/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const presets::PresetData & message, std::span< uint8_t > buffer)
Definition at line 322 of file presets_api.cpp.
{
    shrapnel_presets_Preset proto = shrapnel_presets_Preset_init_zero;
    int rc = to_proto(message, proto);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto, buffer);
}
References to_bytes(), and to_proto().
to_bytes() [6/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const presets::PresetData & message, std::span< uint8_t > buffer)
Definition at line 322 of file presets_api.cpp.
{
    shrapnel_presets_Preset proto = shrapnel_presets_Preset_init_zero;
    int rc = to_proto(message, proto);
    if(rc != 0)
    {
        return std::nullopt;
    }
    return to_bytes(proto, buffer);
}
References to_bytes(), and to_proto().
to_bytes() [7/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const shrapnel_messages_Message & message, std::span< uint8_t > buffer)
Definition at line 32 of file messages.cpp.
{
    pb_ostream_t stream = pb_ostream_from_buffer(buffer.data(), buffer.size());
    bool success = pb_encode(&stream, &shrapnel_messages_Message_msg, &message);
    if(!success)
    {
        return std::nullopt;
    }
    return buffer.subspan(0, stream.bytes_written);
}
to_bytes() [8/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const shrapnel_midi_mapping_Mapping & message, std::span< uint8_t > buffer)
Definition at line 118 of file midi_mapping_api.cpp.
{
    pb_ostream_t stream = pb_ostream_from_buffer(buffer.data(), buffer.size());
    bool success =
        pb_encode(&stream, &shrapnel_midi_mapping_Mapping_msg, &message);
    if(!success)
    {
        return std::nullopt;
    }
    return buffer.subspan(0, stream.bytes_written);
}
to_bytes() [9/10]
template<> std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const shrapnel_presets_Preset & proto, std::span< uint8_t > buffer)
Definition at line 292 of file presets_api.cpp.
{
    pb_ostream_t stream = pb_ostream_from_buffer(buffer.data(), buffer.size());
    bool success = pb_encode(&stream, &shrapnel_presets_Preset_msg, &proto);
    if(!success)
    {
        return std::nullopt;
    }
    return buffer.subspan(0, stream.bytes_written);
}
to_bytes() [10/10]
template<typename T > std::optional< std::span< uint8_t > > shrapnel::api::to_bytes (const T & message, std::span< uint8_t > buffer)
Convert a message to bytes to be sent over the network to the frontend.
Referenced by shrapnel::midi::MappingManager< MAX_MAPPINGS, MAX_OBSERVERS >::create(), shrapnel::presets::PresetsManager::create(), to_bytes(), shrapnel::presets::PresetsManager::update(), and shrapnel::midi::MappingManager< MAX_MAPPINGS, MAX_OBSERVERS >::update().
to_proto() [1/39]
template<> int shrapnel::api::to_proto (const ApiMessage & message, shrapnel_messages_Message & out)
Definition at line 62 of file messages.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, events::ApiMessage>)
            {
                out.which_message = shrapnel_messages_Message_audio_event_tag;
                return to_proto<shrapnel_audio_events_Message>(
                    message, out.message.audio_event);
            }
            else if constexpr(std::is_same_v<T, parameters::ApiMessage>)
            {
                out.which_message = shrapnel_messages_Message_command_tag;
                return to_proto<shrapnel_cmd_handling_Message>(
                    message, out.message.command);
            }
            else if constexpr(std::is_same_v<T, midi::MappingApiMessage>)
            {
                out.which_message = shrapnel_messages_Message_midi_mapping_tag;
                return to_proto<shrapnel_midi_mapping_Message>(
                    message, out.message.midi_mapping);
            }
            else if constexpr(std::is_same_v<T, presets::PresetsApiMessage>)
            {
                out.which_message = shrapnel_messages_Message_preset_tag;
                return to_proto<shrapnel_presets_Message>(message,
                                                          out.message.preset);
            }
            else if constexpr(std::is_same_v<
                                  T,
                                  selected_preset::SelectedPresetApiMessage>)
            {
                out.which_message =
                    shrapnel_messages_Message_selected_preset_tag;
                return to_proto<shrapnel_selected_preset_Message>(
                    message, out.message.selected_preset);
            }
            else
            {
                return -1;
            }
        },
        message);
}
to_proto() [2/39]
template<> int shrapnel::api::to_proto (const events::ApiMessage & message, shrapnel_audio_events_Message & out)
Definition at line 100 of file audio_events.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, events::InputClipped>)
            {
                out.which_event =
                    shrapnel_audio_events_Message_input_clipped_tag;
                int rc = to_proto<shrapnel_audio_events_InputClipped>(
                    message, out.event.input_clipped);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, events::OutputClipped>)
            {
                out.which_event =
                    shrapnel_audio_events_Message_output_clipped_tag;
                int rc = to_proto<shrapnel_audio_events_OutputClipped>(
                    message, out.event.output_clipped);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [3/39]
template<> int shrapnel::api::to_proto (const events::ApiMessage & message, shrapnel_audio_events_Message & out)
Definition at line 100 of file audio_events.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, events::InputClipped>)
            {
                out.which_event =
                    shrapnel_audio_events_Message_input_clipped_tag;
                int rc = to_proto<shrapnel_audio_events_InputClipped>(
                    message, out.event.input_clipped);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, events::OutputClipped>)
            {
                out.which_event =
                    shrapnel_audio_events_Message_output_clipped_tag;
                int rc = to_proto<shrapnel_audio_events_OutputClipped>(
                    message, out.event.output_clipped);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [4/39]
template<> int shrapnel::api::to_proto (const events::InputClipped & , shrapnel_audio_events_InputClipped &)
Definition at line 73 of file audio_events.cpp.
{
    return 0;
}
to_proto() [5/39]
template<> int shrapnel::api::to_proto (const events::OutputClipped & , shrapnel_audio_events_OutputClipped &)
Definition at line 86 of file audio_events.cpp.
{
    return 0;
}
to_proto() [6/39]
template<> int shrapnel::api::to_proto (const midi::CreateRequest & message, shrapnel_midi_mapping_CreateRequest & out)
Definition at line 236 of file midi_mapping_api.cpp.
{
    out.has_mapping = true;
    return to_proto<shrapnel_midi_mapping_Mapping>(message.mapping,
                                                   out.mapping);
}
References shrapnel::midi::CreateRequest::mapping.
to_proto() [7/39]
template<> int shrapnel::api::to_proto (const midi::CreateResponse & message, shrapnel_midi_mapping_CreateResponse & out)
Definition at line 252 of file midi_mapping_api.cpp.
{
    out.has_mapping = true;
    return to_proto<shrapnel_midi_mapping_MappingRecord>(message.mapping,
                                                         out.mapping);
}
References shrapnel::midi::CreateResponse::mapping.
to_proto() [8/39]
template<> int shrapnel::api::to_proto (const midi::GetRequest & , shrapnel_midi_mapping_GetRequest &)
Definition at line 224 of file midi_mapping_api.cpp.
{
    return 0;
}
to_proto() [9/39]
template<> int shrapnel::api::to_proto (const midi::Mapping & message, shrapnel_midi_mapping_Mapping & out)
Definition at line 151 of file midi_mapping_api.cpp.
{
    out.midi_channel = message.midi_channel;
    out.cc_number = message.cc_number;
    switch(message.mode)
    {
    case midi::Mapping::Mode::PARAMETER:
        out.mode = shrapnel_midi_mapping_Mapping_Mode_parameter;
        break;
    case midi::Mapping::Mode::TOGGLE:
        out.mode = shrapnel_midi_mapping_Mapping_Mode_toggle;
        break;
    case midi::Mapping::Mode::BUTTON:
        out.mode = shrapnel_midi_mapping_Mapping_Mode_button;
        break;
    default:
        return -1;
    }
    strncpy(out.parameter_name,
            message.parameter_name.data(),
            sizeof out.parameter_name);
    out.preset_id = message.preset_id;
    return 0;
}
References shrapnel::midi::Mapping::BUTTON, shrapnel::midi::Mapping::cc_number, shrapnel::midi::Mapping::midi_channel, shrapnel::midi::Mapping::mode, shrapnel::midi::Mapping::PARAMETER, shrapnel::midi::Mapping::parameter_name, shrapnel::midi::Mapping::preset_id, and shrapnel::midi::Mapping::TOGGLE.
to_proto() [10/39]
template<> int shrapnel::api::to_proto (const midi::MappingApiMessage & message, shrapnel_midi_mapping_Message & out)
Definition at line 491 of file midi_mapping_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, midi::GetRequest>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_get_request_tag;
                int rc = to_proto<shrapnel_midi_mapping_GetRequest>(
                    message, out.message.get_request);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::CreateRequest>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_create_request_tag;
                int rc = to_proto<shrapnel_midi_mapping_CreateRequest>(
                    message, out.message.create_request);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::CreateResponse>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_create_response_tag;
                int rc = to_proto<shrapnel_midi_mapping_CreateResponse>(
                    message, out.message.create_response);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::Update>)
            {
                out.which_message = shrapnel_midi_mapping_Message_update_tag;
                int rc = to_proto<shrapnel_midi_mapping_Update>(
                    message, out.message.update);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::Remove>)
            {
                out.which_message = shrapnel_midi_mapping_Message_remove_tag;
                int rc = to_proto<shrapnel_midi_mapping_Remove>(
                    message, out.message.remove);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::MessageReceived>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_message_received_tag;
                int rc = to_proto<shrapnel_midi_mapping_MessageReceived>(
                    message, out.message.message_received);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [11/39]
template<> int shrapnel::api::to_proto (const midi::MappingApiMessage & message, shrapnel_midi_mapping_Message & out)
Definition at line 491 of file midi_mapping_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, midi::GetRequest>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_get_request_tag;
                int rc = to_proto<shrapnel_midi_mapping_GetRequest>(
                    message, out.message.get_request);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::CreateRequest>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_create_request_tag;
                int rc = to_proto<shrapnel_midi_mapping_CreateRequest>(
                    message, out.message.create_request);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::CreateResponse>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_create_response_tag;
                int rc = to_proto<shrapnel_midi_mapping_CreateResponse>(
                    message, out.message.create_response);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::Update>)
            {
                out.which_message = shrapnel_midi_mapping_Message_update_tag;
                int rc = to_proto<shrapnel_midi_mapping_Update>(
                    message, out.message.update);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::Remove>)
            {
                out.which_message = shrapnel_midi_mapping_Message_remove_tag;
                int rc = to_proto<shrapnel_midi_mapping_Remove>(
                    message, out.message.remove);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, midi::MessageReceived>)
            {
                out.which_message =
                    shrapnel_midi_mapping_Message_message_received_tag;
                int rc = to_proto<shrapnel_midi_mapping_MessageReceived>(
                    message, out.message.message_received);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [12/39]
template<> int shrapnel::api::to_proto (const midi::Message & message, shrapnel_midi_mapping_MidiMessage & out)
Definition at line 373 of file midi_mapping_api.cpp.
{
    auto channel = message.channel;
    return std::visit(
        [channel, &out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            out.channel = channel;
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, midi::Message::NoteOn>)
            {
                out.which_parameters =
                    shrapnel_midi_mapping_MidiMessage_note_on_tag;
                return to_proto<shrapnel_midi_mapping_MidiMessage_NoteOn>(
                    message, out.parameters.note_on);
            }
            else if constexpr(std::is_same_v<T, midi::Message::NoteOff>)
            {
                out.which_parameters =
                    shrapnel_midi_mapping_MidiMessage_note_off_tag;
                return to_proto<shrapnel_midi_mapping_MidiMessage_NoteOff>(
                    message, out.parameters.note_off);
            }
            else if constexpr(std::is_same_v<T, midi::Message::ControlChange>)
            {
                out.which_parameters =
                    shrapnel_midi_mapping_MidiMessage_control_change_tag;
                return to_proto<
                    shrapnel_midi_mapping_MidiMessage_ControlChange>(
                    message, out.parameters.control_change);
            }
            else if constexpr(std::is_same_v<T, midi::Message::ProgramChange>)
            {
                out.which_parameters =
                    shrapnel_midi_mapping_MidiMessage_program_change_tag;
                return to_proto<
                    shrapnel_midi_mapping_MidiMessage_ProgramChange>(
                    message, out.parameters.program_change);
            }
            return -1;
        },
        message.parameters);
}
References shrapnel::midi::Message::channel, shrapnel::midi::Message::parameters, and to_proto().
to_proto() [13/39]
template<> int shrapnel::api::to_proto (const midi::Message::ControlChange & message, shrapnel_midi_mapping_MidiMessage_ControlChange & out)
Definition at line 339 of file midi_mapping_api.cpp.
{
    out.control = message.control;
    out.value = message.value;
    return 0;
}
References shrapnel::midi::Message::ControlChange::control, and shrapnel::midi::Message::ControlChange::value.
to_proto() [14/39]
template<> int shrapnel::api::to_proto (const midi::Message::NoteOff & message, shrapnel_midi_mapping_MidiMessage_NoteOff & out)
Definition at line 321 of file midi_mapping_api.cpp.
{
    out.note = message.note;
    out.velocity = message.velocity;
    return 0;
}
References shrapnel::midi::Message::NoteOff::note, and shrapnel::midi::Message::NoteOff::velocity.
to_proto() [15/39]
template<> int shrapnel::api::to_proto (const midi::Message::NoteOn & message, shrapnel_midi_mapping_MidiMessage_NoteOn & out)
Definition at line 303 of file midi_mapping_api.cpp.
{
    out.note = message.note;
    out.velocity = message.velocity;
    return 0;
}
References shrapnel::midi::Message::NoteOn::note, and shrapnel::midi::Message::NoteOn::velocity.
to_proto() [16/39]
template<> int shrapnel::api::to_proto (const midi::Message::ProgramChange & message, shrapnel_midi_mapping_MidiMessage_ProgramChange & out)
Definition at line 357 of file midi_mapping_api.cpp.
{
    out.number = message.number;
    return 0;
}
References shrapnel::midi::Message::ProgramChange::number.
to_proto() [17/39]
template<> int shrapnel::api::to_proto (const midi::MessageReceived & message, shrapnel_midi_mapping_MessageReceived & out)
Definition at line 469 of file midi_mapping_api.cpp.
{
    out.has_received_message = true;
    int rc = to_proto<shrapnel_midi_mapping_MidiMessage>(message.message,
                                                         out.received_message);
    if(rc != 0)
    {
        return -1;
    }
    out.has_received_message = true;
    return 0;
}
References shrapnel::midi::MessageReceived::message.
to_proto() [18/39]
template<> int shrapnel::api::to_proto (const midi::Remove & message, shrapnel_midi_mapping_Remove & out)
Definition at line 289 of file midi_mapping_api.cpp.
{
    out.id = message.id;
    return 0;
}
References shrapnel::midi::Remove::id.
to_proto() [19/39]
template<> int shrapnel::api::to_proto (const midi::Update & message, shrapnel_midi_mapping_Update & out)
Definition at line 269 of file midi_mapping_api.cpp.
{
    out.has_mapping = true;
    int rc = to_proto<shrapnel_midi_mapping_MappingRecord>(message.mapping,
                                                           out.mapping);
    if(rc != 0)
    {
        return -1;
    }
    return 0;
}
References shrapnel::midi::Update::mapping.
to_proto() [20/39]
template<> int shrapnel::api::to_proto (const parameters::ApiMessage & message, shrapnel_cmd_handling_Message & out)
Definition at line 81 of file cmd_handling_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, parameters::Update>)
            {
                out.which_message = shrapnel_cmd_handling_Message_update_tag;
                return to_proto<shrapnel_cmd_handling_Update>(
                    message, out.message.update);
            }
            else if constexpr(std::is_same_v<T, parameters::Initialise>)
            {
                out.which_message =
                    shrapnel_cmd_handling_Message_initialise_tag;
                return to_proto<shrapnel_cmd_handling_Initialise>(
                    message, out.message.initialise);
            }
            return -1;
        },
        message);
}
to_proto() [21/39]
template<> int shrapnel::api::to_proto (const parameters::ApiMessage & message, shrapnel_cmd_handling_Message & out)
Definition at line 81 of file cmd_handling_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, parameters::Update>)
            {
                out.which_message = shrapnel_cmd_handling_Message_update_tag;
                return to_proto<shrapnel_cmd_handling_Update>(
                    message, out.message.update);
            }
            else if constexpr(std::is_same_v<T, parameters::Initialise>)
            {
                out.which_message =
                    shrapnel_cmd_handling_Message_initialise_tag;
                return to_proto<shrapnel_cmd_handling_Initialise>(
                    message, out.message.initialise);
            }
            return -1;
        },
        message);
}
to_proto() [22/39]
template<> int shrapnel::api::to_proto (const parameters::Initialise & , shrapnel_cmd_handling_Initialise &)
Definition at line 75 of file cmd_handling_api.cpp.
{
    return 0;
}
to_proto() [23/39]
template<> int shrapnel::api::to_proto (const parameters::Update & message, shrapnel_cmd_handling_Update & out)
Definition at line 66 of file cmd_handling_api.cpp.
{
    out.value = message.value;
    strncpy(out.id, message.id.data(), sizeof out.id);
    return 0;
}
References shrapnel::parameters::Update::id, and shrapnel::parameters::Update::value.
to_proto() [24/39]
template<> int shrapnel::api::to_proto (const presets::Create & message, shrapnel_presets_Create & out)
Definition at line 135 of file presets_api.cpp.
{
    out.has_preset = true;
    return to_proto<shrapnel_presets_Preset>(message.preset, out.preset);
}
References shrapnel::presets::Create::preset.
to_proto() [25/39]
template<> int shrapnel::api::to_proto (const presets::Delete & message, shrapnel_presets_Remove & out)
Definition at line 164 of file presets_api.cpp.
{
    out.id = message.id;
    return 0;
}
References shrapnel::presets::Delete::id.
to_proto() [26/39]
template<> int shrapnel::api::to_proto (const presets::Initialise & , shrapnel_presets_Initialise &)
Definition at line 107 of file presets_api.cpp.
{
    return 0;
}
to_proto() [27/39]
template<> int shrapnel::api::to_proto (const presets::Notify & message, shrapnel_presets_Notify & out)
Definition at line 119 of file presets_api.cpp.
{
    out.preset.id = message.id;
    out.has_preset = true;
    out.preset.has_preset = true;
    return to_proto<shrapnel_presets_Preset>(message.preset, out.preset.preset);
}
References shrapnel::presets::Notify::id, and shrapnel::presets::Notify::preset.
to_proto() [28/39]
template<> int shrapnel::api::to_proto (const presets::ParametersData & message, shrapnel_presets_PresetParameters & out)
Definition at line 28 of file presets_api.cpp.
{
    out.amp_gain = message.amp_gain * 1000;
    out.amp_channel = message.amp_channel * 1000;
    out.bass = message.bass * 1000;
    out.middle = message.middle * 1000;
    out.treble = message.treble * 1000;
    out.contour = message.contour * 1000;
    out.volume = message.volume * 1000;
    out.noise_gate_threshold = message.noise_gate_threshold * 1000;
    out.noise_gate_hysteresis = message.noise_gate_hysteresis * 1000;
    out.noise_gate_attack = message.noise_gate_attack * 1000;
    out.noise_gate_hold = message.noise_gate_hold * 1000;
    out.noise_gate_release = message.noise_gate_release * 1000;
    out.noise_gate_bypass = message.noise_gate_bypass * 1000;
    out.chorus_rate = message.chorus_rate * 1000;
    out.chorus_depth = message.chorus_depth * 1000;
    out.chorus_mix = message.chorus_mix * 1000;
    out.chorus_bypass = message.chorus_bypass * 1000;
    out.wah_position = message.wah_position * 1000;
    out.wah_vocal = message.wah_vocal * 1000;
    out.wah_bypass = message.wah_bypass * 1000;
    return 0;
}
References shrapnel::presets::ParametersData::amp_channel, shrapnel::presets::ParametersData::amp_gain, shrapnel::presets::ParametersData::bass, shrapnel::presets::ParametersData::chorus_bypass, shrapnel::presets::ParametersData::chorus_depth, shrapnel::presets::ParametersData::chorus_mix, shrapnel::presets::ParametersData::chorus_rate, shrapnel::presets::ParametersData::contour, shrapnel::presets::ParametersData::middle, shrapnel::presets::ParametersData::noise_gate_attack, shrapnel::presets::ParametersData::noise_gate_bypass, shrapnel::presets::ParametersData::noise_gate_hold, shrapnel::presets::ParametersData::noise_gate_hysteresis, shrapnel::presets::ParametersData::noise_gate_release, shrapnel::presets::ParametersData::noise_gate_threshold, shrapnel::presets::ParametersData::treble, shrapnel::presets::ParametersData::volume, shrapnel::presets::ParametersData::wah_bypass, shrapnel::presets::ParametersData::wah_position, and shrapnel::presets::ParametersData::wah_vocal.
to_proto() [29/39]
template<> int shrapnel::api::to_proto (const presets::PresetData & preset, shrapnel_presets_Preset & out)
Definition at line 82 of file presets_api.cpp.
{
    int rc = to_proto<shrapnel_presets_PresetParameters>(preset.parameters,
                                                         out.parameters);
    if(rc != 0)
    {
        return -1;
    }
    out.has_parameters = true;
    strncpy(out.name, preset.name.data(), sizeof out.name);
    return 0;
}
References shrapnel::presets::PresetData::name, and shrapnel::presets::PresetData::parameters.
to_proto() [30/39]
template<> int shrapnel::api::to_proto (const presets::PresetsApiMessage & message, shrapnel_presets_Message & out)
Definition at line 178 of file presets_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, presets::Initialise>)
            {
                out.which_message = shrapnel_presets_Message_initialise_tag;
                int rc = to_proto<shrapnel_presets_Initialise>(
                    message, out.message.initialise);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Notify>)
            {
                out.which_message = shrapnel_presets_Message_notify_tag;
                int rc = to_proto<shrapnel_presets_Notify>(message,
                                                           out.message.notify);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Create>)
            {
                out.which_message = shrapnel_presets_Message_create_tag;
                int rc = to_proto<shrapnel_presets_Create>(message,
                                                           out.message.create);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Update>)
            {
                out.which_message = shrapnel_presets_Message_update_tag;
                int rc = to_proto<shrapnel_presets_Update>(message,
                                                           out.message.update);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Delete>)
            {
                out.which_message = shrapnel_presets_Message_remove_tag;
                int rc = to_proto<shrapnel_presets_Remove>(message,
                                                           out.message.remove);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [31/39]
template<> int shrapnel::api::to_proto (const presets::PresetsApiMessage & message, shrapnel_presets_Message & out)
Definition at line 178 of file presets_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, presets::Initialise>)
            {
                out.which_message = shrapnel_presets_Message_initialise_tag;
                int rc = to_proto<shrapnel_presets_Initialise>(
                    message, out.message.initialise);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Notify>)
            {
                out.which_message = shrapnel_presets_Message_notify_tag;
                int rc = to_proto<shrapnel_presets_Notify>(message,
                                                           out.message.notify);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Create>)
            {
                out.which_message = shrapnel_presets_Message_create_tag;
                int rc = to_proto<shrapnel_presets_Create>(message,
                                                           out.message.create);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Update>)
            {
                out.which_message = shrapnel_presets_Message_update_tag;
                int rc = to_proto<shrapnel_presets_Update>(message,
                                                           out.message.update);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, presets::Delete>)
            {
                out.which_message = shrapnel_presets_Message_remove_tag;
                int rc = to_proto<shrapnel_presets_Remove>(message,
                                                           out.message.remove);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [32/39]
template<> int shrapnel::api::to_proto (const presets::Update & message, shrapnel_presets_Update & out)
Definition at line 148 of file presets_api.cpp.
{
    out.preset.id = message.id;
    out.has_preset = true;
    out.preset.has_preset = true;
    return to_proto<shrapnel_presets_Preset>(message.preset, out.preset.preset);
}
References shrapnel::presets::Update::id, and shrapnel::presets::Update::preset.
to_proto() [33/39]
template<> int shrapnel::api::to_proto (const selected_preset ::Write & message, shrapnel_selected_preset_Write & out)
Definition at line 40 of file selected_preset_api.cpp.
{
    out.id = message.selectedPresetId;
    return 0;
}
to_proto() [34/39]
template<> int shrapnel::api::to_proto (const selected_preset::Notify & message, shrapnel_selected_preset_Notify & out)
Definition at line 32 of file selected_preset_api.cpp.
{
    out.id = message.selectedPresetId;
    return 0;
}
References shrapnel::selected_preset::Notify::selectedPresetId.
to_proto() [35/39]
template<> int shrapnel::api::to_proto (const selected_preset::Read & , shrapnel_selected_preset_Read &)
Definition at line 26 of file selected_preset_api.cpp.
{
    return 0;
}
to_proto() [36/39]
template<> int shrapnel::api::to_proto (const selected_preset::SelectedPresetApiMessage & message, shrapnel_selected_preset_Message & out)
Definition at line 48 of file selected_preset_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, selected_preset::Read>)
            {
                out.which_message = shrapnel_selected_preset_Message_read_tag;
                int rc = to_proto<shrapnel_selected_preset_Read>(
                    message, out.message.read);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, selected_preset::Notify>)
            {
                out.which_message = shrapnel_selected_preset_Message_notify_tag;
                int rc = to_proto<shrapnel_selected_preset_Notify>(
                    message, out.message.notify);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, selected_preset::Write>)
            {
                out.which_message = shrapnel_selected_preset_Message_write_tag;
                int rc = to_proto<shrapnel_selected_preset_Write>(
                    message, out.message.write);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [37/39]
template<> int shrapnel::api::to_proto (const selected_preset::SelectedPresetApiMessage & message, shrapnel_selected_preset_Message & out)
Definition at line 48 of file selected_preset_api.cpp.
{
    return std::visit(
        [&out](const auto &message) -> int
        {
            using T = std::decay_t<decltype(message)>;
            if constexpr(std::is_same_v<T, selected_preset::Read>)
            {
                out.which_message = shrapnel_selected_preset_Message_read_tag;
                int rc = to_proto<shrapnel_selected_preset_Read>(
                    message, out.message.read);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, selected_preset::Notify>)
            {
                out.which_message = shrapnel_selected_preset_Message_notify_tag;
                int rc = to_proto<shrapnel_selected_preset_Notify>(
                    message, out.message.notify);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else if constexpr(std::is_same_v<T, selected_preset::Write>)
            {
                out.which_message = shrapnel_selected_preset_Message_write_tag;
                int rc = to_proto<shrapnel_selected_preset_Write>(
                    message, out.message.write);
                if(rc != 0)
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
            return 0;
        },
        message);
}
to_proto() [38/39]
template<> int shrapnel::api::to_proto (const std::pair< midi::Mapping::id_t, midi::Mapping > & message, shrapnel_midi_mapping_MappingRecord & out)
Definition at line 201 of file midi_mapping_api.cpp.
{
    int rc =
        to_proto<shrapnel_midi_mapping_Mapping>(message.second, out.mapping);
    if(rc != 0)
    {
        return -1;
    }
    out.has_mapping = true;
    out.id = message.first;
    return 0;
}
to_proto() [39/39]
template<typename ProtoT , typename T > int shrapnel::api::to_proto (const T & message, ProtoT & out)
Convert a message to proto struct.
Referenced by to_bytes(), and to_proto().