ShrapnelDSP: shrapnel::selected_preset Namespace Reference
shrapnel::selected_preset Namespace Reference
Data Structures
struct Notify
struct Read
class SelectedPresetManager
struct Write
Typedefs
using SelectedPresetApiMessage = std::variant< Read, Notify, Write >
Functions
etl::string_stream & operator<< (etl::string_stream &out, const Read &self)
etl::string_stream & operator<< (etl::string_stream &out, const Notify &self)
etl::string_stream & operator<< (etl::string_stream &out, const Write &self)
etl::string_stream & operator<< (etl::string_stream &out, const SelectedPresetApiMessage &self)
template<typename T >
rapidjson::Value to_json (rapidjson::Document &document, const T &object)
Convert object to a JSON value.
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Notify &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const SelectedPresetApiMessage &object)
template<typename T >
std::optional< T > from_json (const rapidjson::Value &)
template<>
std::optional< Read > from_json (const rapidjson::Value &json)
template<>
std::optional< Write > from_json (const rapidjson::Value &json)
template<>
std::optional< SelectedPresetApiMessage > from_json (const rapidjson::Value &json)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Notify &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const SelectedPresetApiMessage &object)
template<>
std::optional< Read > from_json (const rapidjson::Value &json)
template<>
std::optional< Write > from_json (const rapidjson::Value &json)
template<>
std::optional< SelectedPresetApiMessage > from_json (const rapidjson::Value &json)
template<typename T >
constexpr const char * get_message_type ()
template<>
constexpr const char * get_message_type< Read > ()
template<>
constexpr const char * get_message_type< Notify > ()
template<>
constexpr const char * get_message_type< Write > ()
Variables
constexpr char key [] = "selected_preset"
Typedef Documentation
SelectedPresetApiMessage
using shrapnel::selected_preset::SelectedPresetApiMessage = typedef std::variant<Read, Notify, Write>
Definition at line 49 of file selected_preset_api.h.
Function Documentation
from_json() [1/7]
template<typename T > std::optional< T > shrapnel::selected_preset::from_json (const rapidjson::Value &)
from_json() [2/7]
template<> std::optional< Read > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 28 of file selected_preset_json_parser.cpp.
{
    return Read{};
}
from_json() [3/7]
template<> std::optional< Write > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 28 of file selected_preset_json_parser.cpp.
{
    return Read{};
}
from_json() [4/7]
template<> std::optional< SelectedPresetApiMessage > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 28 of file selected_preset_json_parser.cpp.
{
    return Read{};
}
References get_message_type< Read >(), get_message_type< Write >(), and shrapnel::selected_preset::Write::selectedPresetId.
from_json() [5/7]
template<> std::optional< Read > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 28 of file selected_preset_json_parser.cpp.
{
    return Read{};
}
from_json() [6/7]
template<> std::optional< Write > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 34 of file selected_preset_json_parser.cpp.
{
    auto id_json = json.FindMember("selectedPreset");
    if(id_json == json.MemberEnd())
    {
        return std::nullopt;
    }
    if(!id_json->value.IsUint())
    {
        return std::nullopt;
    }
    return Write{.selectedPresetId{id_json->value.GetUint()}};
}
References shrapnel::selected_preset::Write::selectedPresetId.
from_json() [7/7]
template<> std::optional< SelectedPresetApiMessage > shrapnel::selected_preset::from_json (const rapidjson::Value & json)
Definition at line 51 of file selected_preset_json_parser.cpp.
{
    constexpr char TAG[] = "SelectedPresetApiMessage from_json";
    auto message_type_member = json.FindMember("messageType");
    if(message_type_member == json.MemberEnd())
    {
        ESP_LOGE(TAG, "messageType is missing");
        goto error;
    }
    if(!message_type_member->value.IsString())
    {
        ESP_LOGE(TAG, "messageType is not string");
        goto error;
    }
    {
        const etl::map<std::string,
                       std::function<std::optional<SelectedPresetApiMessage>()>,
                       2>
            lut{
                {get_message_type<Read>(),
                 [&] { return from_json<Read>(json); }},
                {get_message_type<Write>(),
                 [&] { return from_json<Write>(json); }},
            };
        const char *message_type = message_type_member->value.GetString();
        if(auto f = lut.find(message_type); f != lut.end())
        {
            return f->second();
        }
    }
error:
    return std::nullopt;
}
References get_message_type< Read >(), and get_message_type< Write >().
get_message_type()
template<typename T > constexpr const char * shrapnel::selected_preset::get_message_type () constexpr
get_message_type< Notify >()
template<> constexpr const char * shrapnel::selected_preset::get_message_type< Notify > () constexpr
Definition at line 36 of file selected_preset_message_type.h.
{
    return "SelectedPreset::notify";
}
get_message_type< Read >()
template<> constexpr const char * shrapnel::selected_preset::get_message_type< Read > () constexpr
Definition at line 30 of file selected_preset_message_type.h.
{
    return "SelectedPreset::read";
}
Referenced by from_json().
get_message_type< Write >()
template<> constexpr const char * shrapnel::selected_preset::get_message_type< Write > () constexpr
Definition at line 42 of file selected_preset_message_type.h.
{
    return "SelectedPreset::write";
}
Referenced by from_json().
operator<<() [1/4]
etl::string_stream & shrapnel::selected_preset::operator<< (etl::string_stream & out, const Notify & self)
Definition at line 30 of file selected_preset_to_string.cpp.
{
    return out << "{ selected_preset=" << self.selectedPresetId << " }";
}
References shrapnel::selected_preset::Notify::selectedPresetId.
operator<<() [2/4]
etl::string_stream & shrapnel::selected_preset::operator<< (etl::string_stream & out, const Read & self)
Definition at line 25 of file selected_preset_to_string.cpp.
{
    return out << "{ }";
}
operator<<() [3/4]
etl::string_stream & shrapnel::selected_preset::operator<< (etl::string_stream & out, const SelectedPresetApiMessage & self)
Definition at line 40 of file selected_preset_to_string.cpp.
{
    auto print = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Read>)
        {
            out << "<Read>" << message;
        }
        else if constexpr(std::is_same_v<T, Notify>)
        {
            out << "<Notify>" << message;
        }
        else if constexpr(std::is_same_v<T, Write>)
        {
            out << "<Write>" << message;
        }
        else
        {
            out << "Unknown";
        }
    };
    std::visit(print, self);
    return out;
}
operator<<() [4/4]
etl::string_stream & shrapnel::selected_preset::operator<< (etl::string_stream & out, const Write & self)
Definition at line 35 of file selected_preset_to_string.cpp.
{
    return out << "{ selected_preset=" << self.selectedPresetId << " }";
}
References shrapnel::selected_preset::Write::selectedPresetId.
to_json() [1/5]
template<> rapidjson::Value shrapnel::selected_preset::to_json (rapidjson::Document & document, const Notify & object)
Definition at line 26 of file selected_preset_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    json.AddMember<unsigned int>(
        "selectedPreset", object.selectedPresetId, document.GetAllocator());
    return json;
}
to_json() [2/5]
template<> rapidjson::Value shrapnel::selected_preset::to_json (rapidjson::Document & document, const Notify & object)
Definition at line 26 of file selected_preset_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    json.AddMember<unsigned int>(
        "selectedPreset", object.selectedPresetId, document.GetAllocator());
    return json;
}
to_json() [3/5]
template<> rapidjson::Value shrapnel::selected_preset::to_json (rapidjson::Document & document, const SelectedPresetApiMessage & object)
Definition at line 38 of file selected_preset_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Notify>)
        {
            json = to_json(document, message);
        }
        json.AddMember("messageType",
                       rapidjson::StringRef(get_message_type<T>()),
                       document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References to_json().
to_json() [4/5]
template<> rapidjson::Value shrapnel::selected_preset::to_json (rapidjson::Document & document, const SelectedPresetApiMessage & object)
Definition at line 38 of file selected_preset_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Notify>)
        {
            json = to_json(document, message);
        }
        json.AddMember("messageType",
                       rapidjson::StringRef(get_message_type<T>()),
                       document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References to_json().
to_json() [5/5]
template<typename T > rapidjson::Value shrapnel::selected_preset::to_json (rapidjson::Document & document, const T & object)
Convert object to a JSON value.
Note
The document must not by modified by this function. It is only passed in so that its allocator member can be accessed.
Referenced by to_json().
Variable Documentation
key
constexpr char shrapnel::selected_preset::key[] = "selected_preset" constexpr
Definition at line 26 of file selected_preset_manager.cpp.
Referenced by shrapnel::selected_preset::SelectedPresetManager::get(), shrapnel::persistence::EspStorage::load(), shrapnel::persistence::EspStorage::save(), and shrapnel::selected_preset::SelectedPresetManager::set().