ShrapnelDSP: shrapnel::presets Namespace Reference
shrapnel::presets Namespace Reference
Data Structures
struct Create
struct Delete
struct Initialise
struct Notify
struct ParametersData
struct PresetData
class PresetsManager
struct Update
Typedefs
using id_t = uint32_t
using PresetsApiMessage = std::variant< Initialise, Notify, Create, Update, Delete >
Functions
template<typename T >
ParametersData serialise_live_parameters (T &parameters_service)
template<typename T >
void deserialise_live_parameters (T &parameters_service, shrapnel::presets::ParametersData parameters)
int serialise_parameters (const ParametersData &parameters, std::span< uint8_t > &buffer)
int serialise_preset (const PresetData &preset, std::span< uint8_t > &buffer)
int deserialise_preset (const std::span< uint8_t > &buffer, PresetData &preset)
etl::string_stream & operator<< (etl::string_stream &out, const ParametersData &self)
etl::string_stream & operator<< (etl::string_stream &out, const PresetData &self)
etl::string_stream & operator<< (etl::string_stream &out, const Initialise &self)
etl::string_stream & operator<< (etl::string_stream &out, const Notify &self)
etl::string_stream & operator<< (etl::string_stream &out, const Create &self)
etl::string_stream & operator<< (etl::string_stream &out, const Update &self)
etl::string_stream & operator<< (etl::string_stream &out, const Delete &self)
etl::string_stream & operator<< (etl::string_stream &out, const PresetsApiMessage &self)
template<typename T >
rapidjson::Value to_json (rapidjson::Document &document, const T &object)
Convert object to a JSON value.
template<>
rapidjson::Value to_json (rapidjson::Document &document, const ParametersData &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const PresetData &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Notify &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const PresetsApiMessage &object)
template<typename T >
std::optional< T > from_json (const rapidjson::Value &)
template<>
std::optional< ParametersData > from_json (const rapidjson::Value &json)
template<>
std::optional< PresetData > from_json (const rapidjson::Value &json)
template<>
std::optional< Initialise > from_json (const rapidjson::Value &json)
template<>
std::optional< Create > from_json (const rapidjson::Value &json)
template<>
std::optional< Update > from_json (const rapidjson::Value &json)
template<>
std::optional< PresetsApiMessage > from_json (const rapidjson::Value &json)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const ParametersData &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const PresetData &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Notify &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const PresetsApiMessage &object)
template<>
std::optional< ParametersData > from_json (const rapidjson::Value &json)
template<>
std::optional< PresetData > from_json (const rapidjson::Value &json)
template<>
std::optional< Initialise > from_json (const rapidjson::Value &json)
template<>
std::optional< Create > from_json (const rapidjson::Value &json)
template<>
std::optional< Update > from_json (const rapidjson::Value &json)
template<>
std::optional< Delete > from_json (const rapidjson::Value &json)
template<>
std::optional< PresetsApiMessage > from_json (const rapidjson::Value &json)
template<typename T >
constexpr const char * get_message_type ()
template<>
constexpr const char * get_message_type< Initialise > ()
template<>
constexpr const char * get_message_type< Create > ()
template<>
constexpr const char * get_message_type< Notify > ()
template<>
constexpr const char * get_message_type< Update > ()
template<>
constexpr const char * get_message_type< Delete > ()
Typedef Documentation
id_t
using shrapnel::presets::id_t = typedef uint32_t
Definition at line 26 of file presets.h.
PresetsApiMessage
using shrapnel::presets::PresetsApiMessage = typedef std::variant<Initialise, Notify, Create, Update, Delete>
Definition at line 102 of file presets_api.h.
Function Documentation
deserialise_live_parameters()
template<typename T > void shrapnel::presets::deserialise_live_parameters (T & parameters_service, shrapnel::presets::ParametersData parameters)
Definition at line 59 of file preset_serialisation.h.
{
    parameters_service.update("ampGain", parameters.amp_gain);
    parameters_service.update("ampChannel", parameters.amp_channel);
    parameters_service.update("bass", parameters.bass);
    parameters_service.update("middle", parameters.middle);
    parameters_service.update("treble", parameters.treble);
    parameters_service.update("contour", parameters.contour);
    parameters_service.update("volume", parameters.volume);
    parameters_service.update("noiseGateThreshold", parameters.noise_gate_threshold);
    parameters_service.update("noiseGateHysteresis", parameters.noise_gate_hysteresis);
    parameters_service.update("noiseGateAttack", parameters.noise_gate_attack);
    parameters_service.update("noiseGateHold", parameters.noise_gate_hold);
    parameters_service.update("noiseGateRelease", parameters.noise_gate_release);
    parameters_service.update("noiseGateBypass", parameters.noise_gate_bypass);
    parameters_service.update("chorusRate", parameters.chorus_rate);
    parameters_service.update("chorusDepth", parameters.chorus_depth);
    parameters_service.update("chorusMix", parameters.chorus_mix);
    parameters_service.update("chorusBypass", parameters.chorus_bypass);
    parameters_service.update("wahPosition", parameters.wah_position);
    parameters_service.update("wahVocal", parameters.wah_vocal);
    parameters_service.update("wahBypass", parameters.wah_bypass);
}
References shrapnel::presets::ParametersData::amp_channel, shrapnel::presets::ParametersData::amp_gain, shrapnel::presets::ParametersData::bass, shrapnel::presets::ParametersData::chorus_bypass, shrapnel::presets::ParametersData::chorus_depth, shrapnel::presets::ParametersData::chorus_mix, shrapnel::presets::ParametersData::chorus_rate, shrapnel::presets::ParametersData::contour, shrapnel::presets::ParametersData::middle, shrapnel::presets::ParametersData::noise_gate_attack, shrapnel::presets::ParametersData::noise_gate_bypass, shrapnel::presets::ParametersData::noise_gate_hold, shrapnel::presets::ParametersData::noise_gate_hysteresis, shrapnel::presets::ParametersData::noise_gate_release, shrapnel::presets::ParametersData::noise_gate_threshold, shrapnel::presets::ParametersData::treble, shrapnel::presets::ParametersData::volume, shrapnel::presets::ParametersData::wah_bypass, shrapnel::presets::ParametersData::wah_position, and shrapnel::presets::ParametersData::wah_vocal.
deserialise_preset()
int shrapnel::presets::deserialise_preset (const std::span< uint8_t > & buffer, PresetData & preset) inline
Definition at line 171 of file preset_serialisation.h.
{
    auto unpacked = preset__unpack(nullptr, buffer.size(), buffer.data());
    if(unpacked == nullptr)
    {
        return -1;
    }
    preset = PresetData{
        .name{unpacked->name},
        .parameters{
            .amp_gain = unpacked->parameters->amp_gain / 1000.f,
            .amp_channel = unpacked->parameters->amp_channel / 1000.f,
            .bass = unpacked->parameters->bass / 1000.f,
            .middle = unpacked->parameters->middle / 1000.f,
            .treble = unpacked->parameters->treble / 1000.f,
            .contour = unpacked->parameters->contour / 1000.f,
            .volume = unpacked->parameters->volume / 1000.f,
            .noise_gate_threshold =
                unpacked->parameters->noise_gate_threshold / 1000.f,
            .noise_gate_hysteresis =
                unpacked->parameters->noise_gate_hysteresis / 1000.f,
            .noise_gate_attack =
                unpacked->parameters->noise_gate_attack / 1000.f,
            .noise_gate_hold = unpacked->parameters->noise_gate_hold / 1000.f,
            .noise_gate_release =
                unpacked->parameters->noise_gate_release / 1000.f,
            .noise_gate_bypass =
                unpacked->parameters->noise_gate_bypass / 1000.f,
            .chorus_rate = unpacked->parameters->chorus_rate / 1000.f,
            .chorus_depth = unpacked->parameters->chorus_depth / 1000.f,
            .chorus_mix = unpacked->parameters->chorus_mix / 1000.f,
            .chorus_bypass = unpacked->parameters->chorus_bypass / 1000.f,
            .wah_position = unpacked->parameters->wah_position / 1000.f,
            .wah_vocal = unpacked->parameters->wah_vocal / 1000.f,
            .wah_bypass = unpacked->parameters->wah_bypass / 1000.f,
        },
    };
    preset__free_unpacked(unpacked, nullptr);
    return 0;
}
References shrapnel::presets::PresetData::name, preset__free_unpacked(), and preset__unpack().
Referenced by shrapnel::presets::PresetsManager::read().
from_json() [1/14]
template<typename T > std::optional< T > shrapnel::presets::from_json (const rapidjson::Value &)
from_json() [2/14]
template<> std::optional< ParametersData > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
References shrapnel::presets::ParametersData::amp_gain, preset_parameters__free_unpacked(), and preset_parameters__unpack().
from_json() [3/14]
template<> std::optional< PresetData > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
from_json() [4/14]
template<> std::optional< Initialise > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
from_json() [5/14]
template<> std::optional< Create > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
from_json() [6/14]
template<> std::optional< Update > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
from_json() [7/14]
template<> std::optional< PresetsApiMessage > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
References get_message_type< Create >(), get_message_type< Delete >(), get_message_type< Initialise >(), and get_message_type< Update >().
from_json() [8/14]
template<> std::optional< ParametersData > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 31 of file presets_json_parser.cpp.
{
    using base64_codec = cppcodec::base64_rfc4648;
    if(!json.IsString())
    {
        return std::nullopt;
    }
    std::array<uint8_t, 100> buffer{};
    if(base64_codec::decoded_max_size(json.GetStringLength()) > buffer.size())
    {
        return std::nullopt;
    }
    size_t decoded_size = 0;
    auto error = base64_codec::decode(buffer.data(),
                                      buffer.size(),
                                      json.GetString(),
                                      json.GetStringLength(),
                                      decoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return std::nullopt;
    }
    auto unpacked =
        preset_parameters__unpack(nullptr, decoded_size, buffer.data());
    if(unpacked == nullptr)
    {
        return std::nullopt;
    }
    auto out = ParametersData{
        .amp_gain = unpacked->amp_gain / 1000.f,
        .amp_channel = unpacked->amp_channel / 1000.f,
        .bass = unpacked->bass / 1000.f,
        .middle = unpacked->middle / 1000.f,
        .treble = unpacked->treble / 1000.f,
        .contour = unpacked->contour / 1000.f,
        .volume = unpacked->volume / 1000.f,
        .noise_gate_threshold = unpacked->noise_gate_threshold / 1000.f,
        .noise_gate_hysteresis = unpacked->noise_gate_hysteresis / 1000.f,
        .noise_gate_attack = unpacked->noise_gate_attack / 1000.f,
        .noise_gate_hold = unpacked->noise_gate_hold / 1000.f,
        .noise_gate_release = unpacked->noise_gate_release / 1000.f,
        .noise_gate_bypass = unpacked->noise_gate_bypass / 1000.f,
        .chorus_rate = unpacked->chorus_rate / 1000.f,
        .chorus_depth = unpacked->chorus_depth / 1000.f,
        .chorus_mix = unpacked->chorus_mix / 1000.f,
        .chorus_bypass = unpacked->chorus_bypass / 1000.f,
        .wah_position = unpacked->wah_position / 1000.f,
        .wah_vocal = unpacked->wah_vocal / 1000.f,
        .wah_bypass = unpacked->wah_bypass / 1000.f,
    };
    preset_parameters__free_unpacked(unpacked, nullptr);
    return out;
}
from_json() [9/14]
template<> std::optional< PresetData > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 92 of file presets_json_parser.cpp.
{
    auto name = json.FindMember("name");
    if(name == json.MemberEnd() || !name->value.IsString())
        return std::nullopt;
    auto parameters_json = json.FindMember("parameters");
    if(parameters_json == json.MemberEnd())
        return std::nullopt;
    auto parameters = from_json<ParametersData>(parameters_json->value);
    if(!parameters.has_value())
        return std::nullopt;
    return {{
        .name{name->value.GetString()},
        .parameters{*parameters},
    }};
}
from_json() [10/14]
template<> std::optional< Initialise > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 112 of file presets_json_parser.cpp.
{
    return Initialise();
}
from_json() [11/14]
template<> std::optional< Create > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 118 of file presets_json_parser.cpp.
{
    auto preset_json = json.FindMember("preset");
    if(preset_json == json.MemberEnd())
        return std::nullopt;
    auto preset = from_json<PresetData>(preset_json->value);
    if(!preset.has_value())
        return std::nullopt;
    return {{.preset = *preset}};
}
from_json() [12/14]
template<> std::optional< Update > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 132 of file presets_json_parser.cpp.
{
    auto id_json = json.FindMember("id");
    if(id_json == json.MemberEnd())
        return std::nullopt;
    if(!id_json->value.IsUint())
        return std::nullopt;
    auto preset_json = json.FindMember("preset");
    if(preset_json == json.MemberEnd())
        return std::nullopt;
    auto preset = from_json<PresetData>(preset_json->value);
    if(!preset.has_value())
        return std::nullopt;
    return {{.id{id_json->value.GetUint()}, .preset = *preset}};
}
from_json() [13/14]
template<> std::optional< Delete > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 151 of file presets_json_parser.cpp.
{
    auto id_json = json.FindMember("id");
    if(id_json == json.MemberEnd())
        return std::nullopt;
    if(!id_json->value.IsUint())
        return std::nullopt;
    return {{.id{id_json->value.GetUint()}}};
}
from_json() [14/14]
template<> std::optional< PresetsApiMessage > shrapnel::presets::from_json (const rapidjson::Value & json)
Definition at line 164 of file presets_json_parser.cpp.
{
    constexpr char TAG[] = "PresetsApiMessage from_json";
    auto message_type_member = json.FindMember("messageType");
    if(message_type_member == json.MemberEnd())
    {
        ESP_LOGE(TAG, "messageType is missing");
        goto error;
    }
    if(!message_type_member->value.IsString())
    {
        ESP_LOGE(TAG, "messageType is not string");
        goto error;
    }
    {
        const etl::map<std::string,
                       std::function<std::optional<PresetsApiMessage>()>,
                       4>
            lut{
                {get_message_type<Initialise>(),
                 [&] { return from_json<Initialise>(json); }},
                {get_message_type<Create>(),
                 [&] { return from_json<Create>(json); }},
                {get_message_type<Update>(),
                 [&] { return from_json<Update>(json); }},
                {get_message_type<Delete>(),
                 [&] { return from_json<Delete>(json); }},
            };
        const char *message_type = message_type_member->value.GetString();
        if(auto f = lut.find(message_type); f != lut.end())
        {
            return f->second();
        }
    }
error:
    return std::nullopt;
}
References shrapnel::presets::ParametersData::amp_gain, get_message_type< Create >(), get_message_type< Delete >(), get_message_type< Initialise >(), get_message_type< Update >(), preset_parameters__free_unpacked(), and preset_parameters__unpack().
get_message_type()
template<typename T > constexpr const char * shrapnel::presets::get_message_type () constexpr
get_message_type< Create >()
template<> constexpr const char * shrapnel::presets::get_message_type< Create > () constexpr
Definition at line 36 of file presets_message_type.h.
{
    return "Presets::create";
}
Referenced by from_json().
get_message_type< Delete >()
template<> constexpr const char * shrapnel::presets::get_message_type< Delete > () constexpr
Definition at line 54 of file presets_message_type.h.
{
    return "Presets::delete";
}
Referenced by from_json().
get_message_type< Initialise >()
template<> constexpr const char * shrapnel::presets::get_message_type< Initialise > () constexpr
Definition at line 30 of file presets_message_type.h.
{
    return "Presets::initialise";
}
Referenced by from_json().
get_message_type< Notify >()
template<> constexpr const char * shrapnel::presets::get_message_type< Notify > () constexpr
Definition at line 42 of file presets_message_type.h.
{
    return "Presets::notify";
}
get_message_type< Update >()
template<> constexpr const char * shrapnel::presets::get_message_type< Update > () constexpr
Definition at line 48 of file presets_message_type.h.
{
    return "Presets::update";
}
Referenced by from_json().
operator<<() [1/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const Create & self)
Definition at line 47 of file presets_to_string.cpp.
{
    return out << "{ preset=" << self.preset << " }";
}
References shrapnel::presets::Create::preset.
operator<<() [2/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const Delete & self)
Definition at line 57 of file presets_to_string.cpp.
{
    return out << "{ id=" << self.id << " }";
}
References shrapnel::presets::Delete::id.
operator<<() [3/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const Initialise & self)
Definition at line 37 of file presets_to_string.cpp.
{
    return out << "{ }";
}
operator<<() [4/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const Notify & self)
Definition at line 42 of file presets_to_string.cpp.
{
    return out << "{ id=" << self.id << " preset=" << self.preset << " }";
}
References shrapnel::presets::Notify::id, and shrapnel::presets::Notify::preset.
operator<<() [5/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const ParametersData & self)
Definition at line 25 of file presets_to_string.cpp.
{
    return out << "{ amp_gain=" << self.amp_gain << " }";
}
References shrapnel::presets::ParametersData::amp_gain.
operator<<() [6/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const PresetData & self)
Definition at line 31 of file presets_to_string.cpp.
{
    return out << "{ name=" << self.name << "parameters=" << self.parameters
               << " }";
}
References shrapnel::presets::PresetData::name, and shrapnel::presets::PresetData::parameters.
operator<<() [7/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const PresetsApiMessage & self)
Definition at line 62 of file presets_to_string.cpp.
{
    auto print = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Initialise>)
        {
            out << "<Initialise>" << message;
        }
        else if constexpr(std::is_same_v<T, Notify>)
        {
            out << "<Notify>" << message;
        }
        else if constexpr(std::is_same_v<T, Create>)
        {
            out << "<Create>" << message;
        }
        else if constexpr(std::is_same_v<T, Update>)
        {
            out << "<Update>" << message;
        }
        else if constexpr(std::is_same_v<T, Delete>)
        {
            out << "<Delete>" << message;
        }
        else
        {
            out << "Unknown";
        }
    };
    std::visit(print, self);
    return out;
}
operator<<() [8/8]
etl::string_stream & shrapnel::presets::operator<< (etl::string_stream & out, const Update & self)
Definition at line 52 of file presets_to_string.cpp.
{
    return out << "{ id= " << self.id << " preset=" << self.preset << " }";
}
References shrapnel::presets::Update::id, and shrapnel::presets::Update::preset.
serialise_live_parameters()
template<typename T > ParametersData shrapnel::presets::serialise_live_parameters (T & parameters_service)
Definition at line 30 of file preset_serialisation.h.
{
    shrapnel::presets::ParametersData parameters{
        .amp_gain = parameters_service.get("ampGain"),
        .amp_channel = parameters_service.get("ampChannel"),
        .bass = parameters_service.get("bass"),
        .middle = parameters_service.get("middle"),
        .treble = parameters_service.get("treble"),
        .contour = parameters_service.get("contour"),
        .volume = parameters_service.get("volume"),
        .noise_gate_threshold = parameters_service.get("noiseGateThreshold"),
        .noise_gate_hysteresis = parameters_service.get("noiseGateHysteresis"),
        .noise_gate_attack = parameters_service.get("noiseGateAttack"),
        .noise_gate_hold = parameters_service.get("noiseGateHold"),
        .noise_gate_release = parameters_service.get("noiseGateRelease"),
        .noise_gate_bypass = parameters_service.get("noiseGateBypass"),
        .chorus_rate = parameters_service.get("chorusRate"),
        .chorus_depth = parameters_service.get("chorusDepth"),
        .chorus_mix = parameters_service.get("chorusMix"),
        .chorus_bypass = parameters_service.get("chorusBypass"),
        .wah_position = parameters_service.get("wahPosition"),
        .wah_vocal = parameters_service.get("wahVocal"),
        .wah_bypass = parameters_service.get("wahBypass"),
    };
    return parameters;
}
References shrapnel::presets::ParametersData::amp_gain.
serialise_parameters()
int shrapnel::presets::serialise_parameters (const ParametersData & parameters, std::span< uint8_t > & buffer) inline
Definition at line 84 of file preset_serialisation.h.
{
    struct PresetParameters preset = PRESET_PARAMETERS__INIT;
    preset_parameters__init(&preset);
    preset.amp_gain = parameters.amp_gain * 1000;
    preset.amp_channel = parameters.amp_channel * 1000;
    preset.bass = parameters.bass * 1000;
    preset.middle = parameters.middle * 1000;
    preset.treble = parameters.treble * 1000;
    preset.contour = parameters.contour * 1000;
    preset.volume = parameters.volume * 1000;
    preset.noise_gate_threshold = parameters.noise_gate_threshold * 1000;
    preset.noise_gate_hysteresis = parameters.noise_gate_hysteresis * 1000;
    preset.noise_gate_attack = parameters.noise_gate_attack * 1000;
    preset.noise_gate_hold = parameters.noise_gate_hold * 1000;
    preset.noise_gate_release = parameters.noise_gate_release * 1000;
    preset.noise_gate_bypass = parameters.noise_gate_bypass * 1000;
    preset.chorus_rate = parameters.chorus_rate * 1000;
    preset.chorus_depth = parameters.chorus_depth * 1000;
    preset.chorus_mix = parameters.chorus_mix * 1000;
    preset.chorus_bypass = parameters.chorus_bypass * 1000;
    preset.wah_position = parameters.wah_position * 1000;
    preset.wah_vocal = parameters.wah_vocal * 1000;
    preset.wah_bypass = parameters.wah_bypass * 1000;
    auto packed_size = preset_parameters__get_packed_size(&preset);
    if(packed_size > buffer.size())
    {
        return -1;
    }
    preset_parameters__pack(&preset, buffer.data());
    buffer = buffer.subspan(0, packed_size);
    return 0;
}
References shrapnel::presets::ParametersData::amp_channel, PresetParameters::amp_channel, shrapnel::presets::ParametersData::amp_gain, PresetParameters::amp_gain, shrapnel::presets::ParametersData::bass, PresetParameters::bass, shrapnel::presets::ParametersData::chorus_bypass, PresetParameters::chorus_bypass, shrapnel::presets::ParametersData::chorus_depth, PresetParameters::chorus_depth, shrapnel::presets::ParametersData::chorus_mix, PresetParameters::chorus_mix, shrapnel::presets::ParametersData::chorus_rate, PresetParameters::chorus_rate, shrapnel::presets::ParametersData::contour, PresetParameters::contour, shrapnel::presets::ParametersData::middle, PresetParameters::middle, shrapnel::presets::ParametersData::noise_gate_attack, PresetParameters::noise_gate_attack, shrapnel::presets::ParametersData::noise_gate_bypass, PresetParameters::noise_gate_bypass, shrapnel::presets::ParametersData::noise_gate_hold, PresetParameters::noise_gate_hold, shrapnel::presets::ParametersData::noise_gate_hysteresis, PresetParameters::noise_gate_hysteresis, shrapnel::presets::ParametersData::noise_gate_release, PresetParameters::noise_gate_release, shrapnel::presets::ParametersData::noise_gate_threshold, PresetParameters::noise_gate_threshold, preset_parameters__get_packed_size(), preset_parameters__init(), preset_parameters__pack(), shrapnel::presets::ParametersData::treble, PresetParameters::treble, shrapnel::presets::ParametersData::volume, PresetParameters::volume, shrapnel::presets::ParametersData::wah_bypass, PresetParameters::wah_bypass, shrapnel::presets::ParametersData::wah_position, PresetParameters::wah_position, shrapnel::presets::ParametersData::wah_vocal, and PresetParameters::wah_vocal.
Referenced by to_json().
serialise_preset()
int shrapnel::presets::serialise_preset (const PresetData & preset, std::span< uint8_t > & buffer) inline
Definition at line 122 of file preset_serialisation.h.
{
    struct PresetParameters parameters_proto = PRESET_PARAMETERS__INIT;
    preset_parameters__init(&parameters_proto);
    parameters_proto.amp_gain = preset.parameters.amp_gain * 1000;
    parameters_proto.amp_channel = preset.parameters.amp_channel * 1000;
    parameters_proto.bass = preset.parameters.bass * 1000;
    parameters_proto.middle = preset.parameters.middle * 1000;
    parameters_proto.treble = preset.parameters.treble * 1000;
    parameters_proto.contour = preset.parameters.contour * 1000;
    parameters_proto.volume = preset.parameters.volume * 1000;
    parameters_proto.noise_gate_threshold =
        preset.parameters.noise_gate_threshold * 1000;
    parameters_proto.noise_gate_hysteresis =
        preset.parameters.noise_gate_hysteresis * 1000;
    parameters_proto.noise_gate_attack =
        preset.parameters.noise_gate_attack * 1000;
    parameters_proto.noise_gate_hold = preset.parameters.noise_gate_hold * 1000;
    parameters_proto.noise_gate_release =
        preset.parameters.noise_gate_release * 1000;
    parameters_proto.noise_gate_bypass =
        preset.parameters.noise_gate_bypass * 1000;
    parameters_proto.chorus_rate = preset.parameters.chorus_rate * 1000;
    parameters_proto.chorus_depth = preset.parameters.chorus_depth * 1000;
    parameters_proto.chorus_mix = preset.parameters.chorus_mix * 1000;
    parameters_proto.chorus_bypass = preset.parameters.chorus_bypass * 1000;
    parameters_proto.wah_position = preset.parameters.wah_position * 1000;
    parameters_proto.wah_vocal = preset.parameters.wah_vocal * 1000;
    parameters_proto.wah_bypass = preset.parameters.wah_bypass * 1000;
    struct Preset preset_proto = PRESET__INIT;
    preset__init(&preset_proto);
    preset_proto.name = const_cast<char *>(preset.name.c_str());
    preset_proto.parameters = &parameters_proto;
    auto packed_size = preset__get_packed_size(&preset_proto);
    if(packed_size > buffer.size())
    {
        return -1;
    }
    preset__pack(&preset_proto, buffer.data());
    buffer = buffer.subspan(0, packed_size);
    return 0;
}
References shrapnel::presets::ParametersData::amp_channel, PresetParameters::amp_channel, shrapnel::presets::ParametersData::amp_gain, PresetParameters::amp_gain, shrapnel::presets::ParametersData::bass, PresetParameters::bass, shrapnel::presets::ParametersData::chorus_bypass, PresetParameters::chorus_bypass, shrapnel::presets::ParametersData::chorus_depth, PresetParameters::chorus_depth, shrapnel::presets::ParametersData::chorus_mix, PresetParameters::chorus_mix, shrapnel::presets::ParametersData::chorus_rate, PresetParameters::chorus_rate, shrapnel::presets::ParametersData::contour, PresetParameters::contour, shrapnel::presets::ParametersData::middle, PresetParameters::middle, shrapnel::presets::PresetData::name, Preset::name, shrapnel::presets::ParametersData::noise_gate_attack, PresetParameters::noise_gate_attack, shrapnel::presets::ParametersData::noise_gate_bypass, PresetParameters::noise_gate_bypass, shrapnel::presets::ParametersData::noise_gate_hold, PresetParameters::noise_gate_hold, shrapnel::presets::ParametersData::noise_gate_hysteresis, PresetParameters::noise_gate_hysteresis, shrapnel::presets::ParametersData::noise_gate_release, PresetParameters::noise_gate_release, shrapnel::presets::ParametersData::noise_gate_threshold, PresetParameters::noise_gate_threshold, shrapnel::presets::PresetData::parameters, Preset::parameters, preset__get_packed_size(), preset__init(), preset__pack(), preset_parameters__init(), shrapnel::presets::ParametersData::treble, PresetParameters::treble, shrapnel::presets::ParametersData::volume, PresetParameters::volume, shrapnel::presets::ParametersData::wah_bypass, PresetParameters::wah_bypass, shrapnel::presets::ParametersData::wah_position, PresetParameters::wah_position, shrapnel::presets::ParametersData::wah_vocal, and PresetParameters::wah_vocal.
Referenced by shrapnel::presets::PresetsManager::create(), and shrapnel::presets::PresetsManager::update().
to_json() [1/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const Notify & object)
Definition at line 86 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    json.AddMember<unsigned int>("id", object.id, document.GetAllocator());
    json.AddMember(
        "preset", to_json(document, object.preset), document.GetAllocator());
    return json;
}
References to_json().
to_json() [2/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const Notify & object)
Definition at line 86 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    json.AddMember<unsigned int>("id", object.id, document.GetAllocator());
    json.AddMember(
        "preset", to_json(document, object.preset), document.GetAllocator());
    return json;
}
References to_json().
to_json() [3/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const ParametersData & object)
Definition at line 32 of file presets_json_builder.cpp.
{
    uint8_t buffer[100] = {};
    auto data = std::span<uint8_t, std::dynamic_extent>(buffer);
    int rc = serialise_parameters(object, data);
    if(rc != 0)
    {
        return {/* null */};
    }
    using base64_codec = cppcodec::base64_rfc4648;
    std::array<char, 200> base64_buffer;
    auto encoded_size = base64_codec::encoded_size(data.size());
    if(encoded_size > base64_buffer.size())
    {
        return {/* null */};
    }
    auto error = base64_codec::encode(base64_buffer.data(),
                                      base64_buffer.size(),
                                      data.data(),
                                      data.size(),
                                      encoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return {/* null */};
    }
    auto json = rapidjson::Value{};
    json.SetString(base64_buffer.data(), encoded_size, document.GetAllocator());
    return json;
}
References serialise_parameters().
to_json() [4/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const ParametersData & object)
Definition at line 32 of file presets_json_builder.cpp.
{
    uint8_t buffer[100] = {};
    auto data = std::span<uint8_t, std::dynamic_extent>(buffer);
    int rc = serialise_parameters(object, data);
    if(rc != 0)
    {
        return {/* null */};
    }
    using base64_codec = cppcodec::base64_rfc4648;
    std::array<char, 200> base64_buffer;
    auto encoded_size = base64_codec::encoded_size(data.size());
    if(encoded_size > base64_buffer.size())
    {
        return {/* null */};
    }
    auto error = base64_codec::encode(base64_buffer.data(),
                                      base64_buffer.size(),
                                      data.data(),
                                      data.size(),
                                      encoded_size);
    if(!std::holds_alternative<std::monostate>(error))
    {
        return {/* null */};
    }
    auto json = rapidjson::Value{};
    json.SetString(base64_buffer.data(), encoded_size, document.GetAllocator());
    return json;
}
References serialise_parameters().
to_json() [5/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const PresetData & object)
Definition at line 70 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value name{object.name.c_str(), document.GetAllocator()};
    json.AddMember("name", name, document.GetAllocator());
    json.AddMember("parameters",
                   to_json(document, object.parameters),
                   document.GetAllocator());
    return json;
}
References to_json().
to_json() [6/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const PresetData & object)
Definition at line 70 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value name{object.name.c_str(), document.GetAllocator()};
    json.AddMember("name", name, document.GetAllocator());
    json.AddMember("parameters",
                   to_json(document, object.parameters),
                   document.GetAllocator());
    return json;
}
References to_json().
to_json() [7/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const PresetsApiMessage & object)
Definition at line 99 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Notify>)
        {
            json = to_json(document, message);
        }
        json.AddMember("messageType",
                       rapidjson::StringRef(get_message_type<T>()),
                       document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References to_json().
to_json() [8/9]
template<> rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const PresetsApiMessage & object)
Definition at line 99 of file presets_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message)
    {
        using T = std::decay_t<decltype(message)>;
        if constexpr(std::is_same_v<T, Notify>)
        {
            json = to_json(document, message);
        }
        json.AddMember("messageType",
                       rapidjson::StringRef(get_message_type<T>()),
                       document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References to_json().
to_json() [9/9]
template<typename T > rapidjson::Value shrapnel::presets::to_json (rapidjson::Document & document, const T & object)
Convert object to a JSON value.
Note
The document must not by modified by this function. It is only passed in so that its allocator member can be accessed.
Referenced by to_json().