ShrapnelDSP: shrapnel::midi Namespace Reference
shrapnel::midi Namespace Reference
Data Structures
struct CreateRequest
struct CreateResponse
class Decoder
class EspMidiUart
struct GetRequest
struct GetResponse
struct Mapping
class MappingManager
struct Message
class MidiUartBase
struct Remove
struct Update
Typedefs
using MappingObserver = etl::observer< const Mapping::id_t & >
using MappingApiMessage = std::variant< GetRequest, GetResponse, CreateRequest, CreateResponse, Update, Remove >
Enumerations
enum MessageType { NOTE_OFF = 0x80 , NOTE_ON = 0x90 , CONTROL_CHANGE = 0xB0 , PROGRAM_CHANGE = 0xC0 }
Functions
etl::string_stream & operator<< (etl::string_stream &out, const Mapping &self)
etl::string_stream & operator<< (etl::string_stream &out, const GetRequest &self)
etl::string_stream & operator<< (etl::string_stream &out, const GetResponse &self)
etl::string_stream & operator<< (etl::string_stream &out, const CreateRequest &self)
etl::string_stream & operator<< (etl::string_stream &out, const CreateResponse &self)
etl::string_stream & operator<< (etl::string_stream &out, const Update &self)
etl::string_stream & operator<< (etl::string_stream &out, const Remove &self)
etl::string_stream & operator<< (etl::string_stream &out, const MappingApiMessage &self)
template<typename T >
rapidjson::Value to_json (rapidjson::Document &document, const T &object)
Convert object to a JSON value.
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Mapping &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Mapping::id_t &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const std::pair< Mapping::id_t, Mapping > &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const CreateResponse &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const GetResponse &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const MappingApiMessage &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const etl::imap< Mapping::id_t, Mapping > &object)
template<typename T >
std::optional< T > from_json (const rapidjson::Value &)
template<>
std::optional< GetRequest > from_json (const rapidjson::Value &json)
template<>
std::optional< Mapping > from_json (const rapidjson::Value &json)
template<>
std::optional< std::pair< Mapping::id_t, Mapping > > from_json (const rapidjson::Value &json)
template<>
std::optional< CreateRequest > from_json (const rapidjson::Value &json)
template<>
std::optional< Update > from_json (const rapidjson::Value &json)
template<>
std::optional< Remove > from_json (const rapidjson::Value &json)
template<>
std::optional< Mapping::id_t > from_json (const rapidjson::Value &json)
template<>
std::optional< MappingApiMessage > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<typename MapType >
requires std::derived_from<MapType, etl::imap<Mapping::id_t, Mapping>>
std::optional< MapType > from_json (const rapidjson::Value &json)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Mapping &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const Mapping::id_t &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const std::pair< Mapping::id_t, Mapping > &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const CreateResponse &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const GetResponse &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const MappingApiMessage &object)
template<>
rapidjson::Value to_json (rapidjson::Document &document, const etl::imap< Mapping::id_t, Mapping > &object)
static int parse_uuid (Mapping::id_t &uuid, const char *string)
template<>
std::optional< GetRequest > from_json (const rapidjson::Value &)
Convert the message into a object representing it.
template<>
std::optional< Mapping > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< std::pair< Mapping::id_t, Mapping > > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< CreateRequest > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< Update > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< Remove > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< MappingApiMessage > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<>
std::optional< Mapping::id_t > from_json (const rapidjson::Value &json)
Convert the message into a object representing it.
template<typename T >
constexpr const char * get_message_type ()
template<>
constexpr const char * get_message_type< GetRequest > ()
template<>
constexpr const char * get_message_type< GetResponse > ()
template<>
constexpr const char * get_message_type< CreateRequest > ()
template<>
constexpr const char * get_message_type< CreateResponse > ()
template<>
constexpr const char * get_message_type< Update > ()
template<>
constexpr const char * get_message_type< Remove > ()
template<>
std::optional< float > from_json (const rapidjson::Value &value)
Convert the message into a object representing it.
template<>
rapidjson::Value to_json (rapidjson::Document &document, const float &object)
Variables
int constexpr CC_VALUE_MAX = 127
Typedef Documentation
MappingApiMessage
using shrapnel::midi::MappingApiMessage = typedef std::variant<GetRequest, GetResponse, CreateRequest, CreateResponse, Update, Remove>
Definition at line 57 of file midi_mapping_api.h.
MappingObserver
using shrapnel::midi::MappingObserver = typedef etl::observer<const Mapping::id_t&>
Definition at line 213 of file midi_mapping.h.
Enumeration Type Documentation
MessageType
enum shrapnel::midi::MessageType
Enumerator
NOTE_OFF
NOTE_ON
CONTROL_CHANGE
PROGRAM_CHANGE
Definition at line 33 of file midi_protocol.h.
                 {
    NOTE_OFF = 0x80,
    NOTE_ON = 0x90,
    CONTROL_CHANGE = 0xB0,
    PROGRAM_CHANGE = 0xC0,
};
Function Documentation
from_json() [1/19]
template<typename T > std::optional< T > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 72 of file midi_mapping_json_parser.h.
{
    constexpr char TAG[] = "etl::map<Mapping::id_t, Mapping> from_json";
    MapType out;
    if(!json.IsObject())
    {
        ESP_LOGE(TAG, "map is not object");
        return std::nullopt;
    }
    if(json.MemberCount() > MapType::MAX_SIZE)
    {
        ESP_LOGE(TAG, "too many elements in json");
        return std::nullopt;
    }
    for (const auto &entry : json.GetObject())
    {
        auto mapping = from_json<Mapping>(entry.value);
        if(!mapping.has_value())
        {
            ESP_LOGE(TAG, "failed to get mapping");
            return std::nullopt;
        }
        auto id = from_json<Mapping::id_t>(entry.name);
        if(!id.has_value())
        {
            ESP_LOGE(TAG, "failed to get uuid");
            return std::nullopt;
        }
        out[*id] = *mapping;
    }
    return out;
}
References shrapnel::parameters::TAG.
Referenced by shrapnel::app_main().
from_json() [2/19]
template<> std::optional< GetRequest > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [3/19]
template<> std::optional< GetRequest > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [4/19]
template<> std::optional< Mapping > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [5/19]
template<> std::optional< std::pair< Mapping::id_t, Mapping > > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [6/19]
template<> std::optional< CreateRequest > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [7/19]
template<> std::optional< Update > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [8/19]
template<> std::optional< Remove > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [9/19]
template<> std::optional< Mapping::id_t > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
from_json() [10/19]
template<> std::optional< MappingApiMessage > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 29 of file midi_mapping_json_parser.cpp.
{
    return GetRequest();
}
References get_message_type< CreateRequest >(), get_message_type< GetRequest >(), get_message_type< Remove >(), get_message_type< Update >(), shrapnel::midi::Mapping::PARAMETER, parse_uuid(), shrapnel::parameters::TAG, and shrapnel::midi::Mapping::TOGGLE.
from_json() [11/19]
template<typename MapType > requires std::derived_from<MapType, etl::imap<Mapping::id_t, Mapping>> std::optional< MapType > shrapnel::midi::from_json (const rapidjson::Value & json)
Definition at line 72 of file midi_mapping_json_parser.h.
{
    constexpr char TAG[] = "etl::map<Mapping::id_t, Mapping> from_json";
    MapType out;
    if(!json.IsObject())
    {
        ESP_LOGE(TAG, "map is not object");
        return std::nullopt;
    }
    if(json.MemberCount() > MapType::MAX_SIZE)
    {
        ESP_LOGE(TAG, "too many elements in json");
        return std::nullopt;
    }
    for (const auto &entry : json.GetObject())
    {
        auto mapping = from_json<Mapping>(entry.value);
        if(!mapping.has_value())
        {
            ESP_LOGE(TAG, "failed to get mapping");
            return std::nullopt;
        }
        auto id = from_json<Mapping::id_t>(entry.name);
        if(!id.has_value())
        {
            ESP_LOGE(TAG, "failed to get uuid");
            return std::nullopt;
        }
        out[*id] = *mapping;
    }
    return out;
}
References shrapnel::parameters::TAG.
Referenced by shrapnel::app_main().
from_json() [12/19]
template<> std::optional< Mapping > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 35 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "Mapping from_json";
    auto midi_channel = json.FindMember("midi_channel");
    if(midi_channel == json.MemberEnd()) {
        ESP_LOGE(TAG, "midi_channel is missing");
        return std::nullopt;
    }
    auto cc_number = json.FindMember("cc_number");
    if(cc_number == json.MemberEnd()) {
        ESP_LOGE(TAG, "cc_number is missing");
        return std::nullopt;
    }
    Mapping::Mode mode = Mapping::Mode::PARAMETER;
    auto mode_json = json.FindMember("mode");
    if(mode_json == json.MemberEnd())
    {
        ESP_LOGW(TAG, "mode is missing, setting it to PARAMETER");
    }
    else
    {
        if(!mode_json->value.IsString())
        {
            ESP_LOGE(TAG, "mode is not string");
            return std::nullopt;
        }
        static const etl::map<etl::string_view, Mapping::Mode, 2> lut{
            {"parameter", Mapping::Mode::PARAMETER},
            {"toggle", Mapping::Mode::TOGGLE},
        };
        if(!lut.contains(mode_json->value.GetString()))
        {
            ESP_LOGE(TAG, "unknown mode %s", mode_json->value.GetString());
            return std::nullopt;
        }
        mode = lut.at(mode_json->value.GetString());
    }
    auto parameter_id = json.FindMember("parameter_id");
    if(parameter_id == json.MemberEnd()) {
        ESP_LOGE(TAG, "parameter_id is missing");
        return std::nullopt;
    }
    // TODO range check before narrowing conversion to uint8_t
    return Mapping{static_cast<uint8_t>(midi_channel->value.GetInt()),
                   static_cast<uint8_t>(cc_number->value.GetInt()),
                   mode,
                   parameters::id_t(parameter_id->value.GetString())};
}
References shrapnel::midi::Mapping::PARAMETER, shrapnel::parameters::TAG, and shrapnel::midi::Mapping::TOGGLE.
from_json() [13/19]
template<> std::optional< std::pair< Mapping::id_t, Mapping > > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 91 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "pair<mapping::id, mapping> from_json";
    if(!json.IsObject())
    {
        ESP_LOGE(TAG, "mapping is not object");
        return std::nullopt;
    }
    // XXX There should be only one key, so we take the first one
    //     and ignore the rest
    auto mapping_entry_member = json.GetObject().begin();
    if(mapping_entry_member == json.GetObject().end())
    {
        ESP_LOGE(TAG, "mapping is empty");
        return std::nullopt;
    }
    auto &mapping_id = mapping_entry_member->name;
    auto &mapping_entry = mapping_entry_member->value;
    auto mapping = from_json<Mapping>(mapping_entry);
    if(!mapping.has_value()) {
        ESP_LOGE(TAG, "failed to get mapping");
        return std::nullopt;
    }
    auto id = from_json<Mapping::id_t>(mapping_id);
    if(!id.has_value()) {
        ESP_LOGE(TAG, "failed to get id");
        return std::nullopt;
    }
    return {{ *id, *mapping }};
}
References shrapnel::parameters::TAG.
from_json() [14/19]
template<> std::optional< CreateRequest > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 130 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "Update from_json";
    auto mapping_member = json.FindMember("mapping");
    if(mapping_member == json.MemberEnd()) {
        ESP_LOGE(TAG, "mapping is missing");
        return std::nullopt;
    }
    auto mapping = from_json<std::pair<Mapping::id_t, Mapping>>(mapping_member->value);
    return CreateRequest{*mapping};
}
References shrapnel::parameters::TAG.
from_json() [15/19]
template<> std::optional< Update > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 145 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "Update from_json";
    auto mapping_member = json.FindMember("mapping");
    if(mapping_member == json.MemberEnd()) {
        ESP_LOGE(TAG, "mapping is missing");
        return std::nullopt;
    }
    auto mapping = from_json<std::pair<Mapping::id_t, Mapping>>(mapping_member->value);
    return Update{*mapping};
}
References shrapnel::parameters::TAG.
from_json() [16/19]
template<> std::optional< Remove > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 160 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "Remove from_json";
    auto id_member = json.FindMember("id");
    if(id_member == json.MemberEnd()) {
        ESP_LOGE(TAG, "id is missing");
        return std::nullopt;
    }
    auto uuid = from_json<Mapping::id_t>(id_member->value);
    if(!uuid.has_value())
    {
        ESP_LOGE(TAG, "Failed to parse UUID");
        return std::nullopt;
    }
    return {{*uuid}};
}
References shrapnel::parameters::TAG.
from_json() [17/19]
template<> std::optional< MappingApiMessage > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 180 of file midi_mapping_json_parser.cpp.
{
    constexpr char TAG[] = "MidiApiMessage from_json";
    auto message_type_member = json.FindMember("messageType");
    if(message_type_member == json.MemberEnd()) {
        ESP_LOGE(TAG, "messageType is missing");
        goto error;
    }
    if(!message_type_member->value.IsString()) {
        ESP_LOGE(TAG, "messageType is not string");
        goto error;
    }
    {
        const etl::map<std::string, std::function<std::optional<MappingApiMessage>()>, 4> lut{
            { get_message_type<GetRequest>(), [&]{return from_json<GetRequest>(json);} },
            { get_message_type<CreateRequest>(), [&]{return from_json<CreateRequest>(json);} },
            { get_message_type<Update>(), [&]{return from_json<Update>(json);} },
            { get_message_type<Remove>(), [&]{return from_json<Remove>(json);} },
        };
        const char *message_type = message_type_member->value.GetString();
        if(auto f = lut.find(message_type); f != lut.end())
        {
            return f->second();
        }
    }
error:
    return std::nullopt;
}
References get_message_type< CreateRequest >(), get_message_type< GetRequest >(), get_message_type< Remove >(), get_message_type< Update >(), and shrapnel::parameters::TAG.
from_json() [18/19]
template<> std::optional< Mapping::id_t > shrapnel::midi::from_json (const rapidjson::Value & json)
Convert the message into a object representing it.
Definition at line 214 of file midi_mapping_json_parser.cpp.
{
    constexpr const char *TAG = "Mapping::id_t from_json";
    if (!json.IsString()) {
        ESP_LOGE(TAG, "id is not string");
        return std::nullopt;
    }
    Mapping::id_t out;
    int rc = parse_uuid(out, json.GetString());
    if(rc != 0) {
       ESP_LOGE(TAG, "failed to get uuid");
        return std::nullopt;
    }
    return out;
}
References parse_uuid(), and shrapnel::parameters::TAG.
from_json() [19/19]
template<> std::optional< float > shrapnel::midi::from_json (const rapidjson::Value & value)
Convert the message into a object representing it.
Definition at line 89 of file main.cpp.
    {
        if(!value.IsFloat()) {
            ESP_LOGE(TAG, "not float");
            return std::nullopt;
        }
        return value.GetFloat();
    }
References shrapnel::parameters::TAG.
get_message_type()
template<typename T > constexpr const char * shrapnel::midi::get_message_type () constexpr
get_message_type< CreateRequest >()
template<> constexpr const char * shrapnel::midi::get_message_type< CreateRequest > () constexpr
Definition at line 43 of file midi_message_type.h.
{
    return "MidiMap::create::request";
}
Referenced by from_json().
get_message_type< CreateResponse >()
template<> constexpr const char * shrapnel::midi::get_message_type< CreateResponse > () constexpr
Definition at line 49 of file midi_message_type.h.
{
    return "MidiMap::create::response";
}
get_message_type< GetRequest >()
template<> constexpr const char * shrapnel::midi::get_message_type< GetRequest > () constexpr
Definition at line 31 of file midi_message_type.h.
{
    return "MidiMap::get::request";
}
Referenced by from_json().
get_message_type< GetResponse >()
template<> constexpr const char * shrapnel::midi::get_message_type< GetResponse > () constexpr
Definition at line 37 of file midi_message_type.h.
{
    return "MidiMap::get::response";
}
get_message_type< Remove >()
template<> constexpr const char * shrapnel::midi::get_message_type< Remove > () constexpr
Definition at line 61 of file midi_message_type.h.
{
    return "MidiMap::remove";
}
Referenced by from_json().
get_message_type< Update >()
template<> constexpr const char * shrapnel::midi::get_message_type< Update > () constexpr
Definition at line 55 of file midi_message_type.h.
{
    return "MidiMap::update";
}
Referenced by from_json().
operator<<() [1/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const CreateRequest & self)
Definition at line 48 of file midi_mapping_api.cpp.
{
    out << "{ " << self.mapping << " }";
    return out;
}
References shrapnel::midi::CreateRequest::mapping.
operator<<() [2/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const CreateResponse & self)
Definition at line 53 of file midi_mapping_api.cpp.
{
    return out << "{ " << self.mapping << " }";
}
References shrapnel::midi::CreateResponse::mapping.
operator<<() [3/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const GetRequest & self)
Definition at line 38 of file midi_mapping_api.cpp.
{
    out << "{}";
    return out;
}
operator<<() [4/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const GetResponse & self)
Definition at line 43 of file midi_mapping_api.cpp.
{
    return out << "{ TODO }";
}
operator<<() [5/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const Mapping & self)
Definition at line 27 of file midi_mapping_api.cpp.
{
    out << "{";
    out << " channel " << self.midi_channel;
    out << " cc number " << self.cc_number;
    out << " mode "
        << (self.mode == Mapping::Mode::TOGGLE ? "toggle" : "parameter");
    out << " name " << self.parameter_name;
    out << " }";
    return out;
}
References shrapnel::midi::Mapping::cc_number, shrapnel::midi::Mapping::midi_channel, shrapnel::midi::Mapping::mode, shrapnel::midi::Mapping::parameter_name, and shrapnel::midi::Mapping::TOGGLE.
operator<<() [6/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const MappingApiMessage & self)
Definition at line 68 of file midi_mapping_api.cpp.
{
#if 1
    auto print = [&](const auto &message) {
        using T = std::decay_t<decltype(message)>;
        if constexpr (std::is_same_v<T, GetRequest>) {
            out << "<GetRequest>" << message;
        } else if constexpr (std::is_same_v<T, GetResponse>) {
            out << "<GetResponse>" << message;
        } else if constexpr (std::is_same_v<T, CreateRequest>) {
            out << "<CreateRequest>" << message;
        } else if constexpr (std::is_same_v<T, CreateResponse>) {
            out << "<CreateResponse>" << message;
        } else if constexpr (std::is_same_v<T, Update>) {
            out << "<Update>" << message;
        } else if constexpr (std::is_same_v<T, Remove>) {
            out << "<Remove>" << message;
        } else {
            out << "Unknown";
        }
    };
    std::visit(print, self);
#else
    if (auto message = std::get_if<GetRequest>(&self)) {
        out << "<GetRequest>" << *message;
    } else if (auto message = std::get_if<GetResponse>(&self)) {
        out << "<GetResponse>" << *message;
    } else if (auto message = std::get_if<CreateRequest>(&self)) {
        out << "<CreateRequest>" << *message;
    } else if (auto message = std::get_if<CreateResponse>(&self)) {
        out << "<CreateResponse>" << *message;
    } else if (auto message = std::get_if<Update>(&self)) {
        out << "<Update>" << *message;
    } else if (auto message = std::get_if<Remove>(&self)) {
        out << "<Remove>" << *message;
    } else {
        out << "Unknown";
    }
#endif
    return out;
}
operator<<() [7/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const Remove & self)
Definition at line 63 of file midi_mapping_api.cpp.
{
    return out << "{ " << self.id << " }";
}
References shrapnel::midi::Remove::id.
operator<<() [8/8]
etl::string_stream & shrapnel::midi::operator<< (etl::string_stream & out, const Update & self)
Definition at line 58 of file midi_mapping_api.cpp.
{
    return out << "{ " << self.mapping << " }";
}
References shrapnel::midi::Update::mapping.
parse_uuid()
static int shrapnel::midi::parse_uuid (Mapping::id_t & uuid, const char * string) static
Definition at line 232 of file midi_mapping_json_parser.cpp.
{
    constexpr std::size_t UUID_LENGTH = 36;
    constexpr char TAG[] = "parse_uuid";
    if(UUID_LENGTH != std::strlen(string))
    {
        ESP_LOGE(TAG, "Incorrect UUID string length");
        return -1;
    }
    size_t i = 0;
    size_t j = 0;
    ESP_LOGD(TAG, "i = %zu, j = %zu", i , j);
    while(i < UUID_LENGTH)
    {
        char digit[2];
        std::memcpy(digit, &string[i], 2);
        ESP_LOGD(TAG, "digit = %c%c", digit[0] , digit[1]);
        // TODO error on invalid characters: z, symbols etc
        //      The only valid characters are 0 to 9 and a to f.
        //
        //      Handle uppercase as well. It is required when a string UUID
        //      is an input as per RFC 4122 Section 3
        //      https://tools.ietf.org/html/rfc4122#section-3
        auto get_value = [&] (char hex) -> uint8_t {
            if(hex >= 'a')
            {
                return hex - 'a' + 10;
            }
            else
            {
                return hex - '0';
            }
        };
        uuid[j] = get_value(digit[0]) << 4 | get_value(digit[1]);
        j++;
        i += 2;
        bool is_separator = (i == 8) || (i == 13) || (i == 18) || (i == 23);
        if(is_separator) i++;
        ESP_LOGD(TAG, "i = %zu, j = %zu", i , j);
    }
    return 0;
}
References shrapnel::parameters::TAG.
Referenced by from_json().
to_json() [1/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const CreateResponse & object)
Definition at line 88 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mapping = to_json(document, object.mapping);
    json.AddMember("mapping", mapping, document.GetAllocator());
    return json;
}
References to_json().
to_json() [2/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const CreateResponse & object)
Definition at line 88 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mapping = to_json(document, object.mapping);
    json.AddMember("mapping", mapping, document.GetAllocator());
    return json;
}
References to_json().
to_json() [3/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const etl::imap< Mapping::id_t, Mapping > & object)
Definition at line 133 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    for(const auto &entry : object)
    {
        rapidjson::Value mapping = to_json(document, entry.second);
        auto id = to_json(document, entry.first);
        json.AddMember(id, mapping, document.GetAllocator());
    }
    return json;
}
References to_json().
to_json() [4/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const etl::imap< Mapping::id_t, Mapping > & object)
Definition at line 133 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    for(const auto &entry : object)
    {
        rapidjson::Value mapping = to_json(document, entry.second);
        auto id = to_json(document, entry.first);
        json.AddMember(id, mapping, document.GetAllocator());
    }
    return json;
}
References to_json().
to_json() [5/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const float & object)
Definition at line 99 of file main.cpp.
    {
        rapidjson::Value out{};
        out.SetFloat(object);
        return out;
    }
Referenced by shrapnel::websocket_send().
to_json() [6/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const GetResponse & object)
Definition at line 99 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mappings = to_json(document, *object.mappings);
    json.AddMember("mappings", mappings, document.GetAllocator());
    return json;
}
References to_json().
to_json() [7/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const GetResponse & object)
Definition at line 99 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mappings = to_json(document, *object.mappings);
    json.AddMember("mappings", mappings, document.GetAllocator());
    return json;
}
References to_json().
to_json() [8/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const Mapping & object)
Definition at line 32 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value midi_channel;
    midi_channel = object.midi_channel;
    json.AddMember("midi_channel", midi_channel, document.GetAllocator());
    rapidjson::Value cc_number;
    cc_number = object.cc_number;
    json.AddMember("cc_number", cc_number, document.GetAllocator());
    rapidjson::Value mode;
    mode.SetString(object.mode == Mapping::Mode::TOGGLE ? "toggle"
                                                        : "parameter",
                   document.GetAllocator());
    json.AddMember("mode", mode, document.GetAllocator());
    rapidjson::Value parameter_id;
    parameter_id.SetString(object.parameter_name.data(), object.parameter_name.size(), document.GetAllocator());
    json.AddMember("parameter_id", parameter_id, document.GetAllocator());
    return json;
}
References shrapnel::midi::Mapping::TOGGLE.
to_json() [9/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const Mapping & object)
Definition at line 32 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value midi_channel;
    midi_channel = object.midi_channel;
    json.AddMember("midi_channel", midi_channel, document.GetAllocator());
    rapidjson::Value cc_number;
    cc_number = object.cc_number;
    json.AddMember("cc_number", cc_number, document.GetAllocator());
    rapidjson::Value mode;
    mode.SetString(object.mode == Mapping::Mode::TOGGLE ? "toggle"
                                                        : "parameter",
                   document.GetAllocator());
    json.AddMember("mode", mode, document.GetAllocator());
    rapidjson::Value parameter_id;
    parameter_id.SetString(object.parameter_name.data(), object.parameter_name.size(), document.GetAllocator());
    json.AddMember("parameter_id", parameter_id, document.GetAllocator());
    return json;
}
References shrapnel::midi::Mapping::TOGGLE.
to_json() [10/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const Mapping::id_t & object)
Definition at line 59 of file midi_mapping_json_builder.cpp.
{
    char uuid[37];
    sprintf(uuid,
            "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-"
            "%02x%02x%02x%02x%02x%02x",
            object[0], object[1], object[2], object[3], object[4], object[5],
            object[6], object[7], object[8], object[9], object[10], object[11],
            object[12], object[13], object[14], object[15]);
    rapidjson::Value out;
    out.SetString(uuid, 36, document.GetAllocator());
    return out;
}
to_json() [11/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const Mapping::id_t & object)
Definition at line 59 of file midi_mapping_json_builder.cpp.
{
    char uuid[37];
    sprintf(uuid,
            "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-"
            "%02x%02x%02x%02x%02x%02x",
            object[0], object[1], object[2], object[3], object[4], object[5],
            object[6], object[7], object[8], object[9], object[10], object[11],
            object[12], object[13], object[14], object[15]);
    rapidjson::Value out;
    out.SetString(uuid, 36, document.GetAllocator());
    return out;
}
to_json() [12/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const MappingApiMessage & object)
Definition at line 110 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message) {
        using T = std::decay_t<decltype(message)>;
        if constexpr (std::is_same_v<T, CreateResponse> ||
                      std::is_same_v<T, GetResponse>) {
            json = to_json(document, message);
        } else {
            ESP_LOGE(TAG, "No handler registered for message");
        }
        json.AddMember("messageType", rapidjson::StringRef(get_message_type<T>()), document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References shrapnel::parameters::TAG, and to_json().
to_json() [13/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const MappingApiMessage & object)
Definition at line 110 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    auto visitor = [&](const auto &message) {
        using T = std::decay_t<decltype(message)>;
        if constexpr (std::is_same_v<T, CreateResponse> ||
                      std::is_same_v<T, GetResponse>) {
            json = to_json(document, message);
        } else {
            ESP_LOGE(TAG, "No handler registered for message");
        }
        json.AddMember("messageType", rapidjson::StringRef(get_message_type<T>()), document.GetAllocator());
    };
    std::visit(visitor, object);
    return json;
}
References shrapnel::parameters::TAG, and to_json().
to_json() [14/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const std::pair< Mapping::id_t, Mapping > & object)
Definition at line 76 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mapping = to_json(document, object.second);
    auto id = to_json(document, object.first);
    json.AddMember(id, mapping, document.GetAllocator());
    return json;
}
References to_json().
to_json() [15/16]
template<> rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const std::pair< Mapping::id_t, Mapping > & object)
Definition at line 76 of file midi_mapping_json_builder.cpp.
{
    rapidjson::Value json;
    json.SetObject();
    rapidjson::Value mapping = to_json(document, object.second);
    auto id = to_json(document, object.first);
    json.AddMember(id, mapping, document.GetAllocator());
    return json;
}
References to_json().
to_json() [16/16]
template<typename T > rapidjson::Value shrapnel::midi::to_json (rapidjson::Document & document, const T & object)
Convert object to a JSON value.
Note
The document must not by modified by this function. It is only passed in so that its allocator member can be accessed.
Referenced by to_json().
Variable Documentation
CC_VALUE_MAX
int constexpr shrapnel::midi::CC_VALUE_MAX = 127 constexpr
Definition at line 31 of file midi_protocol.h.
Referenced by shrapnel::midi::MappingManager< AudioParametersT, MAX_MAPPINGS, MAX_OBSERVERS >::process_message().