ShrapnelDSP: effects/gate/include/noise_gate.h File Reference
noise_gate.h File Reference
Functions
int gate_init (void)
Initialise the effect.
void gate_reset (void)
Reset the state.
void gate_set_buffer_size (size_t buffer_size)
Set the buffer size in number of samples.
void gate_set_sample_rate (float a_sample_rate)
Set the sample rate in Hz.
void gate_set_threshold (float a_threshold, float a_hysteresis)
Set the threshold and hysteresis value in dBFS.
void gate_set_attack (float a_attack)
Set the attack time in milliseconds.
void gate_set_hold (float a_hold)
Set the hold time in milliseconds.
void gate_set_release (float a_release)
Set the release time in milliseconds.
void gate_analyse (const float *buf, size_t sample_count)
Analyse the audio.
void gate_process (float *buf, size_t sample_count)
Apply the precalculated gain to the audio.
Function Documentation
gate_analyse()
void gate_analyse (const float * buf, size_t sample_count)
Analyse the audio.
This calculates the gain values to use in the gate_process function.
Note
Make sure to use the same buffer with this function and gate_process.
Definition at line 155 of file noise_gate.cpp.
{
    assert(sample_count <= buffer_size);
    static float gain = 0;
    static state_t next_state = INIT;
    static int hold_count = 0;
    // rectify the signal
    for(size_t i = 0; i < sample_count; i++)
    {
        filter_buffer[i] = fabsf(buf[i]);
    }
    //low pass filter
    envelope_detect_filter->process(filter_buffer, filter_buffer, sample_count);
    // work out the gain
    for(size_t i = 0; i < sample_count; i++)
    {
        switch(state)
        {
            case INIT:
                //don't need to init hold_count, it will be initialised when
                //leaving the attack state
                gain = 0;
                next_state = CLOSED;
                break;
            case CLOSED:
                if(filter_buffer[i] > threshold)
                {
                    next_state = ATTACK;
                }
                else
                {
                    next_state = CLOSED;
                }
                break;
            case ATTACK:
                if(filter_buffer[i] > threshold)
                {
                    gain = gain + 1.f/attack_samples;
                    if(gain > 1)
                    {
                        gain = 1;
                        hold_count = 0;
                        next_state = OPEN;
                    }
                }
                else
                {
                    next_state = RELEASE;
                }
                break;
            case OPEN:
                if(filter_buffer[i] > threshold_low)
                {
                    hold_count = 0;
                    next_state = OPEN;
                }
                else
                {
                    hold_count = hold_count + 1;
                    if(hold_count > hold_samples)
                    {
                        next_state = RELEASE;
                    }
                    else
                    {
                        next_state = OPEN;
                    }
                }
                break;
            case RELEASE:
                if(filter_buffer[i] > threshold_low)
                {
                    next_state = ATTACK;
                }
                else
                {
                    gain = gain - 1.f/release_samples;
                    if(gain < 0)
                    {
                        gain = 0;
                        next_state = CLOSED;
                    }
                }
                break;
            default:
                next_state = INIT;
                break;
        }
        state = next_state;
        gain_buffer[i] = gain;
    }
}
References ATTACK, attack_samples, buffer_size, CLOSED, envelope_detect_filter, filter_buffer, gain_buffer, hold_samples, INIT, OPEN, shrapnel::dsp::IirFilter::process(), RELEASE, release_samples, state, threshold, and threshold_low.
Referenced by process_samples().
gate_init()
int gate_init (void)
Initialise the effect.
Definition at line 50 of file noise_gate.cpp.
{
    assert(envelope_detect_filter == NULL && "already initialised");
    envelope_detect_filter = new shrapnel::dsp::IirFilter();
    if(envelope_detect_filter == NULL)
    {
        return -1;
    }
    gate_reset();
    return 0;
}
References envelope_detect_filter, and gate_reset().
Referenced by process_init().
gate_process()
void gate_process (float * buf, size_t sample_count)
Apply the precalculated gain to the audio.
Applies the gain from gate_analyse function
Note
Make sure to use the same buffer with this function and gate_analyse.
Definition at line 253 of file noise_gate.cpp.
{
    dspal_multiply(gain_buffer, buf, buf, sample_count);
}
References dspal_multiply(), and gain_buffer.
Referenced by process_samples().
gate_reset()
void gate_reset (void)
Reset the state.
Definition at line 66 of file noise_gate.cpp.
{
    state = INIT;
    if(gain_buffer)
    {
        memset(gain_buffer, 0, sizeof(*gain_buffer)*buffer_size);
    }
    if(filter_buffer)
    {
        memset(filter_buffer, 0, sizeof(*filter_buffer)*buffer_size);
    }
}
References buffer_size, filter_buffer, gain_buffer, INIT, and state.
Referenced by gate_init().
gate_set_attack()
void gate_set_attack (float a_attack)
Set the attack time in milliseconds.
Note
must be called after gate_set_sample_rate
Definition at line 140 of file noise_gate.cpp.
{
    attack_samples = sample_rate * a_attack / 1000.f;
}
References attack_samples, and sample_rate.
Referenced by process_init(), and process_samples().
gate_set_buffer_size()
void gate_set_buffer_size (size_t buffer_size)
Set the buffer size in number of samples.
Definition at line 83 of file noise_gate.cpp.
{
    if(gain_buffer)
    {
        free(gain_buffer);
        gain_buffer = NULL;
    }
    gain_buffer = static_cast<float *>(calloc(a_buffer_size, sizeof(*gain_buffer)));
    if(gain_buffer == NULL)
    {
        return;
    }
    if(filter_buffer)
    {
        free(filter_buffer);
        filter_buffer = NULL;
    }
    filter_buffer = static_cast<float *>(calloc(a_buffer_size, sizeof(*filter_buffer)));
    if(filter_buffer == NULL)
    {
        return;
    }
    buffer_size = a_buffer_size;
}
References buffer_size, filter_buffer, and gain_buffer.
Referenced by process_init().
gate_set_hold()
void gate_set_hold (float a_hold)
Set the hold time in milliseconds.
Note
must be called after gate_set_sample_rate
Definition at line 145 of file noise_gate.cpp.
{
    hold_samples = sample_rate * a_hold / 1000.f;
}
References hold_samples, and sample_rate.
Referenced by process_init(), and process_samples().
gate_set_release()
void gate_set_release (float a_release)
Set the release time in milliseconds.
Note
must be called after gate_set_sample_rate
Definition at line 150 of file noise_gate.cpp.
{
    release_samples = sample_rate * a_release / 1000.f;
}
References release_samples, and sample_rate.
Referenced by process_init(), and process_samples().
gate_set_sample_rate()
void gate_set_sample_rate (float a_sample_rate)
Set the sample rate in Hz.
Definition at line 112 of file noise_gate.cpp.
{
    std::array<float, 6> coeffs = {0};
    dspal_biquad_design_lowpass(coeffs.data(), 10.f/a_sample_rate, M_SQRT1_2);
    memmove(&coeffs.data()[4], &coeffs.data()[3], 2*sizeof(*coeffs.data()));
    coeffs[3] = 1.f;
    envelope_detect_filter->set_coefficients(coeffs);
    sample_rate = a_sample_rate;
}
References dspal_biquad_design_lowpass(), envelope_detect_filter, sample_rate, and shrapnel::dsp::IirFilter::set_coefficients().
Referenced by process_init().
gate_set_threshold()
void gate_set_threshold (float a_threshold, float a_hysteresis)
Set the threshold and hysteresis value in dBFS.
When the level is above the threshold, the gate starts opening. When the level falls below the threshold minus hysteresis, the gate starts closing.
Definition at line 130 of file noise_gate.cpp.
{
    assert(a_hysteresis >= 0.f);
    threshold = db_to_ratio(a_threshold);
    threshold_low = threshold * db_to_ratio(-1.f * a_hysteresis);
    assert(threshold_low <= threshold);
}
References db_to_ratio(), threshold, and threshold_low.
Referenced by process_init(), and process_samples().