ShrapnelDSP: firmware/components/pcm3060/pcm3060.c File Reference
pcm3060.c File Reference
Functions
static bool _initialised (void)
esp_err_t _i2c_write (uint8_t reg_adr, uint8_t data)
void pcm3060_init (i2c_port_t port, bool adr)
Initialise the driver.
esp_err_t pcm3060_power_up (void)
perform power up sequence
esp_err_t pcm3060_power_down (void)
perform power down sequence
Variables
static uint8_t _address
static i2c_port_t _port = -1
Function Documentation
_i2c_write()
esp_err_t _i2c_write (uint8_t reg_adr, uint8_t data)
Definition at line 37 of file pcm3060.c.
{
    esp_err_t err = i2c_write_byte(_port, _address, reg_adr, data);
    if(err != ESP_OK)
    {
        ESP_LOGE(TAG, "Write to reg 0x%02x failed", reg_adr);
    }
    return err;
}
References _address, _port, i2c_write_byte(), and shrapnel::parameters::TAG.
Referenced by pcm3060_power_down(), and pcm3060_power_up().
_initialised()
static bool _initialised (void) static
Definition at line 31 of file pcm3060.c.
{
    return _port != -1;
}
References _port.
Referenced by pcm3060_power_down(), and pcm3060_power_up().
pcm3060_init()
void pcm3060_init (i2c_port_t port, bool adr)
Initialise the driver.
Definition at line 49 of file pcm3060.c.
{
    _port = port;
    _address = I2C_ADDRESS | (adr << 1);
}
References _address, and _port.
Referenced by shrapnel::app_main().
pcm3060_power_down()
esp_err_t pcm3060_power_down (void)
perform power down sequence
Definition at line 74 of file pcm3060.c.
{
    if(!_initialised())
    {
        return ESP_FAIL;
    }
    return _i2c_write(0x40, 0xF1);//single ended output, power save enable
}
References _i2c_write(), and _initialised().
pcm3060_power_up()
esp_err_t pcm3060_power_up (void)
perform power up sequence
Definition at line 55 of file pcm3060.c.
{
    esp_err_t err;
    if(!_initialised())
    {
        return ESP_FAIL;
    }
    err = _i2c_write(0x43, 0x80);//use clock1 for DAC, slave mode, 24-bit I2S
    if(err != ESP_OK)
    {
        return err;
    }
    err = _i2c_write(0x40, 0xC0);//differential output, power save release
    return err;
}
References _i2c_write(), and _initialised().
Referenced by shrapnel::app_main().
Variable Documentation
_address
uint8_t _address static
Definition at line 28 of file pcm3060.c.
Referenced by _i2c_write(), and pcm3060_init().
_port
i2c_port_t _port = -1 static
Definition at line 29 of file pcm3060.c.
Referenced by _i2c_write(), _initialised(), and pcm3060_init().