ShrapnelDSP: firmware/components/presets/proto/generated/presets.pb-c.c File Reference
presets.pb-c.c File Reference
Functions
void preset_parameters__init (PresetParameters *message)
size_t preset_parameters__get_packed_size (const PresetParameters *message)
size_t preset_parameters__pack (const PresetParameters *message, uint8_t *out)
size_t preset_parameters__pack_to_buffer (const PresetParameters *message, ProtobufCBuffer *buffer)
PresetParameters * preset_parameters__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset_parameters__free_unpacked (PresetParameters *message, ProtobufCAllocator *allocator)
void preset_record__init (PresetRecord *message)
size_t preset_record__get_packed_size (const PresetRecord *message)
size_t preset_record__pack (const PresetRecord *message, uint8_t *out)
size_t preset_record__pack_to_buffer (const PresetRecord *message, ProtobufCBuffer *buffer)
PresetRecord * preset_record__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset_record__free_unpacked (PresetRecord *message, ProtobufCAllocator *allocator)
void preset__init (Preset *message)
size_t preset__get_packed_size (const Preset *message)
size_t preset__pack (const Preset *message, uint8_t *out)
size_t preset__pack_to_buffer (const Preset *message, ProtobufCBuffer *buffer)
Preset * preset__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset__free_unpacked (Preset *message, ProtobufCAllocator *allocator)
Variables
static const ProtobufCFieldDescriptor preset_parameters__field_descriptors [20]
static const unsigned preset_parameters__field_indices_by_name []
static const ProtobufCIntRange preset_parameters__number_ranges [1+1]
const ProtobufCMessageDescriptor preset_parameters__descriptor
static const ProtobufCFieldDescriptor preset_record__field_descriptors [2]
static const unsigned preset_record__field_indices_by_name []
static const ProtobufCIntRange preset_record__number_ranges [1+1]
const ProtobufCMessageDescriptor preset_record__descriptor
static const ProtobufCFieldDescriptor preset__field_descriptors [2]
static const unsigned preset__field_indices_by_name []
static const ProtobufCIntRange preset__number_ranges [1+1]
const ProtobufCMessageDescriptor preset__descriptor
Function Documentation
preset__free_unpacked()
void preset__free_unpacked (Preset * message, ProtobufCAllocator * allocator)
Definition at line 136 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::deserialise_preset().
preset__get_packed_size()
size_t preset__get_packed_size (const Preset * message)
Definition at line 106 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::serialise_preset().
preset__init()
void preset__init (Preset * message)
Definition at line 100 of file presets.pb-c.c.
{
  static const Preset init_value = PRESET__INIT;
  *message = init_value;
}
Referenced by shrapnel::presets::serialise_preset().
preset__pack()
size_t preset__pack (const Preset * message, uint8_t * out)
Definition at line 112 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::serialise_preset().
preset__pack_to_buffer()
size_t preset__pack_to_buffer (const Preset * message, ProtobufCBuffer * buffer)
Definition at line 119 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References Preset::base, and preset__descriptor.
preset__unpack()
Preset * preset__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 127 of file presets.pb-c.c.
{
  return (Preset *)
     protobuf_c_message_unpack (&preset__descriptor,
                                allocator, len, data);
}
References preset__descriptor.
Referenced by shrapnel::presets::deserialise_preset().
preset_parameters__free_unpacked()
void preset_parameters__free_unpacked (PresetParameters * message, ProtobufCAllocator * allocator)
Definition at line 46 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset_parameters__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::from_json().
preset_parameters__get_packed_size()
size_t preset_parameters__get_packed_size (const PresetParameters * message)
Definition at line 16 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::serialise_parameters().
preset_parameters__init()
void preset_parameters__init (PresetParameters * message)
Definition at line 10 of file presets.pb-c.c.
{
  static const PresetParameters init_value = PRESET_PARAMETERS__INIT;
  *message = init_value;
}
Referenced by shrapnel::presets::serialise_parameters(), and shrapnel::presets::serialise_preset().
preset_parameters__pack()
size_t preset_parameters__pack (const PresetParameters * message, uint8_t * out)
Definition at line 22 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::serialise_parameters().
preset_parameters__pack_to_buffer()
size_t preset_parameters__pack_to_buffer (const PresetParameters * message, ProtobufCBuffer * buffer)
Definition at line 29 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References PresetParameters::base, and preset_parameters__descriptor.
preset_parameters__unpack()
PresetParameters * preset_parameters__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 37 of file presets.pb-c.c.
{
  return (PresetParameters *)
     protobuf_c_message_unpack (&preset_parameters__descriptor,
                                allocator, len, data);
}
References preset_parameters__descriptor.
Referenced by shrapnel::presets::from_json().
preset_record__free_unpacked()
void preset_record__free_unpacked (PresetRecord * message, ProtobufCAllocator * allocator)
Definition at line 91 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__get_packed_size()
size_t preset_record__get_packed_size (const PresetRecord * message)
Definition at line 61 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__init()
void preset_record__init (PresetRecord * message)
Definition at line 55 of file presets.pb-c.c.
{
  static const PresetRecord init_value = PRESET_RECORD__INIT;
  *message = init_value;
}
preset_record__pack()
size_t preset_record__pack (const PresetRecord * message, uint8_t * out)
Definition at line 67 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__pack_to_buffer()
size_t preset_record__pack_to_buffer (const PresetRecord * message, ProtobufCBuffer * buffer)
Definition at line 74 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__unpack()
PresetRecord * preset_record__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 82 of file presets.pb-c.c.
{
  return (PresetRecord *)
     protobuf_c_message_unpack (&preset_record__descriptor,
                                allocator, len, data);
}
References preset_record__descriptor.
Variable Documentation
preset__descriptor
const ProtobufCMessageDescriptor preset__descriptor
Initial value:
=
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Preset",
  "Preset",
  "Preset",
  "",
  sizeof(Preset),
  2,
  preset__field_descriptors,
  preset__field_indices_by_name,
  1,  preset__number_ranges,
  (ProtobufCMessageInit) preset__init,
  NULL,NULL,NULL
}
Definition at line 517 of file presets.pb-c.c.
Referenced by preset__free_unpacked(), preset__get_packed_size(), preset__pack(), preset__pack_to_buffer(), and preset__unpack().
preset__field_descriptors
const ProtobufCFieldDescriptor preset__field_descriptors[2] static
Initial value:
=
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,
    offsetof(Preset, name),
    NULL,
    &protobuf_c_empty_string,
    0,
    0,NULL,NULL
  },
  {
    "parameters",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,
    offsetof(Preset, parameters),
    &preset_parameters__descriptor,
    NULL,
    0,
    0,NULL,NULL
  },
}
Definition at line 481 of file presets.pb-c.c.
preset__field_indices_by_name
const unsigned preset__field_indices_by_name[] static
Initial value:
= {
  0,
  1,
}
Definition at line 508 of file presets.pb-c.c.
preset__number_ranges
const ProtobufCIntRange preset__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 2 }
}
Definition at line 512 of file presets.pb-c.c.
preset_parameters__descriptor
const ProtobufCMessageDescriptor preset_parameters__descriptor
Initial value:
=
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PresetParameters",
  "PresetParameters",
  "PresetParameters",
  "",
  sizeof(PresetParameters),
  20,
  preset_parameters__field_descriptors,
  preset_parameters__field_indices_by_name,
  1,  preset_parameters__number_ranges,
  (ProtobufCMessageInit) preset_parameters__init,
  NULL,NULL,NULL
}
Definition at line 415 of file presets.pb-c.c.
Referenced by preset_parameters__free_unpacked(), preset_parameters__get_packed_size(), preset_parameters__pack(), preset_parameters__pack_to_buffer(), and preset_parameters__unpack().
preset_parameters__field_descriptors
const ProtobufCFieldDescriptor preset_parameters__field_descriptors[20] static
Definition at line 145 of file presets.pb-c.c.
preset_parameters__field_indices_by_name
const unsigned preset_parameters__field_indices_by_name[] static
Initial value:
= {
  1,
  0,
  2,
  16,
  14,
  15,
  13,
  5,
  3,
  9,
  12,
  10,
  8,
  11,
  7,
  4,
  6,
  19,
  17,
  18,
}
Definition at line 388 of file presets.pb-c.c.
preset_parameters__number_ranges
const ProtobufCIntRange preset_parameters__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 20 }
}
Definition at line 410 of file presets.pb-c.c.
preset_record__descriptor
const ProtobufCMessageDescriptor preset_record__descriptor
Initial value:
=
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PresetRecord",
  "PresetRecord",
  "PresetRecord",
  "",
  sizeof(PresetRecord),
  2,
  preset_record__field_descriptors,
  preset_record__field_indices_by_name,
  1,  preset_record__number_ranges,
  (ProtobufCMessageInit) preset_record__init,
  NULL,NULL,NULL
}
Definition at line 466 of file presets.pb-c.c.
Referenced by preset_record__free_unpacked(), preset_record__get_packed_size(), preset_record__pack(), preset_record__pack_to_buffer(), and preset_record__unpack().
preset_record__field_descriptors
const ProtobufCFieldDescriptor preset_record__field_descriptors[2] static
Initial value:
=
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,
    offsetof(PresetRecord, id),
    NULL,
    NULL,
    0,
    0,NULL,NULL
  },
  {
    "preset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,
    offsetof(PresetRecord, preset),
    &preset__descriptor,
    NULL,
    0,
    0,NULL,NULL
  },
}
Definition at line 430 of file presets.pb-c.c.
preset_record__field_indices_by_name
const unsigned preset_record__field_indices_by_name[] static
Initial value:
= {
  0,
  1,
}
Definition at line 457 of file presets.pb-c.c.
preset_record__number_ranges
const ProtobufCIntRange preset_record__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 2 }
}
Definition at line 461 of file presets.pb-c.c.