ShrapnelDSP: firmware/components/presets/proto/generated/presets.pb-c.h File Reference
presets.pb-c.h File Reference
Data Structures
struct PresetParameters
struct PresetRecord
struct Preset
Typedefs
typedef typedefPROTOBUF_C__BEGIN_DECLS struct PresetParameters PresetParameters
typedef struct PresetRecord PresetRecord
typedef struct Preset Preset
typedef void(* PresetParameters_Closure) (const PresetParameters *message, void *closure_data)
typedef void(* PresetRecord_Closure) (const PresetRecord *message, void *closure_data)
typedef void(* Preset_Closure) (const Preset *message, void *closure_data)
Functions
void preset_parameters__init (PresetParameters *message)
size_t preset_parameters__get_packed_size (const PresetParameters *message)
size_t preset_parameters__pack (const PresetParameters *message, uint8_t *out)
size_t preset_parameters__pack_to_buffer (const PresetParameters *message, ProtobufCBuffer *buffer)
PresetParameters * preset_parameters__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset_parameters__free_unpacked (PresetParameters *message, ProtobufCAllocator *allocator)
void preset_record__init (PresetRecord *message)
size_t preset_record__get_packed_size (const PresetRecord *message)
size_t preset_record__pack (const PresetRecord *message, uint8_t *out)
size_t preset_record__pack_to_buffer (const PresetRecord *message, ProtobufCBuffer *buffer)
PresetRecord * preset_record__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset_record__free_unpacked (PresetRecord *message, ProtobufCAllocator *allocator)
void preset__init (Preset *message)
size_t preset__get_packed_size (const Preset *message)
size_t preset__pack (const Preset *message, uint8_t *out)
size_t preset__pack_to_buffer (const Preset *message, ProtobufCBuffer *buffer)
Preset * preset__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void preset__free_unpacked (Preset *message, ProtobufCAllocator *allocator)
Variables
const ProtobufCMessageDescriptor preset_parameters__descriptor
const ProtobufCMessageDescriptor preset_record__descriptor
const ProtobufCMessageDescriptor preset__descriptor
Typedef Documentation
Preset
typedef struct Preset Preset
Definition at line 20 of file presets.pb-c.h.
Preset_Closure
typedef void(* Preset_Closure) (const Preset *message, void *closure_data)
Definition at line 153 of file presets.pb-c.h.
PresetParameters
typedef typedefPROTOBUF_C__BEGIN_DECLS struct PresetParameters PresetParameters
Definition at line 18 of file presets.pb-c.h.
PresetParameters_Closure
typedef void(* PresetParameters_Closure) (const PresetParameters *message, void *closure_data)
Definition at line 147 of file presets.pb-c.h.
PresetRecord
typedef struct PresetRecord PresetRecord
Definition at line 19 of file presets.pb-c.h.
PresetRecord_Closure
typedef void(* PresetRecord_Closure) (const PresetRecord *message, void *closure_data)
Definition at line 150 of file presets.pb-c.h.
Function Documentation
preset__free_unpacked()
void preset__free_unpacked (Preset * message, ProtobufCAllocator * allocator)
Definition at line 136 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::deserialise_preset().
preset__get_packed_size()
size_t preset__get_packed_size (const Preset * message)
Definition at line 106 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::serialise_preset().
preset__init()
void preset__init (Preset * message)
Definition at line 100 of file presets.pb-c.c.
{
  static const Preset init_value = PRESET__INIT;
  *message = init_value;
}
Referenced by shrapnel::presets::serialise_preset().
preset__pack()
size_t preset__pack (const Preset * message, uint8_t * out)
Definition at line 112 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References Preset::base, and preset__descriptor.
Referenced by shrapnel::presets::serialise_preset().
preset__pack_to_buffer()
size_t preset__pack_to_buffer (const Preset * message, ProtobufCBuffer * buffer)
Definition at line 119 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References Preset::base, and preset__descriptor.
preset__unpack()
Preset * preset__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 127 of file presets.pb-c.c.
{
  return (Preset *)
     protobuf_c_message_unpack (&preset__descriptor,
                                allocator, len, data);
}
References preset__descriptor.
Referenced by shrapnel::presets::deserialise_preset().
preset_parameters__free_unpacked()
void preset_parameters__free_unpacked (PresetParameters * message, ProtobufCAllocator * allocator)
Definition at line 46 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset_parameters__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::from_json().
preset_parameters__get_packed_size()
size_t preset_parameters__get_packed_size (const PresetParameters * message)
Definition at line 16 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::serialise_parameters().
preset_parameters__init()
void preset_parameters__init (PresetParameters * message)
Definition at line 10 of file presets.pb-c.c.
{
  static const PresetParameters init_value = PRESET_PARAMETERS__INIT;
  *message = init_value;
}
Referenced by shrapnel::presets::serialise_parameters(), and shrapnel::presets::serialise_preset().
preset_parameters__pack()
size_t preset_parameters__pack (const PresetParameters * message, uint8_t * out)
Definition at line 22 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References PresetParameters::base, and preset_parameters__descriptor.
Referenced by shrapnel::presets::serialise_parameters().
preset_parameters__pack_to_buffer()
size_t preset_parameters__pack_to_buffer (const PresetParameters * message, ProtobufCBuffer * buffer)
Definition at line 29 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_parameters__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References PresetParameters::base, and preset_parameters__descriptor.
preset_parameters__unpack()
PresetParameters * preset_parameters__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 37 of file presets.pb-c.c.
{
  return (PresetParameters *)
     protobuf_c_message_unpack (&preset_parameters__descriptor,
                                allocator, len, data);
}
References preset_parameters__descriptor.
Referenced by shrapnel::presets::from_json().
preset_record__free_unpacked()
void preset_record__free_unpacked (PresetRecord * message, ProtobufCAllocator * allocator)
Definition at line 91 of file presets.pb-c.c.
{
  if(!message)
    return;
  assert(message->base.descriptor == &preset_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__get_packed_size()
size_t preset_record__get_packed_size (const PresetRecord * message)
Definition at line 61 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__init()
void preset_record__init (PresetRecord * message)
Definition at line 55 of file presets.pb-c.c.
{
  static const PresetRecord init_value = PRESET_RECORD__INIT;
  *message = init_value;
}
preset_record__pack()
size_t preset_record__pack (const PresetRecord * message, uint8_t * out)
Definition at line 67 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__pack_to_buffer()
size_t preset_record__pack_to_buffer (const PresetRecord * message, ProtobufCBuffer * buffer)
Definition at line 74 of file presets.pb-c.c.
{
  assert(message->base.descriptor == &preset_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
References PresetRecord::base, and preset_record__descriptor.
preset_record__unpack()
PresetRecord * preset_record__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
Definition at line 82 of file presets.pb-c.c.
{
  return (PresetRecord *)
     protobuf_c_message_unpack (&preset_record__descriptor,
                                allocator, len, data);
}
References preset_record__descriptor.
Variable Documentation
preset__descriptor
const ProtobufCMessageDescriptor preset__descriptor extern
Definition at line 517 of file presets.pb-c.c.
Referenced by preset__free_unpacked(), preset__get_packed_size(), preset__pack(), preset__pack_to_buffer(), and preset__unpack().
preset_parameters__descriptor
const ProtobufCMessageDescriptor preset_parameters__descriptor extern
Definition at line 415 of file presets.pb-c.c.
Referenced by preset_parameters__free_unpacked(), preset_parameters__get_packed_size(), preset_parameters__pack(), preset_parameters__pack_to_buffer(), and preset_parameters__unpack().
preset_record__descriptor
const ProtobufCMessageDescriptor preset_record__descriptor extern
Definition at line 466 of file presets.pb-c.c.
Referenced by preset_record__free_unpacked(), preset_record__get_packed_size(), preset_record__pack(), preset_record__pack_to_buffer(), and preset_record__unpack().