ShrapnelDSP: firmware/components/i2s/process.h File Reference
process.h File Reference
Functions
void process_samples (int32_t *buf, size_t buf_len)
esp_err_t process_init (shrapnel::parameters::AudioParametersBase *audio_params)
Function Documentation
process_init()
esp_err_t process_init (shrapnel::parameters::AudioParametersBase * audio_params)
Definition at line 184 of file process.cpp.
{
    ESP_ERROR_CHECK(gate_init());
    gate_set_sample_rate(SAMPLE_RATE);
    gate_set_threshold(-60, 1);
    gate_set_attack(10);
    gate_set_hold(50);
    gate_set_release(50);
    gate_set_buffer_size(DMA_BUF_SIZE);
    chorus = new shrapnel::effect::Chorus();
    assert(chorus);
    chorus->set_sample_rate(SAMPLE_RATE);
    wah = new shrapnel::effect::Wah();
    assert(wah);
    wah->set_sample_rate(SAMPLE_RATE);
    valvestate = new shrapnel::effect::valvestate::Valvestate();
    assert(valvestate);
    valvestate->prepare(SAMPLE_RATE);
    amp_gain = audio_params->get_raw_parameter("ampGain");
    assert(amp_gain);
    amp_channel = audio_params->get_raw_parameter("ampChannel");
    assert(amp_channel);
    bass = audio_params->get_raw_parameter("bass");
    assert(bass);
    middle = audio_params->get_raw_parameter("middle");
    assert(middle);
    treble = audio_params->get_raw_parameter("treble");
    assert(treble);
    contour = audio_params->get_raw_parameter("contour");
    assert(contour);
    volume = audio_params->get_raw_parameter("volume");
    assert(volume);
    gate_threshold = audio_params->get_raw_parameter("noiseGateThreshold");
    assert(gate_threshold);
    gate_hysteresis = audio_params->get_raw_parameter("noiseGateHysteresis");
    assert(gate_hysteresis);
    gate_attack = audio_params->get_raw_parameter("noiseGateAttack");
    assert(gate_attack);
    gate_hold = audio_params->get_raw_parameter("noiseGateHold");
    assert(gate_hold);
    gate_release = audio_params->get_raw_parameter("noiseGateRelease");
    assert(gate_release);
    gate_bypass = audio_params->get_raw_parameter("noiseGateBypass");
    assert(gate_bypass);
    chorus_rate = audio_params->get_raw_parameter("chorusRate");
    assert(chorus_rate);
    chorus_depth = audio_params->get_raw_parameter("chorusDepth");
    assert(chorus_depth);
    chorus_mix = audio_params->get_raw_parameter("chorusMix");
    assert(chorus_mix);
    chorus_bypass = audio_params->get_raw_parameter("chorusBypass");
    assert(chorus_bypass);
    wah_position = audio_params->get_raw_parameter("wahPosition");
    assert(wah_position);
    wah_vocal = audio_params->get_raw_parameter("wahVocal");
    assert(wah_vocal);
    wah_bypass = audio_params->get_raw_parameter("wahBypass");
    assert(wah_bypass);
    ESP_LOGI(TAG, "Initialised FIR filter with length %d", fir_coeff.size());
    auto speaker_convolution = std::make_unique<shrapnel::dsp::FastConvolution<1024, 512>>(fir_coeff);
    assert(speaker_convolution.get());
    speaker = new shrapnel::dsp::FastFir<
        DMA_BUF_SIZE,
        1024,
        shrapnel::dsp::FastConvolution<1024, 512>>(std::move(speaker_convolution));
    assert(speaker);
    return ESP_OK;
}
References shrapnel::audio_params, fir_coeff, gate_init(), gate_set_attack(), gate_set_buffer_size(), gate_set_hold(), gate_set_release(), gate_set_sample_rate(), gate_set_threshold(), and shrapnel::parameters::TAG.
Referenced by i2s_processing_task().
process_samples()
void process_samples (int32_t * buf, size_t buf_len)
Definition at line 93 of file process.cpp.
{
    assert(g_profiling_gpio != -1 && "I2S task has not been initialised");
    gpio_set_level(g_profiling_gpio, 1);
    profiling_start();
    /* Copy samples, skipping every second one. These correspond to the left
     * channel of the ADC and DAC, which are not used here
     * XXX not sure why the right channel is not at index 0 */
    for(size_t i = 1; i < buf_len; i+=2)
    {
        if(buf[i] == INT32_MIN || buf[i] == INT32_MAX)
        {
            shrapnel::events::input_clipped.clear();
            shrapnel::events::input_clipped.notify_all();
        }
        fbuf[i/2] = buf[i]/(float)INT32_MAX;
    }
    gate_set_threshold(*gate_threshold, *gate_hysteresis);
    gate_set_attack(*gate_attack);
    gate_set_hold(*gate_hold);
    gate_set_release(*gate_release);
    profiling_mark_stage(0);
    gate_analyse(fbuf, buf_len/2);
    profiling_mark_stage(1);
    valvestate->set_gain(*amp_gain, *amp_channel);
    valvestate->set_fmv(*bass, *middle, *treble);
    valvestate->set_contour(*contour);
    valvestate->set_volume(decibel_to_ratio(*volume));
    profiling_mark_stage(2);
    valvestate->process(fbuf, buf_len/2);
    profiling_mark_stage(3);
    if(*gate_bypass < 0.5f)
    {
        gate_process(fbuf, buf_len/2);
    }
    profiling_mark_stage(4);
    /* speaker IR */
    speaker->process(fbuf);
    profiling_mark_stage(17);
    chorus->set_modulation_rate_hz(*chorus_rate);
    chorus->set_modulation_depth(*chorus_depth);
    chorus->set_modulation_mix(*chorus_mix);
    profiling_mark_stage(18);
    if(*chorus_bypass < 0.5f)
    {
        chorus->process(fbuf, buf_len/2);
    }
    profiling_mark_stage(19);
    wah->set_expression_position(*wah_position);
    wah->set_vocal(*wah_vocal);
    if(*wah_bypass < 0.5f)
    {
        wah->process(fbuf, buf_len/2);
    }
    for(size_t i = 1; i < buf_len; i+=2)
    {
        if(fbuf[i/2] > 1.f || fbuf[i/2] < -1.f)
        {
            shrapnel::events::output_clipped.clear();
            shrapnel::events::output_clipped.notify_all();
        }
        if(fbuf[i/2] != fbuf[i/2])
        {
            ESP_LOGE(TAG, "Not a number at index %d", i);
            assert(0);
        }
        buf[i] = float_to_int32(fbuf[i/2]);
    }
    profiling_mark_stage(20);
    profiling_stop();
    gpio_set_level(g_profiling_gpio, 0);
    ESP_LOGD(TAG, "stack: %d", uxTaskGetStackHighWaterMark(NULL));
}
References decibel_to_ratio(), fbuf, float_to_int32(), g_profiling_gpio, gate_analyse(), gate_process(), gate_set_attack(), gate_set_hold(), gate_set_release(), gate_set_threshold(), shrapnel::events::input_clipped, shrapnel::events::output_clipped, profiling_mark_stage(), profiling_start(), profiling_stop(), and shrapnel::parameters::TAG.
Referenced by i2s_processing_task().