ShrapnelDSP: firmware/components/i2s/include/profiling.h File Reference
profiling.h File Reference
Functions
void profiling_start (void)
void profiling_mark_stage (unsigned int stage)
void profiling_stop (void)
void i2s_profiling_task (void *param)
Variables
SemaphoreHandle_t profiling_mutex
Function Documentation
i2s_profiling_task()
void i2s_profiling_task (void * param)
Definition at line 83 of file profiling.cpp.
{
    (void) param;
    cpu_freq_mhz = ets_get_cpu_frequency();
    ESP_LOGI(TAG, "CPU frequency: %d MHz", cpu_freq_mhz);
    while(1)
    {
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        if(xSemaphoreTake(profiling_mutex, 100 / portTICK_PERIOD_MS))
        {
            ESP_LOGI(TAG, " ========= \n");
            int64_t total_cycles = 0;
            for(int i = 0; i < NUMBER_OF_STAGES; i++)
            {
                //if the stage has not been assigned, stop printing
                if(stage_cycles[i] == 0)
                {
                    break;
                }
                int64_t current_stage_cycles = stage_cycles[i] - ((i == 0) ? start_cycles : stage_cycles[i - 1]);
                ESP_LOGI(TAG, "Stage %3d processing took %7lld cycles %4lld us (%03.1f %%)",
                        i,
                        current_stage_cycles,
                        cycles_to_us(current_stage_cycles),
                        cycles_to_percent(current_stage_cycles));
                total_cycles += current_stage_cycles;
            }
            ESP_LOGI(TAG, "Total processing took     %7lld cycles %4lld us (%03.1f %%)",
                    total_cycles,
                    cycles_to_us(total_cycles),
                    cycles_to_percent(total_cycles));
            ESP_LOGI(TAG, " ========= \n");
            xSemaphoreGive(profiling_mutex);
        }
        else
        {
            ESP_LOGE(TAG, "%s failed to take semaphore", __FUNCTION__);
        }
    }
}
References cpu_freq_mhz, cycles_to_percent(), cycles_to_us(), profiling_mutex, stage_cycles, start_cycles, and shrapnel::parameters::TAG.
Referenced by shrapnel::app_main().
profiling_mark_stage()
void profiling_mark_stage (unsigned int stage)
Definition at line 48 of file profiling.cpp.
{
    assert(stage < NUMBER_OF_STAGES);
    if(got_semaphore)
    {
        stage_cycles[stage] = cpu_hal_get_cycle_count();
    }
}
References got_semaphore, and stage_cycles.
Referenced by process_samples().
profiling_start()
void profiling_start (void)
Definition at line 39 of file profiling.cpp.
{
    if(xSemaphoreTake(profiling_mutex, 0))
    {
        got_semaphore = true;
        start_cycles = cpu_hal_get_cycle_count();
    }
}
References got_semaphore, profiling_mutex, and start_cycles.
Referenced by process_samples().
profiling_stop()
void profiling_stop (void)
Definition at line 58 of file profiling.cpp.
{
    if(got_semaphore)
    {
        xSemaphoreGive(profiling_mutex);
        got_semaphore = false;
    }
}
References got_semaphore, and profiling_mutex.
Referenced by process_samples().
Variable Documentation
profiling_mutex
SemaphoreHandle_t profiling_mutex extern
Definition at line 35 of file profiling.cpp.
Referenced by shrapnel::app_main(), i2s_profiling_task(), profiling_start(), and profiling_stop().