on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache
  CCACHE_DIR: /ccache

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:3
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}

    - name: ccache reset statistics
      run: ccache --zero-stats

    # This could be two different steps, but we need to preserve the
    # environment that is set up by export.sh
    - name: Setup ESP-IDF and build
      run: . $IDF_PATH/export.sh && idf.py -C firmware build

    - name: ccache statistics
      run: ccache --show-stats

  build-plugins:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:3
    strategy:
      matrix:
        plugin: ["chorus",  "gate", "vibrato"]
        build_type: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ matrix.plugin }}-${{ matrix.build_type }}

    - name: ccache reset statistics
      run: ccache --zero-stats

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} plugins/${{matrix.plugin}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: ccache statistics
      run: ccache --show-stats

  ctest:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:3
    strategy:
      matrix:
        build_type: ["Release", "Debug"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ matrix.build_type }}

    - name: ccache reset statistics
      run: ccache --zero-stats

    - run: pwd
    - run: ctest --version

    - name: Configure CMake
      env:
        CXXFLAGS: "-fprofile-arcs -ftest-coverage"
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} test

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: /__w/ShrapnelMonorepo/ShrapnelMonorepo/build
      run: ctest -C ${{matrix.build_type}}

    - name: ccache statistics
      run: ccache --show-stats

    - name: Coverage
      if: build_type == 'Debug'
      run: lcov --capture --directory build -o lcov.info

    - name: Coveralls
      if: build_type == 'Debug'
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: lcov.info
        # TODO base-path: test
