name: GitHub Actions Demo

on: [push]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:1
    steps:
      - run: echo "TODO build firmware"

  build-plugins:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:1
    strategy:
      matrix:
        plugin: ["chorus",  "gate", "vibrato"]
        build_type: ["Release", "Debug"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} plugins/${{matrix.plugin}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

  ctest:
    runs-on: ubuntu-latest
    container: barabas5532/shrapnel:1
    strategy:
      matrix:
        build_type: ["Release", "Debug"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} test

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
