name: StrictDoc Github Pages

# TODO deploy to pages only for push on master
#      strictdoc and doxygen export should be checked for success on all branches
on: pull_request

env:
  FLUTTER_VERSION: '3.0.3'
  FLUTTER_CHANNEL: 'stable'

jobs:
  strictdoc:
    name: Generate StrictDoc
    runs-on: ubuntu-latest
    container: barabas5532/strictdoc:0.0.26
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Debug working directory
      run: pwd

    - name: StrictDoc export
      run: strictdoc export requirements

    - name: Debug output directory
      run: ls -Ral .

    - uses: actions/upload-artifact@v3
      with:
        name: requirements
        path: output/html
        retention-days: 5

  doxygen:
    name: Generate Doxygen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4

    - name: Debug output directory
      run: ls -Ral docs

    - uses: actions/upload-artifact@v3
      with:
        name: firmware-docs
        path: docs/html
        retention-days: 5

  dart-doc:
    name: Generate dart doc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          frontend
    steps:
    - uses: actions/checkout@v3

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true
        cache-key: ${{ github.job }}

    - name: Flutter pub cache
      uses: actions/cache@v2
      with:
        path: ${{ env.PUB_CACHE }}
        key: flutter-pub-${{ github.job }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          flutter-pub-${{ github.job }}-

    - run: flutter pub get
    - run: dart doc .

    - uses: actions/upload-artifact@v3
      with:
        name: frontend-docs
        path: doc/api
        retention-days: 5

  deploy:
    needs: [strictdoc, doxygen, dart-doc]
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: html

    - name: Display structure of downloaded files
      run: ls -R

    # TODO https://github.com/peaceiris/actions-gh-pages is more popular
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: html
        keep_history: true
        allow_empty_commit: false
        jekyll: no
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
